ApplyUpdateAssistant(SC('KIA_Niro_Gasoline_PHEV_051b50382a8243449732d6289abbef96'))
ApplyUpdateAssistant(SC('KIA_Niro_Gasoline_PHEV_a834932faf334744b1aa05784c581ce6'))
AMEAddComponent("VeDy.datafile_import_tool", "datafile_import_tool", (1474,178), True, SC(''))
AMEMoveComponent("datafile_import_tool", (1403,294), True)
AMEAddComponent("VeDy.datafile_import_tool", "datafile_import_tool_1", (1403,384), True, SC(''))
AMEMoveComponent("datafile_import_tool_1", (1403,381), True)
AMEAddComponent("VeDy.datafile_import_tool", "datafile_import_tool_2", (1403,468), True, SC(''))
AMEMoveComponent("datafile_import_tool_1", (1403,382), True)
AMESetParameterValue("vehtype@vehicle", "1")
#GUIMacroCommand
Undo(SC(''))
AMESetParameterValue("dir@engine", "${circuit_name}_.HOT/KIA_Niro_Gasoline/eng")
AMESetParameterValue("cycleused@driver", "1")
AMESetParameterValue("cycleused@driver", "cycle")
AMESetParameterValue("cycleused@driver", "cycleused")
AMESetParameterValue("direng@ECMS", "${circuit_name}_.HOT/KIA_Niro_Gasoline/eng")
AMESetParameterValue("dir@engine", "dir_eng")
AMESetParameterValue("direng@ECMS", "dir_eng")
AMESetParameterValue("vehtype@vehicle", "1")
#GUIMacroCommand
Undo(SC(''))

AMESetParameterValue("vehtype@vehicle", "1")
#GUIMacroCommand
Undo(SC(''))
#SIMAddInfoItemCmd
#Command logging not implemented for command SIMChangeInfoItemCmd
#Command logging not implemented for command SIMChangeInfoItemCmd
#SIMAddInfoItemCmd
#Command logging not implemented for command SIMChangeInfoItemCmd
#SIMAddInfoItemCmd
#Command logging not implemented for command SIMChangeInfoItemCmd
#Command logging not implemented for command SIMChangeInfoItemCmd
#Command logging not implemented for command SIMChangeInfoItemCmd
#Command logging not implemented for command SIMChangeInfoItemCmd
#SIMAddInfoItemCmd
#ResizeImage
#Command logging not implemented for command SIMChangeInfoItemCmd
#Command logging not implemented for command SIMChangeInfoItemCmd
#Command logging not implemented for command SIMChangeInfoItemCmd
#SIMAddInfoItemCmd
#ResizeImage
#Command logging not implemented for command SIMChangeInfoItemCmd
#Command logging not implemented for command SIMChangeInfoItemCmd
#ResizeImage
#SIMAddInfoItemCmd
#Command logging not implemented for command SIMChangeInfoItemCmd
#Command logging not implemented for command SIMChangeInfoItemCmd
AMEMoveComponent("datafile_import_tool_2", (1403,469), True)
#Command logging not implemented for command SIMChangeInfoItemCmd
#Command logging not implemented for command SIMChangeInfoItemCmd
#Command logging not implemented for command SIMChangeInfoItemCmd
#Command logging not implemented for command SIMChangeInfoItemCmd
AMEMoveComponent("datafile_import_tool_2", (1354,581), True)
AMEMoveComponent("datafile_import_tool_1", (1354,494), True)
AMEMoveComponent("datafile_import_tool", (1354,406), True)
#Command logging not implemented for command SIMChangeInfoItemCmd
#Command logging not implemented for command SIMChangeInfoItemCmd
#Command logging not implemented for command SIMChangeInfoItemCmd
#SIMAddInfoItemCmd
#Command logging not implemented for command SIMChangeInfoItemCmd
#Command logging not implemented for command SIMChangeVariableCmd
#Command logging not implemented for command SIMChangeVariableCmd
#Command logging not implemented for command SIMChangeVariableCmd
#Command logging not implemented for command SIMChangeVariableCmd
#Command logging not implemented for command SIMChangeVariableCmd
#Command logging not implemented for command SIMChangeVariableCmd
#Command logging not implemented for command SIMChangeVariableCmd
#Command logging not implemented for command SIMChangeVariableCmd
#Command logging not implemented for command SIMChangeVariableCmd
#Command logging not implemented for command SIMChangeVariableCmd
#Command logging not implemented for command SIMChangeVariableCmd
#Command logging not implemented for command SIMChangeVariableCmd
#Command logging not implemented for command SIMChangeVariableCmd
#Command logging not implemented for command SIMChangeVariableCmd
#Command logging not implemented for command SIMChangeVariableCmd
#Command logging not implemented for command SIMChangeVariableCmd
#Command logging not implemented for command SIMChangeVariableCmd
#Command logging not implemented for command SIMChangeVariableCmd
#Command logging not implemented for command SIMChangeVariableCmd
#Command logging not implemented for command SIMChangeVariableCmd
#SIMAddInfoItemCmd
#Command logging not implemented for command SIMChangeVariableCmd
#Command logging not implemented for command SIMChangeVariableCmd
#Command logging not implemented for command SIMChangeVariableCmd
#Command logging not implemented for command SIMChangeVariableCmd
#Command logging not implemented for command SIMChangeVariableCmd
#Command logging not implemented for command SIMChangeVariableCmd
AMEMoveComponent("runstats", (60,73), True)
ApplyUpdateAssistant(SC('PlugInHybridElectricVehicle_1a3939b070f34ed487ccf0dadacaedec'))
AMESetParameterValue("massVeh", "2454")
AMESetParameterValue("c0", "195")
AMESetParameterValue("c1", "2.9988")
AMESetParameterValue("c2", "0.410832")
AMESetParameterValue("fronttirewidth", "225")
AMESetParameterValue("fronttireheight", "45")
AMESetParameterValue("fronttiredrim", "18")
AMESetParameterValue("reartirewidth", "225")
AMESetParameterValue("reartireheight", "45")
AMESetParameterValue("reartiredrim", "18")
AMESetParameterValue("maxbrakefront", "8094.519")
AMESetParameterValue("slope", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/slope.data")
AMESetParameterValue("altitude", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/altitude.data")
AMESetParameterValue("cycle", "1")
AMESetParameterValue("pelecFile", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/pelec.data")
AMESetParameterValue("pmechFile", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/pmech.data")
AMESetParameterValue("dir_eng", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/eng")
AMESetParameterValue("cyl", "1.95")
AMESetParameterValue("LHV_fuel", "44000")
AMESetParameterValue("maxspeed", "4000")
AMESetParameterValue("engInertia", "0.195")
AMESetParameterValue("maxfrct", "1200")
AMESetParameterValue("fuelden", "834.7")
AMESetParameterValue("Teng_init", "22.88")
AMESetParameterValue("ocvfile", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/bat/ocv.data")
AMESetParameterValue("socInit", "15")
AMESetParameterValue("nbpar", "100")
AMESetParameterValue("rfile", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/bat/resistance.data")
AMESetParameterValue("nbser", "100")
AMESetParameterValue("capacell", "0.37802846789001")
AMESetParameterValue("umaxBT", "628.2")
AMESetParameterValue("uminBT", "145.8")
AMESetParameterValue("methU", "2")
AMESetParameterValue("deltaSOC", "2")
AMESetParameterValue("tmaxMotPeak", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/mot/tmax_peak.data")
AMESetParameterValue("tminMotPeak", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/mot/tmin_peak.data")
AMESetParameterValue("motlosses", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/mot/losses.data")
AMESetParameterValue("tmaxMotC", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/mot/tmax_continuous.data")
AMESetParameterValue("tminMotC", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/mot/tmin_continuous.data")
AMESetParameterValue("nforratio", "9")
AMESetParameterValue("ratiosRd1", "5.354")
AMESetParameterValue("ratiosRd2", "3.243")
AMESetParameterValue("ratiosRd3", "2.252")
AMESetParameterValue("ratiosRd4", "1.636")
AMESetParameterValue("ratiosRd5", "1.211")
AMESetParameterValue("ratiosRd6", "1")
AMESetParameterValue("ratiosRd7", "0.865")
AMESetParameterValue("ratiosRd8", "0.717")
AMESetParameterValue("ratiosRd9", "0.601")
AMESetParameterValue("finalratioRd", "2.64")
AMESetParameterValue("initS", "2.407")
AMESetParameterValue("vmaxel", "50")
AMESetParameterValue("socfinal", "17")
AMESetParameterValue("qswitchfile", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/transmission_switch.data")
AMESetParameterValue("Tslips@rdgearbox", "Tslips")
AMESetParameterValue("tengstart@ECMS", "tengstart")
AMESetParameterValue("Tslips", "11136.319994646")
AMESetParameterValue("tengstart", "wlaunch*(pi/30.0)*engInertia*4+8.8")
AMESetParameterValue("massVeh", "2152")
AMESetParameterValue("c0", "223.9")
AMESetParameterValue("c1", "2.0196")
AMESetParameterValue("c2", "0.4339008")
AMESetParameterValue("fronttirewidth", "245")
AMESetParameterValue("fronttireheight", "40")
AMESetParameterValue("reartirewidth", "245")
AMESetParameterValue("reartireheight", "40")
AMESetParameterValue("maxbrakefront", "7028.432")
AMESetParameterValue("slope", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Gasoline/slope.data")
AMESetParameterValue("altitude", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Gasoline/altitude.data")
AMESetParameterValue("pelecFile", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Gasoline/pelec.data")
AMESetParameterValue("pmechFile", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Gasoline/pmech.data")
AMESetParameterValue("dir_eng", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Gasoline/eng")
AMESetParameterValue("cyl", "1.991")
AMESetParameterValue("LHV_fuel", "42000")
AMESetParameterValue("maxspeed", "6000")
AMESetParameterValue("engInertia", "0.1991")
AMESetParameterValue("maxfrct", "1050")
AMESetParameterValue("fuelden", "750.3")
AMESetParameterValue("Teng_init", "22.75")
AMESetParameterValue("ocvfile", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Gasoline/bat/ocv.data")
AMESetParameterValue("socInit", "9")
AMESetParameterValue("rfile", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Gasoline/bat/resistance.data")
AMESetParameterValue("deltaSOC", "7")
AMESetParameterValue("tmaxMotPeak", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Gasoline/mot/tmax_peak.data")
AMESetParameterValue("tminMotPeak", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Gasoline/mot/tmin_peak.data")
AMESetParameterValue("motlosses", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Gasoline/mot/losses.data")
AMESetParameterValue("tmaxMotC", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Gasoline/mot/tmax_continuous.data")
AMESetParameterValue("tminMotC", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Gasoline/mot/tmin_continuous.data")
AMESetParameterValue("Tslips", "10333.214646")
AMESetParameterValue("initS", "2.55")
AMESetParameterValue("vmaxel", "36")
AMESetParameterValue("socfinal", "16")
AMESetParameterValue("qswitchfile", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Gasoline/transmission_switch.data")
AMESetParameterValue("cycle", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Gasoline/cycle.data")
AMESetParameterValue("trratio7@rdgearbox", "ratiosRd7")
AMESetParameterValue("trratio8@rdgearbox", "ratioRd8")
AMESetParameterValue("trratio8@rdgearbox", "ratiosRd8")
AMESetParameterValue("nforratio@rdgearbox", "nforratioint")
AMESetParameterValue("nforratio@rdgearbox", "nforratio")
AMESetParameterValue("nforratio", "10")
AMESetParameterValue("trratio9@rdgearbox", "ratiosRd9")
AMESetParameterValue("eff7@rdgearbox", "effRd7")
AMESetParameterValue("eff8@rdgearbox", "effRd8")
AMESetParameterValue("eff9@rdgearbox", "effRd9")
AMESetParameterValue("eff7@rdgearbox", "effsRd7")
AMESetParameterValue("eff8@rdgearbox", "effsRd8")
AMESetParameterValue("eff9@rdgearbox", "effsRd9")
AMESetParameterValue("tau@lag", "0")
AMESetParameterValue("tau@lag_pmeca", "0")
AMESetParameterValue("k@lag", "0")
AMESetParameterValue("k@lag_pmeca", "0")
#GUIMacroCommand
#GUIMacroCommand
Undo(SC(''))
#GUIMacroCommand
Undo(SC(''))
#GUIMacroCommand
#GUIMacroCommand
Undo(SC(''))
#GUIMacroCommand
Undo(SC(''))
AMESetParameterValue("ratiosrd7@ECMS", "ratiosRd7")
AMESetParameterValue("ratiosrd8@ECMS", "ratiosRd8")
AMESetParameterValue("ratiosrd9@ECMS", "ratiosRd9")
AMESetParameterValue("effsrd7@ECMS", "effsRd7")
AMESetParameterValue("effsrd8@ECMS", "effsRd8")
AMESetParameterValue("effsrd9@ECMS", "effsRd9")
AMESetParameterValue("Tclutch", "1929.999")
AMESetParameterValue("fslip@rdclutch", "Tclutch")
AMESetParameterValue("fstick@rdclutch", "Tclutch")
AMESetParameterValue("methqswitch@ECMS", "3")
AMESetParameterValue("methqswitch", "3")
AMESetParameterValue("massVeh", "2454")
AMESetParameterValue("c0", "195")
AMESetParameterValue("c1", "2.9988")
AMESetParameterValue("c2", "0.410832")
AMESetParameterValue("fronttirewidth", "225")
AMESetParameterValue("fronttireheight", "45")
AMESetParameterValue("reartirewidth", "225")
AMESetParameterValue("reartireheight", "45")
AMESetParameterValue("maxbrakefront", "8094.519")
AMESetParameterValue("slope", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/slope.data")
AMESetParameterValue("altitude", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/altitude.data")
AMESetParameterValue("cycle", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/cycle.data")
AMESetParameterValue("pelecFile", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/pelec.data")
AMESetParameterValue("pmechFile", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/pmech.data")
AMESetParameterValue("dir_eng", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/eng")
AMESetParameterValue("cyl", "1.95")
AMESetParameterValue("LHV_fuel", "44000")
AMESetParameterValue("maxspeed", "4000")
AMESetParameterValue("engInertia", "0.195")
AMESetParameterValue("maxfrct", "1200")
AMESetParameterValue("fuelden", "834.7")
AMESetParameterValue("Teng_init", "22.88")
AMESetParameterValue("ocvfile", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/bat/ocv.data")
AMESetParameterValue("socInit", "15")
AMESetParameterValue("rfile", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/bat/resistance.data")
AMESetParameterValue("deltaSOC", "2")
AMESetParameterValue("tmaxMotPeak", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/mot/tmax_peak.data")
AMESetParameterValue("tminMotPeak", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/mot/tmin_peak.data")
AMESetParameterValue("motlosses", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/mot/losses.data")
AMESetParameterValue("tmaxMotC", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/mot/tmax_continuous.data")
AMESetParameterValue("tminMotC", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/mot/tmin_continuous.data")
AMESetParameterValue("Tslips", "11136.319994646")
AMESetParameterValue("Tclutch", "2079.999999")
AMESetParameterValue("initS", "2.407")
AMESetParameterValue("vmaxel", "50")
AMESetParameterValue("socfinal", "17")
AMESetParameterValue("qswitchfile", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/transmission_switch.data")
AMESetParameterValue("massVeh", "1620")
AMESetParameterValue("c0", "92.9")
AMESetParameterValue("c1", "3.2112")
AMESetParameterValue("c2", "0.42768")
AMESetParameterValue("fronttirewidth", "208")
AMESetParameterValue("fronttireheight", "60")
AMESetParameterValue("fronttiredrim", "16")
AMESetParameterValue("reartirewidth", "208")
AMESetParameterValue("reartireheight", "60")
AMESetParameterValue("reartiredrim", "16")
AMESetParameterValue("maxbrakefront", "5313.6")
AMESetParameterValue("slope", "${circuit_name}_.HOT/KIA_Niro_Gasoline/slope.data")
AMESetParameterValue("altitude", "${circuit_name}_.HOT/KIA_Niro_Gasoline/altitude.data")
AMESetParameterValue("cycle", "${circuit_name}_.HOT/KIA_Niro_Gasoline/cycle.data")
AMESetParameterValue("pelecFile", "${circuit_name}_.HOT/KIA_Niro_Gasoline/pelec.data")
AMESetParameterValue("pmechFile", "${circuit_name}_.HOT/KIA_Niro_Gasoline/pmech.data")
AMESetParameterValue("dir_eng", "${circuit_name}_.HOT/KIA_Niro_Gasoline/eng")
AMESetParameterValue("cyl", "1.58")
AMESetParameterValue("LHV_fuel", "42000")
AMESetParameterValue("maxspeed", "6000")
AMESetParameterValue("engInertia", "0.1")
AMESetParameterValue("maxfrct", "441")
AMESetParameterValue("fuelden", "750.3")
AMESetParameterValue("Teng_init", "24")
AMESetParameterValue("ocvfile", "${circuit_name}_.HOT/KIA_Niro_Gasoline/bat/ocv.data")
AMESetParameterValue("socInit", "17")
AMESetParameterValue("nbpar", "96")
AMESetParameterValue("rfile", "${circuit_name}_.HOT/KIA_Niro_Gasoline/bat/resistance.data")
AMESetParameterValue("nbser", "110")
AMESetParameterValue("capacell", "0.257070202249241")
AMESetParameterValue("umaxBT", "564.35515356")
AMESetParameterValue("uminBT", "147.76432561")
AMESetParameterValue("methU", "1")
AMESetParameterValue("deltaSOC", "-4")
AMESetParameterValue("tmaxMotPeak", "${circuit_name}_.HOT/KIA_Niro_Gasoline/mot/tmax_peak.data")
AMESetParameterValue("tminMotPeak", "${circuit_name}_.HOT/KIA_Niro_Gasoline/mot/tmin_peak.data")
AMESetParameterValue("motlosses", "${circuit_name}_.HOT/KIA_Niro_Gasoline/mot/losses.data")
AMESetParameterValue("tmaxMotC", "${circuit_name}_.HOT/KIA_Niro_Gasoline/mot/tmax_continuous.data")
AMESetParameterValue("tminMotC", "${circuit_name}_.HOT/KIA_Niro_Gasoline/mot/tmin_continuous.data")
AMESetParameterValue("nforratio", "7")
AMESetParameterValue("ratiosRd1", "3.867")
AMESetParameterValue("ratiosRd2", "2.217")
AMESetParameterValue("ratiosRd3", "1.371")
AMESetParameterValue("ratiosRd4", "0.93")
AMESetParameterValue("ratiosRd5", "0.695")
AMESetParameterValue("ratiosRd6", "0.585")
AMESetParameterValue("ratiosRd7", "0")
AMESetParameterValue("ratiosRd8", "0")
AMESetParameterValue("ratiosRd9", "0")
AMESetParameterValue("finalratioRd", "4.438")
AMESetParameterValue("Tslips", "3020.13")
AMESetParameterValue("Tclutch", "781")
AMESetParameterValue("initS", "2.459")
AMESetParameterValue("vmaxel", "33.333")
AMESetParameterValue("socfinal", "13")
AMESetParameterValue("qswitchfile", "${circuit_name}_.HOT/KIA_Niro_Gasoline/transmission_switch.data")
AMESetParameterValue("tengstart", "wlaunch*(pi/30.0)*engInertia*4+17.6")
AMESetParameterValue("methqswitch", "2")
AMESetParameterValue("methqswitch@ECMS", "methqswitch")
ApplyUpdateAssistant(SC('PlugInHybridElectricVehicle_7fc8c3093b80486fbc92ff6c7f26914f'))
#Command logging not implemented for command SIMChangeVariableCmd
#SIMAddInfoItemCmd
#DelInfoItemCmd
#SIMAddInfoItemCmd
#SIMAddInfoItemCmd
#DelInfoItemCmd
#SIMAddInfoItemCmd
AMEConnectComponentToLine("wheelspeed", 2, "rotary", 0)
AMEConnectComponentToLine("vehicle", 3, "rotary", 1)
AMEConnectComponentToLine("dup1", 0, "control", 0)
AMEConnectComponentToLine("tempconv2", 0, "control", 1)
AMEConnectComponentToLine("dup1", 1, "control_1", 0)
AMEConnectComponentToLine("engine", 6, "control_1", 1)
AMEConnectComponentToLine("dup1", 2, "control_2", 0)
AMEConnectComponentToLine("tempconv1", 0, "control_2", 1)
AMEConnectComponentToLine("eng_trq_sensor", 0, "rotary_1", 0)
AMEConnectComponentToLine("pmeca_connector", 2, "rotary_1", 1)
AMEConnectComponentToLine("batmass", 0, "electrical", 0)
AMEConnectComponentToLine("battery", 1, "electrical", 1)
AMEConnectComponentToLine("elecfit", 4, "electrical_1", 0)
AMEConnectComponentToLine("elecmass", 0, "electrical_1", 1)
AMEConnectComponentToLine("motmass", 0, "electrical_2", 0)
AMEConnectComponentToLine("motor", 5, "electrical_2", 1)
AMEConnectComponentToLine("elec_splitter_pos", 1, "electrical_3", 0)
AMEConnectComponentToLine("elec_splitter_volt", 1, "electrical_3", 1)
AMEConnectComponentToLine("elecfit", 3, "electrical_4", 0)
AMEConnectComponentToLine("elec_splitter_pos", 2, "electrical_4", 1)
AMEConnectComponentToLine("elec_splitter_pos", 0, "electrical_5", 0)
AMEConnectComponentToLine("motor", 4, "electrical_5", 1)
AMEConnectComponentToLine("SN2", 0, "rotary_2", 0)
AMEConnectComponentToLine("engclutch", 0, "rotary_2", 1)
AMEConnectComponentToLine("SN2", 1, "rotary_3", 0)
AMEConnectComponentToLine("motor", 1, "rotary_3", 1)
AMEConnectComponentToLine("rdgearbox", 1, "rotary_4", 0)
AMEConnectComponentToLine("wheelspeed", 0, "rotary_4", 1)
AMEConnectComponentToLine("dynamic_mux2", 0, "control_3", 0)
AMEConnectComponentToLine("ECMS", 11, "control_3", 1)
AMEConnectComponentToLine("ECMS", 15, "control_4", 0)
AMEConnectComponentToLine("wheelspeed", 1, "control_4", 1)
AMEConnectComponentToLine("ECMS", 17, "control_5", 0)
AMEConnectComponentToLine("driver", 3, "control_5", 1)
AMEConnectComponentToLine("ECMS", 18, "control_6", 0)
AMEConnectComponentToLine("driver", 2, "control_6", 1)
AMEConnectComponentToLine("ECMS", 19, "control_7", 0)
AMEConnectComponentToLine("driver", 1, "control_7", 1)
AMEConnectComponentToLine("vehInfoSplit", 0, "control_8", 0)
AMEConnectComponentToLine("vehInfoSplitDriver", 2, "control_8", 1)
AMEConnectComponentToLine("vehInfoSplitDriver", 0, "control_9", 0)
AMEConnectComponentToLine("PTsrc", 1, "control_9", 1)
AMEConnectComponentToLine("vehInfoSplit", 1, "control_10", 0)
AMEConnectComponentToLine("getVehSpeed", 1, "control_10", 1)
AMEConnectComponentToLine("vehInfoSplit", 2, "control_11", 0)
AMEConnectComponentToLine("vehicle", 11, "control_11", 1)
AMEAddComponent("VeDy.datafile_import_tool", "datafile_import_tool_3", (1360,728), True, SC(''))
#SIMAddInfoItemCmd
#SIMAddInfoItemCmd
#SIMAddInfoItemCmd
#Command logging not implemented for command SIMClearSelectionCmd
#DelInfoItemCmd
#Command logging not implemented for command SIMChangeInfoItemCmd
#Command logging not implemented for command SIMChangeInfoItemCmd
#Command logging not implemented for command SIMChangeInfoItemCmd
#Command logging not implemented for command SIMChangeInfoItemCmd
#Command logging not implemented for command SIMChangeInfoItemCmd
#Command logging not implemented for command SIMChangeInfoItemCmd
#Command logging not implemented for command SIMChangeInfoItemCmd
#Command logging not implemented for command SIMChangeInfoItemCmd
#Command logging not implemented for command SIMChangeInfoItemCmd
#Command logging not implemented for command SIMChangeInfoItemCmd
AMEMoveComponent("datafile_import_tool_3", (1458,407), True)
#Command logging not implemented for command SIMChangeInfoItemCmd
#Command logging not implemented for command SIMChangeInfoItemCmd
#Command logging not implemented for command SIMChangeInfoItemCmd
#Command logging not implemented for command SIMClearSelectionCmd
#DelInfoItemCmd
#Command logging not implemented for command SIMClearSelectionCmd
#DelInfoItemCmd
#Command logging not implemented for command SIMChangeInfoItemCmd
#Command logging not implemented for command SIMChangeInfoItemCmd
#DelInfoItemCmd
#SIMAddInfoItemCmd
#Command logging not implemented for command SIMChangeInfoItemCmd
#Command logging not implemented for command SIMChangeInfoItemCmd
#Command logging not implemented for command SIMChangeInfoItemCmd
AMESetParameterValue("massVeh", "1663")
AMESetParameterValue("c0", "129")
AMESetParameterValue("c1", "3.834")
AMESetParameterValue("c2", "0.402408")
AMESetParameterValue("maxbrakefront", "5454.64")
AMESetParameterValue("slope", "${circuit_name}_.HOT/KIA_Niro_FHEV/slope.data")
AMESetParameterValue("altitude", "${circuit_name}_.HOT/KIA_Niro_FHEV/altitude.data")
AMESetParameterValue("cycle", "${circuit_name}_.HOT/KIA_Niro_FHEV/cycle.data")
AMESetParameterValue("pelecFile", "${circuit_name}_.HOT/KIA_Niro_FHEV/pelec.data")
AMESetParameterValue("pmechFile", "${circuit_name}_.HOT/KIA_Niro_FHEV/pmech.data")
AMESetParameterValue("dir_eng", "${circuit_name}_.HOT/KIA_Niro_FHEV/eng")
AMESetParameterValue("Teng_init", "90")
AMESetParameterValue("ocvfile", "${circuit_name}_.HOT/KIA_Niro_FHEV/bat/ocv.data")
AMESetParameterValue("socInit", "50")
AMESetParameterValue("nbpar", "64")
AMESetParameterValue("rfile", "${circuit_name}_.HOT/KIA_Niro_FHEV/bat/resistance.data")
AMESetParameterValue("nbser", "74")
AMESetParameterValue("capacell", "0.101495165729582")
AMESetParameterValue("umaxBT", "379.657103304")
AMESetParameterValue("uminBT", "99.405091774")
AMESetParameterValue("tmaxMotPeak", "${circuit_name}_.HOT/KIA_Niro_FHEV/mot/tmax_peak.data")
AMESetParameterValue("tminMotPeak", "${circuit_name}_.HOT/KIA_Niro_FHEV/mot/tmin_peak.data")
AMESetParameterValue("motlosses", "${circuit_name}_.HOT/KIA_Niro_FHEV/mot/losses.data")
AMESetParameterValue("tmaxMotC", "${circuit_name}_.HOT/KIA_Niro_FHEV/mot/tmax_continuous.data")
AMESetParameterValue("tminMotC", "${circuit_name}_.HOT/KIA_Niro_FHEV/mot/tmin_continuous.data")
AMESetParameterValue("ratiosRd6", "0.558")
AMESetParameterValue("effsRd1", "0.925")
AMESetParameterValue("effsRd2", "0.925")
AMESetParameterValue("effsRd3", "0.925")
AMESetParameterValue("effsRd4", "0.925")
AMESetParameterValue("effsRd5", "0.925")
AMESetParameterValue("effsRd6", "0.925")
AMESetParameterValue("initS", "2.628")
AMESetParameterValue("vmaxel", "12")
AMESetParameterValue("socfinal", "57")
AMESetParameterValue("qswitchfile", "${circuit_name}_.HOT/KIA_Niro_FHEV/transmission_switch.data")
AMESetParameterValue("deltaSOC", "7")
AMESetParameterValue("massVeh", "1620")
AMESetParameterValue("c0", "92.9")
AMESetParameterValue("c1", "3.2112")
AMESetParameterValue("c2", "0.42768")
AMESetParameterValue("maxbrakefront", "5313.6")
AMESetParameterValue("slope", "${circuit_name}_.HOT/KIA_Niro_Gasoline/slope.data")
AMESetParameterValue("altitude", "${circuit_name}_.HOT/KIA_Niro_Gasoline/altitude.data")
AMESetParameterValue("cycle", "${circuit_name}_.HOT/KIA_Niro_Gasoline/cycle.data")
AMESetParameterValue("pelecFile", "${circuit_name}_.HOT/KIA_Niro_Gasoline/pelec.data")
AMESetParameterValue("pmechFile", "${circuit_name}_.HOT/KIA_Niro_Gasoline/pmech.data")
AMESetParameterValue("dir_eng", "${circuit_name}_.HOT/KIA_Niro_Gasoline/eng")
AMESetParameterValue("Teng_init", "24")
AMESetParameterValue("ocvfile", "${circuit_name}_.HOT/KIA_Niro_Gasoline/bat/ocv.data")
AMESetParameterValue("socInit", "17")
AMESetParameterValue("nbpar", "96")
AMESetParameterValue("rfile", "${circuit_name}_.HOT/KIA_Niro_Gasoline/bat/resistance.data")
AMESetParameterValue("nbser", "110")
AMESetParameterValue("capacell", "0.257070202249241")
AMESetParameterValue("umaxBT", "564.35515356")
AMESetParameterValue("uminBT", "147.76432561")
AMESetParameterValue("deltaSOC", "-4")
AMESetParameterValue("tmaxMotPeak", "${circuit_name}_.HOT/KIA_Niro_Gasoline/mot/tmax_peak.data")
AMESetParameterValue("tminMotPeak", "${circuit_name}_.HOT/KIA_Niro_Gasoline/mot/tmin_peak.data")
AMESetParameterValue("motlosses", "${circuit_name}_.HOT/KIA_Niro_Gasoline/mot/losses.data")
AMESetParameterValue("tmaxMotC", "${circuit_name}_.HOT/KIA_Niro_Gasoline/mot/tmax_continuous.data")
AMESetParameterValue("tminMotC", "${circuit_name}_.HOT/KIA_Niro_Gasoline/mot/tmin_continuous.data")
AMESetParameterValue("ratiosRd6", "0.585")
AMESetParameterValue("effsRd1", "0.9")
AMESetParameterValue("effsRd2", "0.9")
AMESetParameterValue("effsRd3", "0.9")
AMESetParameterValue("effsRd4", "0.9")
AMESetParameterValue("effsRd5", "0.9")
AMESetParameterValue("effsRd6", "0.9")
AMESetParameterValue("initS", "2.459")
AMESetParameterValue("vmaxel", "33.333")
AMESetParameterValue("socfinal", "13")
AMESetParameterValue("qswitchfile", "${circuit_name}_.HOT/KIA_Niro_Gasoline/transmission_switch.data")
AMESetParameterValue("massVeh", "1663")
AMESetParameterValue("c0", "129")
AMESetParameterValue("c1", "3.834")
AMESetParameterValue("c2", "0.402408")
AMESetParameterValue("maxbrakefront", "5454.64")
AMESetParameterValue("slope", "${circuit_name}_.HOT/KIA_Niro_FHEV/slope.data")
AMESetParameterValue("altitude", "${circuit_name}_.HOT/KIA_Niro_FHEV/altitude.data")
AMESetParameterValue("cycle", "${circuit_name}_.HOT/KIA_Niro_FHEV/cycle.data")
AMESetParameterValue("pelecFile", "${circuit_name}_.HOT/KIA_Niro_FHEV/pelec.data")
AMESetParameterValue("pmechFile", "${circuit_name}_.HOT/KIA_Niro_FHEV/pmech.data")
AMESetParameterValue("dir_eng", "${circuit_name}_.HOT/KIA_Niro_FHEV/eng")
AMESetParameterValue("Teng_init", "90")
AMESetParameterValue("ocvfile", "${circuit_name}_.HOT/KIA_Niro_FHEV/bat/ocv.data")
AMESetParameterValue("socInit", "50")
AMESetParameterValue("nbpar", "64")
AMESetParameterValue("rfile", "${circuit_name}_.HOT/KIA_Niro_FHEV/bat/resistance.data")
AMESetParameterValue("nbser", "74")
AMESetParameterValue("capacell", "0.101495165729582")
AMESetParameterValue("umaxBT", "379.657103304")
AMESetParameterValue("uminBT", "99.405091774")
AMESetParameterValue("deltaSOC", "7")
AMESetParameterValue("tmaxMotPeak", "${circuit_name}_.HOT/KIA_Niro_FHEV/mot/tmax_peak.data")
AMESetParameterValue("tminMotPeak", "${circuit_name}_.HOT/KIA_Niro_FHEV/mot/tmin_peak.data")
AMESetParameterValue("motlosses", "${circuit_name}_.HOT/KIA_Niro_FHEV/mot/losses.data")
AMESetParameterValue("tmaxMotC", "${circuit_name}_.HOT/KIA_Niro_FHEV/mot/tmax_continuous.data")
AMESetParameterValue("tminMotC", "${circuit_name}_.HOT/KIA_Niro_FHEV/mot/tmin_continuous.data")
AMESetParameterValue("ratiosRd6", "0.558")
AMESetParameterValue("effsRd1", "0.925")
AMESetParameterValue("effsRd2", "0.925")
AMESetParameterValue("effsRd3", "0.925")
AMESetParameterValue("effsRd4", "0.925")
AMESetParameterValue("effsRd5", "0.925")
AMESetParameterValue("effsRd6", "0.925")
AMESetParameterValue("initS", "2.628")
AMESetParameterValue("vmaxel", "12")
AMESetParameterValue("socfinal", "57")
AMESetParameterValue("qswitchfile", "${circuit_name}_.HOT/KIA_Niro_FHEV/transmission_switch.data")
AMESetParameterValue("f", "0.01")
AMESetParameterValue("k", "0")
AMESetParameterValue("wind", "0")
AMESetParameterValue("socfinal", "13")
AMESetParameterValue("socfinal", "57")
AMESetParameterValue("socf", "57")
AMESetParameterValue("J@rdcluinertia", "J_003")
AMESetParameterValue("J@rdinertia", "J_005")
AMESetParameterValue("J_before", "0.005")
AMESetParameterValue("J_after", "0.003")
AMESetParameterValue("Tslips", "3020.12")
AMESetParameterValue("Tclutch", "780.999")
AMESetParameterValue("socfinal", "100")
AMESetParameterValue("socf", "100")
AMESetParameterValue("socf", "57")
AMESetParameterValue("massVeh", "1620")
AMESetParameterValue("c0", "92.9")
AMESetParameterValue("c1", "3.2112")
AMESetParameterValue("c2", "0.42768")
AMESetParameterValue("f", "0.00587")
AMESetParameterValue("k", "0.000189839248923088")
AMESetParameterValue("wind", "4.5e-06")
AMESetParameterValue("maxbrakefront", "5313.6")
AMESetParameterValue("slope", "${circuit_name}_.HOT/KIA_Niro_Gasoline/slope.data")
AMESetParameterValue("altitude", "${circuit_name}_.HOT/KIA_Niro_Gasoline/altitude.data")
AMESetParameterValue("cycle", "${circuit_name}_.HOT/KIA_Niro_Gasoline/cycle.data")
AMESetParameterValue("pelecFile", "${circuit_name}_.HOT/KIA_Niro_Gasoline/pelec.data")
AMESetParameterValue("pmechFile", "${circuit_name}_.HOT/KIA_Niro_Gasoline/pmech.data")
AMESetParameterValue("dir_eng", "${circuit_name}_.HOT/KIA_Niro_Gasoline/eng")
AMESetParameterValue("Teng_init", "24")
AMESetParameterValue("ocvfile", "${circuit_name}_.HOT/KIA_Niro_Gasoline/bat/ocv.data")
AMESetParameterValue("socInit", "17")
AMESetParameterValue("nbpar", "96")
AMESetParameterValue("rfile", "${circuit_name}_.HOT/KIA_Niro_Gasoline/bat/resistance.data")
AMESetParameterValue("nbser", "110")
AMESetParameterValue("capacell", "0.257070202249241")
AMESetParameterValue("umaxBT", "564.35515356")
AMESetParameterValue("uminBT", "147.76432561")
AMESetParameterValue("deltaSOC", "-4")
AMESetParameterValue("tmaxMotPeak", "${circuit_name}_.HOT/KIA_Niro_Gasoline/mot/tmax_peak.data")
AMESetParameterValue("tminMotPeak", "${circuit_name}_.HOT/KIA_Niro_Gasoline/mot/tmin_peak.data")
AMESetParameterValue("motlosses", "${circuit_name}_.HOT/KIA_Niro_Gasoline/mot/losses.data")
AMESetParameterValue("tmaxMotC", "${circuit_name}_.HOT/KIA_Niro_Gasoline/mot/tmax_continuous.data")
AMESetParameterValue("tminMotC", "${circuit_name}_.HOT/KIA_Niro_Gasoline/mot/tmin_continuous.data")
AMESetParameterValue("ratiosRd6", "0.585")
AMESetParameterValue("effsRd1", "0.9")
AMESetParameterValue("effsRd2", "0.9")
AMESetParameterValue("effsRd3", "0.9")
AMESetParameterValue("effsRd4", "0.9")
AMESetParameterValue("effsRd5", "0.9")
AMESetParameterValue("effsRd6", "0.9")
AMESetParameterValue("Tslips", "3020.13")
AMESetParameterValue("Tclutch", "781")
AMESetParameterValue("initS", "2.459")
AMESetParameterValue("vmaxel", "33.333")
AMESetParameterValue("socfinal", "13")
AMESetParameterValue("socf", "13")
AMESetParameterValue("qswitchfile", "${circuit_name}_.HOT/KIA_Niro_Gasoline/transmission_switch.data")
AMESetParameterValue("J_before", "0.003")
AMESetParameterValue("J_after", "0.005")
AMESetParameterValue("massVeh", "1663")
AMESetParameterValue("c0", "129")
AMESetParameterValue("c1", "3.834")
AMESetParameterValue("c2", "0.402408")
AMESetParameterValue("f", "0.01")
AMESetParameterValue("k", "0")
AMESetParameterValue("wind", "0")
AMESetParameterValue("maxbrakefront", "5454.64")
AMESetParameterValue("slope", "${circuit_name}_.HOT/KIA_Niro_FHEV/slope.data")
AMESetParameterValue("altitude", "${circuit_name}_.HOT/KIA_Niro_FHEV/altitude.data")
AMESetParameterValue("cycle", "${circuit_name}_.HOT/KIA_Niro_FHEV/cycle.data")
AMESetParameterValue("pelecFile", "${circuit_name}_.HOT/KIA_Niro_FHEV/pelec.data")
AMESetParameterValue("pmechFile", "${circuit_name}_.HOT/KIA_Niro_FHEV/pmech.data")
AMESetParameterValue("dir_eng", "${circuit_name}_.HOT/KIA_Niro_FHEV/eng")
AMESetParameterValue("Teng_init", "90")
AMESetParameterValue("ocvfile", "${circuit_name}_.HOT/KIA_Niro_FHEV/bat/ocv.data")
AMESetParameterValue("socInit", "50")
AMESetParameterValue("nbpar", "64")
AMESetParameterValue("rfile", "${circuit_name}_.HOT/KIA_Niro_FHEV/bat/resistance.data")
AMESetParameterValue("nbser", "74")
AMESetParameterValue("capacell", "0.101495165729582")
AMESetParameterValue("umaxBT", "379.657103304")
AMESetParameterValue("uminBT", "99.405091774")
AMESetParameterValue("deltaSOC", "7")
AMESetParameterValue("tmaxMotPeak", "${circuit_name}_.HOT/KIA_Niro_FHEV/mot/tmax_peak.data")
AMESetParameterValue("tminMotPeak", "${circuit_name}_.HOT/KIA_Niro_FHEV/mot/tmin_peak.data")
AMESetParameterValue("motlosses", "${circuit_name}_.HOT/KIA_Niro_FHEV/mot/losses.data")
AMESetParameterValue("tmaxMotC", "${circuit_name}_.HOT/KIA_Niro_FHEV/mot/tmax_continuous.data")
AMESetParameterValue("tminMotC", "${circuit_name}_.HOT/KIA_Niro_FHEV/mot/tmin_continuous.data")
AMESetParameterValue("ratiosRd6", "0.558")
AMESetParameterValue("effsRd1", "0.925")
AMESetParameterValue("effsRd2", "0.925")
AMESetParameterValue("effsRd3", "0.925")
AMESetParameterValue("effsRd4", "0.925")
AMESetParameterValue("effsRd5", "0.925")
AMESetParameterValue("effsRd6", "0.925")
AMESetParameterValue("Tslips", "3020.12")
AMESetParameterValue("Tclutch", "780.999")
AMESetParameterValue("initS", "2.628")
AMESetParameterValue("vmaxel", "12")
AMESetParameterValue("socfinal", "100")
AMESetParameterValue("socf", "57")
AMESetParameterValue("qswitchfile", "${circuit_name}_.HOT/KIA_Niro_FHEV/transmission_switch.data")
AMESetParameterValue("J_before", "0.005")
AMESetParameterValue("J_after", "0.003")
AMESetParameterValue("massVeh", "1620")
AMESetParameterValue("c0", "92.9")
AMESetParameterValue("c1", "3.2112")
AMESetParameterValue("c2", "0.42768")
AMESetParameterValue("f", "0.00587")
AMESetParameterValue("k", "0.000189839248923088")
AMESetParameterValue("wind", "4.5e-06")
AMESetParameterValue("maxbrakefront", "5313.6")
AMESetParameterValue("slope", "${circuit_name}_.HOT/KIA_Niro_Gasoline/slope.data")
AMESetParameterValue("altitude", "${circuit_name}_.HOT/KIA_Niro_Gasoline/altitude.data")
AMESetParameterValue("cycle", "${circuit_name}_.HOT/KIA_Niro_Gasoline/cycle.data")
AMESetParameterValue("pelecFile", "${circuit_name}_.HOT/KIA_Niro_Gasoline/pelec.data")
AMESetParameterValue("pmechFile", "${circuit_name}_.HOT/KIA_Niro_Gasoline/pmech.data")
AMESetParameterValue("dir_eng", "${circuit_name}_.HOT/KIA_Niro_Gasoline/eng")
AMESetParameterValue("Teng_init", "24")
AMESetParameterValue("ocvfile", "${circuit_name}_.HOT/KIA_Niro_Gasoline/bat/ocv.data")
AMESetParameterValue("socInit", "17")
AMESetParameterValue("nbpar", "96")
AMESetParameterValue("rfile", "${circuit_name}_.HOT/KIA_Niro_Gasoline/bat/resistance.data")
AMESetParameterValue("nbser", "110")
AMESetParameterValue("capacell", "0.257070202249241")
AMESetParameterValue("umaxBT", "564.35515356")
AMESetParameterValue("uminBT", "147.76432561")
AMESetParameterValue("deltaSOC", "-4")
AMESetParameterValue("tmaxMotPeak", "${circuit_name}_.HOT/KIA_Niro_Gasoline/mot/tmax_peak.data")
AMESetParameterValue("tminMotPeak", "${circuit_name}_.HOT/KIA_Niro_Gasoline/mot/tmin_peak.data")
AMESetParameterValue("motlosses", "${circuit_name}_.HOT/KIA_Niro_Gasoline/mot/losses.data")
AMESetParameterValue("tmaxMotC", "${circuit_name}_.HOT/KIA_Niro_Gasoline/mot/tmax_continuous.data")
AMESetParameterValue("tminMotC", "${circuit_name}_.HOT/KIA_Niro_Gasoline/mot/tmin_continuous.data")
AMESetParameterValue("ratiosRd6", "0.585")
AMESetParameterValue("effsRd1", "0.9")
AMESetParameterValue("effsRd2", "0.9")
AMESetParameterValue("effsRd3", "0.9")
AMESetParameterValue("effsRd4", "0.9")
AMESetParameterValue("effsRd5", "0.9")
AMESetParameterValue("effsRd6", "0.9")
AMESetParameterValue("Tslips", "3020.13")
AMESetParameterValue("Tclutch", "781")
AMESetParameterValue("initS", "2.459")
AMESetParameterValue("vmaxel", "33.333")
AMESetParameterValue("socfinal", "13")
AMESetParameterValue("socf", "13")
AMESetParameterValue("qswitchfile", "${circuit_name}_.HOT/KIA_Niro_Gasoline/transmission_switch.data")
AMESetParameterValue("J_before", "0.003")
AMESetParameterValue("J_after", "0.005")
AMERemoveComponent("datafile_import_tool")
AMEAddComponent("VeDy.datafile_import_tool", "datafile_import_tool", (1354,407), True, SC(''))
AMESetParameterValue("massVeh", "1663")
AMESetParameterValue("c0", "129")
AMESetParameterValue("c1", "3.834")
AMESetParameterValue("c2", "0.402408")
AMESetParameterValue("f", "0.01")
AMESetParameterValue("k", "0")
AMESetParameterValue("wind", "0")
AMESetParameterValue("maxbrakefront", "5454.64")
AMESetParameterValue("slope", "${circuit_name}_.HOT/KIA_Niro_FHEV/slope.data")
AMESetParameterValue("altitude", "${circuit_name}_.HOT/KIA_Niro_FHEV/altitude.data")
AMESetParameterValue("cycle", "${circuit_name}_.HOT/KIA_Niro_FHEV/cycle.data")
AMESetParameterValue("pelecFile", "${circuit_name}_.HOT/KIA_Niro_FHEV/pelec.data")
AMESetParameterValue("pmechFile", "${circuit_name}_.HOT/KIA_Niro_FHEV/pmech.data")
AMESetParameterValue("dir_eng", "${circuit_name}_.HOT/KIA_Niro_FHEV/eng")
AMESetParameterValue("Teng_init", "90")
AMESetParameterValue("ocvfile", "${circuit_name}_.HOT/KIA_Niro_FHEV/bat/ocv.data")
AMESetParameterValue("socInit", "50")
AMESetParameterValue("nbpar", "64")
AMESetParameterValue("rfile", "${circuit_name}_.HOT/KIA_Niro_FHEV/bat/resistance.data")
AMESetParameterValue("nbser", "74")
AMESetParameterValue("capacell", "0.101495165729582")
AMESetParameterValue("umaxBT", "379.657103304")
AMESetParameterValue("uminBT", "99.405091774")
AMESetParameterValue("deltaSOC", "7")
AMESetParameterValue("tmaxMotPeak", "${circuit_name}_.HOT/KIA_Niro_FHEV/mot/tmax_peak.data")
AMESetParameterValue("tminMotPeak", "${circuit_name}_.HOT/KIA_Niro_FHEV/mot/tmin_peak.data")
AMESetParameterValue("motlosses", "${circuit_name}_.HOT/KIA_Niro_FHEV/mot/losses.data")
AMESetParameterValue("tmaxMotC", "${circuit_name}_.HOT/KIA_Niro_FHEV/mot/tmax_continuous.data")
AMESetParameterValue("tminMotC", "${circuit_name}_.HOT/KIA_Niro_FHEV/mot/tmin_continuous.data")
AMESetParameterValue("ratiosRd6", "0.558")
AMESetParameterValue("effsRd1", "0.925")
AMESetParameterValue("effsRd2", "0.925")
AMESetParameterValue("effsRd3", "0.925")
AMESetParameterValue("effsRd4", "0.925")
AMESetParameterValue("effsRd5", "0.925")
AMESetParameterValue("effsRd6", "0.925")
AMESetParameterValue("Tslips", "3020.12")
AMESetParameterValue("Tclutch", "780.999")
AMESetParameterValue("initS", "2.628")
AMESetParameterValue("vmaxel", "12")
AMESetParameterValue("socfinal", "100")
AMESetParameterValue("socf", "57")
AMESetParameterValue("qswitchfile", "${circuit_name}_.HOT/KIA_Niro_FHEV/transmission_switch.data")
AMESetParameterValue("J_before", "0.005")
AMESetParameterValue("J_after", "0.003")
AMESetParameterValue("massVeh", "2454")
AMESetParameterValue("c0", "195")
AMESetParameterValue("c1", "2.9988")
AMESetParameterValue("c2", "0.410832")
AMESetParameterValue("f", "0.00587")
AMESetParameterValue("k", "0.000189839248923088")
AMESetParameterValue("wind", "4.5e-06")
AMESetParameterValue("fronttirewidth", "225")
AMESetParameterValue("fronttireheight", "45")
AMESetParameterValue("fronttiredrim", "18")
AMESetParameterValue("reartirewidth", "225")
AMESetParameterValue("reartireheight", "45")
AMESetParameterValue("reartiredrim", "18")
AMESetParameterValue("maxbrakefront", "8094.519")
AMESetParameterValue("slope", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/slope.data")
AMESetParameterValue("altitude", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/altitude.data")
AMESetParameterValue("cycle", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/cycle.data")
AMESetParameterValue("pelecFile", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/pelec.data")
AMESetParameterValue("pmechFile", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/pmech.data")
AMESetParameterValue("dir_eng", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/eng")
AMESetParameterValue("cyl", "1.95")
AMESetParameterValue("LHV_fuel", "44000")
AMESetParameterValue("maxspeed", "4000")
AMESetParameterValue("engInertia", "0.195")
AMESetParameterValue("maxfrct", "1200")
AMESetParameterValue("fuelden", "834.7")
AMESetParameterValue("Teng_init", "22.88")
AMESetParameterValue("ocvfile", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/bat/ocv.data")
AMESetParameterValue("socInit", "15")
AMESetParameterValue("nbpar", "100")
AMESetParameterValue("rfile", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/bat/resistance.data")
AMESetParameterValue("nbser", "100")
AMESetParameterValue("capacell", "0.37802846789001")
AMESetParameterValue("umaxBT", "628.2")
AMESetParameterValue("uminBT", "145.8")
AMESetParameterValue("methU", "2")
AMESetParameterValue("deltaSOC", "2")
AMESetParameterValue("tmaxMotPeak", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/mot/tmax_peak.data")
AMESetParameterValue("tminMotPeak", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/mot/tmin_peak.data")
AMESetParameterValue("motlosses", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/mot/losses.data")
AMESetParameterValue("tmaxMotC", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/mot/tmax_continuous.data")
AMESetParameterValue("tminMotC", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/mot/tmin_continuous.data")
AMESetParameterValue("nforratio", "10")
AMESetParameterValue("ratiosRd1", "5.354")
AMESetParameterValue("ratiosRd2", "3.243")
AMESetParameterValue("ratiosRd3", "2.252")
AMESetParameterValue("ratiosRd4", "1.636")
AMESetParameterValue("ratiosRd5", "1.211")
AMESetParameterValue("ratiosRd6", "1")
AMESetParameterValue("ratiosRd7", "0.865")
AMESetParameterValue("ratiosRd8", "0.717")
AMESetParameterValue("ratiosRd9", "0.601")
AMESetParameterValue("effsRd1", "0.9")
AMESetParameterValue("effsRd2", "0.9")
AMESetParameterValue("effsRd3", "0.9")
AMESetParameterValue("effsRd4", "0.9")
AMESetParameterValue("effsRd5", "0.9")
AMESetParameterValue("effsRd6", "0.9")
AMESetParameterValue("finalratioRd", "2.64")
AMESetParameterValue("Tslips", "11136.319994646")
AMESetParameterValue("Tclutch", "2079.999999")
AMESetParameterValue("initS", "2.407")
AMESetParameterValue("vmaxel", "50")
AMESetParameterValue("socfinal", "17")
AMESetParameterValue("socf", "17")
AMESetParameterValue("qswitchfile", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Diesel/transmission_switch.data")
AMESetParameterValue("tengstart", "wlaunch*(pi/30.0)*engInertia*4+8.8")
AMESetParameterValue("methqswitch", "3")
AMESetParameterValue("J_before", "0.003")
AMESetParameterValue("J_after", "0.005")
AMESetParameterValue("massVeh", "2152")
AMESetParameterValue("c0", "223.9")
AMESetParameterValue("c1", "2.0196")
AMESetParameterValue("c2", "0.4339008")
AMESetParameterValue("fronttirewidth", "245")
AMESetParameterValue("fronttireheight", "40")
AMESetParameterValue("reartirewidth", "245")
AMESetParameterValue("reartireheight", "40")
AMESetParameterValue("maxbrakefront", "7028.432")
AMESetParameterValue("slope", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Gasoline/slope.data")
AMESetParameterValue("altitude", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Gasoline/altitude.data")
AMESetParameterValue("cycle", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Gasoline/cycle.data")
AMESetParameterValue("pelecFile", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Gasoline/pelec.data")
AMESetParameterValue("pmechFile", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Gasoline/pmech.data")
AMESetParameterValue("dir_eng", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Gasoline/eng")
AMESetParameterValue("cyl", "1.991")
AMESetParameterValue("LHV_fuel", "42000")
AMESetParameterValue("maxspeed", "6000")
AMESetParameterValue("engInertia", "0.1991")
AMESetParameterValue("maxfrct", "1050")
AMESetParameterValue("fuelden", "750.3")
AMESetParameterValue("Teng_init", "22.75")
AMESetParameterValue("ocvfile", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Gasoline/bat/ocv.data")
AMESetParameterValue("socInit", "9")
AMESetParameterValue("rfile", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Gasoline/bat/resistance.data")
AMESetParameterValue("deltaSOC", "7")
AMESetParameterValue("tmaxMotPeak", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Gasoline/mot/tmax_peak.data")
AMESetParameterValue("tminMotPeak", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Gasoline/mot/tmin_peak.data")
AMESetParameterValue("motlosses", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Gasoline/mot/losses.data")
AMESetParameterValue("tmaxMotC", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Gasoline/mot/tmax_continuous.data")
AMESetParameterValue("tminMotC", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Gasoline/mot/tmin_continuous.data")
AMESetParameterValue("Tslips", "10333.214646")
AMESetParameterValue("Tclutch", "1929.999")
AMESetParameterValue("initS", "2.55")
AMESetParameterValue("vmaxel", "36")
AMESetParameterValue("socfinal", "16")
AMESetParameterValue("socf", "16")
AMESetParameterValue("qswitchfile", "${circuit_name}_.HOT/Mercedes_C_Class_C300_Gasoline/transmission_switch.data")
AMESetParameterValue("massVeh", "1620")
AMESetParameterValue("c0", "92.9")
AMESetParameterValue("c1", "3.2112")
AMESetParameterValue("c2", "0.42768")
AMESetParameterValue("fronttirewidth", "208")
AMESetParameterValue("fronttireheight", "60")
AMESetParameterValue("fronttiredrim", "16")
AMESetParameterValue("reartirewidth", "208")
AMESetParameterValue("reartireheight", "60")
AMESetParameterValue("reartiredrim", "16")
AMESetParameterValue("maxbrakefront", "5313.6")
AMESetParameterValue("slope", "${circuit_name}_.HOT/KIA_Niro_Gasoline/slope.data")
AMESetParameterValue("altitude", "${circuit_name}_.HOT/KIA_Niro_Gasoline/altitude.data")
AMESetParameterValue("cycle", "${circuit_name}_.HOT/KIA_Niro_Gasoline/cycle.data")
AMESetParameterValue("pelecFile", "${circuit_name}_.HOT/KIA_Niro_Gasoline/pelec.data")
AMESetParameterValue("pmechFile", "${circuit_name}_.HOT/KIA_Niro_Gasoline/pmech.data")
AMESetParameterValue("dir_eng", "${circuit_name}_.HOT/KIA_Niro_Gasoline/eng")
AMESetParameterValue("cyl", "1.58")
AMESetParameterValue("engInertia", "0.1")
AMESetParameterValue("maxfrct", "441")
AMESetParameterValue("Teng_init", "24")
AMESetParameterValue("ocvfile", "${circuit_name}_.HOT/KIA_Niro_Gasoline/bat/ocv.data")
AMESetParameterValue("socInit", "17")
AMESetParameterValue("nbpar", "96")
AMESetParameterValue("rfile", "${circuit_name}_.HOT/KIA_Niro_Gasoline/bat/resistance.data")
AMESetParameterValue("nbser", "110")
AMESetParameterValue("capacell", "0.257070202249241")
AMESetParameterValue("umaxBT", "564.35515356")
AMESetParameterValue("uminBT", "147.76432561")
AMESetParameterValue("methU", "1")
AMESetParameterValue("deltaSOC", "-4")
AMESetParameterValue("tmaxMotPeak", "${circuit_name}_.HOT/KIA_Niro_Gasoline/mot/tmax_peak.data")
AMESetParameterValue("tminMotPeak", "${circuit_name}_.HOT/KIA_Niro_Gasoline/mot/tmin_peak.data")
AMESetParameterValue("motlosses", "${circuit_name}_.HOT/KIA_Niro_Gasoline/mot/losses.data")
AMESetParameterValue("tmaxMotC", "${circuit_name}_.HOT/KIA_Niro_Gasoline/mot/tmax_continuous.data")
AMESetParameterValue("tminMotC", "${circuit_name}_.HOT/KIA_Niro_Gasoline/mot/tmin_continuous.data")
AMESetParameterValue("nforratio", "7")
AMESetParameterValue("ratiosRd1", "3.867")
AMESetParameterValue("ratiosRd2", "2.217")
AMESetParameterValue("ratiosRd3", "1.371")
AMESetParameterValue("ratiosRd4", "0.93")
AMESetParameterValue("ratiosRd5", "0.695")
AMESetParameterValue("ratiosRd6", "0.585")
AMESetParameterValue("ratiosRd7", "0")
AMESetParameterValue("ratiosRd8", "0")
AMESetParameterValue("ratiosRd9", "0")
AMESetParameterValue("finalratioRd", "4.438")
AMESetParameterValue("Tslips", "3020.13")
AMESetParameterValue("Tclutch", "781")
AMESetParameterValue("initS", "2.459")
AMESetParameterValue("vmaxel", "33.333")
AMESetParameterValue("socfinal", "13")
AMESetParameterValue("socf", "13")
AMESetParameterValue("qswitchfile", "${circuit_name}_.HOT/KIA_Niro_Gasoline/transmission_switch.data")
AMESetParameterValue("tengstart", "wlaunch*(pi/30.0)*engInertia*4+17.6")
AMESetParameterValue("methqswitch", "2")
AMESetParameterValue("massVeh", "1663")
AMESetParameterValue("c0", "129")
AMESetParameterValue("c1", "3.834")
AMESetParameterValue("c2", "0.402408")
AMESetParameterValue("f", "0.01")
AMESetParameterValue("k", "0")
AMESetParameterValue("wind", "0")
AMESetParameterValue("maxbrakefront", "5454.64")
AMESetParameterValue("slope", "${circuit_name}_.HOT/KIA_Niro_FHEV/slope.data")
AMESetParameterValue("altitude", "${circuit_name}_.HOT/KIA_Niro_FHEV/altitude.data")
AMESetParameterValue("cycle", "${circuit_name}_.HOT/KIA_Niro_FHEV/cycle.data")
AMESetParameterValue("pelecFile", "${circuit_name}_.HOT/KIA_Niro_FHEV/pelec.data")
AMESetParameterValue("pmechFile", "${circuit_name}_.HOT/KIA_Niro_FHEV/pmech.data")
AMESetParameterValue("dir_eng", "${circuit_name}_.HOT/KIA_Niro_FHEV/eng")
AMESetParameterValue("Teng_init", "90")
AMESetParameterValue("ocvfile", "${circuit_name}_.HOT/KIA_Niro_FHEV/bat/ocv.data")
AMESetParameterValue("socInit", "50")
AMESetParameterValue("nbpar", "64")
AMESetParameterValue("rfile", "${circuit_name}_.HOT/KIA_Niro_FHEV/bat/resistance.data")
AMESetParameterValue("nbser", "74")
AMESetParameterValue("capacell", "0.101495165729582")
AMESetParameterValue("umaxBT", "379.657103304")
AMESetParameterValue("uminBT", "99.405091774")
AMESetParameterValue("deltaSOC", "7")
AMESetParameterValue("tmaxMotPeak", "${circuit_name}_.HOT/KIA_Niro_FHEV/mot/tmax_peak.data")
AMESetParameterValue("tminMotPeak", "${circuit_name}_.HOT/KIA_Niro_FHEV/mot/tmin_peak.data")
AMESetParameterValue("motlosses", "${circuit_name}_.HOT/KIA_Niro_FHEV/mot/losses.data")
AMESetParameterValue("tmaxMotC", "${circuit_name}_.HOT/KIA_Niro_FHEV/mot/tmax_continuous.data")
AMESetParameterValue("tminMotC", "${circuit_name}_.HOT/KIA_Niro_FHEV/mot/tmin_continuous.data")
AMESetParameterValue("ratiosRd6", "0.558")
AMESetParameterValue("effsRd1", "0.925")
AMESetParameterValue("effsRd2", "0.925")
AMESetParameterValue("effsRd3", "0.925")
AMESetParameterValue("effsRd4", "0.925")
AMESetParameterValue("effsRd5", "0.925")
AMESetParameterValue("effsRd6", "0.925")
AMESetParameterValue("Tslips", "3020.12")
AMESetParameterValue("Tclutch", "780.999")
AMESetParameterValue("initS", "2.628")
AMESetParameterValue("vmaxel", "12")
AMESetParameterValue("socfinal", "100")
AMESetParameterValue("socf", "57")
AMESetParameterValue("qswitchfile", "${circuit_name}_.HOT/KIA_Niro_FHEV/transmission_switch.data")
AMESetParameterValue("J_before", "0.005")
AMESetParameterValue("J_after", "0.003")
AMESetParameterValue("massVeh", "1620")
AMESetParameterValue("c0", "92.9")
AMESetParameterValue("c1", "3.2112")
AMESetParameterValue("c2", "0.42768")
AMESetParameterValue("f", "0.00587")
AMESetParameterValue("k", "0.000189839248923088")
AMESetParameterValue("wind", "4.5e-06")
AMESetParameterValue("maxbrakefront", "5313.6")
AMESetParameterValue("slope", "${circuit_name}_.HOT/KIA_Niro_Gasoline/slope.data")
AMESetParameterValue("altitude", "${circuit_name}_.HOT/KIA_Niro_Gasoline/altitude.data")
AMESetParameterValue("cycle", "${circuit_name}_.HOT/KIA_Niro_Gasoline/cycle.data")
AMESetParameterValue("pelecFile", "${circuit_name}_.HOT/KIA_Niro_Gasoline/pelec.data")
AMESetParameterValue("pmechFile", "${circuit_name}_.HOT/KIA_Niro_Gasoline/pmech.data")
AMESetParameterValue("dir_eng", "${circuit_name}_.HOT/KIA_Niro_Gasoline/eng")
AMESetParameterValue("Teng_init", "24")
AMESetParameterValue("ocvfile", "${circuit_name}_.HOT/KIA_Niro_Gasoline/bat/ocv.data")
AMESetParameterValue("socInit", "17")
AMESetParameterValue("nbpar", "96")
AMESetParameterValue("rfile", "${circuit_name}_.HOT/KIA_Niro_Gasoline/bat/resistance.data")
AMESetParameterValue("nbser", "110")
AMESetParameterValue("capacell", "0.257070202249241")
AMESetParameterValue("umaxBT", "564.35515356")
AMESetParameterValue("uminBT", "147.76432561")
AMESetParameterValue("deltaSOC", "-4")
AMESetParameterValue("tmaxMotPeak", "${circuit_name}_.HOT/KIA_Niro_Gasoline/mot/tmax_peak.data")
AMESetParameterValue("tminMotPeak", "${circuit_name}_.HOT/KIA_Niro_Gasoline/mot/tmin_peak.data")
AMESetParameterValue("motlosses", "${circuit_name}_.HOT/KIA_Niro_Gasoline/mot/losses.data")
AMESetParameterValue("tmaxMotC", "${circuit_name}_.HOT/KIA_Niro_Gasoline/mot/tmax_continuous.data")
AMESetParameterValue("tminMotC", "${circuit_name}_.HOT/KIA_Niro_Gasoline/mot/tmin_continuous.data")
AMESetParameterValue("ratiosRd6", "0.585")
AMESetParameterValue("effsRd1", "0.9")
AMESetParameterValue("effsRd2", "0.9")
AMESetParameterValue("effsRd3", "0.9")
AMESetParameterValue("effsRd4", "0.9")
AMESetParameterValue("effsRd5", "0.9")
AMESetParameterValue("effsRd6", "0.9")
AMESetParameterValue("Tslips", "3020.13")
AMESetParameterValue("Tclutch", "781")
AMESetParameterValue("initS", "2.459")
AMESetParameterValue("vmaxel", "33.333")
AMESetParameterValue("socfinal", "13")
AMESetParameterValue("socf", "13")
AMESetParameterValue("qswitchfile", "${circuit_name}_.HOT/KIA_Niro_Gasoline/transmission_switch.data")
AMESetParameterValue("J_before", "0.003")
AMESetParameterValue("J_after", "0.005")
ApplyUpdateAssistant(SC('HybridElectricVehicle_e840e9f60e3c42f2923f26abeca5af17'))
