<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE SUB>
<SUB AME_VERSION="2604" DOC_VERSION="6" HOTFIX="0" MAJ="20261" UPDATE="0">
 <Supercomponent catname="CnstSink1" scSubName="RUNSTATADD">
  <PortsMap/>
  <Circuit ameApplication="AMESim" highestId="36">
   <Comps>
    <Comp alias="constant" circuitScopeId="1" depth="201" displayName="constant" geometry="1" iconDescription="constant signal source" labelVisible="0" libraryId="sig.constant" name="constant" scaleX="1.000000" scaleY="1.000000" type="0">
     <Pos x="67" y="96"/>
     <LabelPos configured="0" direction="0" x="0" y="0"/>
     <CirCompIcon cirIconIdentity="1" cirPortGraphics="IDxQT1JUUz4KICA8UE9SVCBmYWNlPSIzIiB0eXBlPSJzaWduYWwiIHg9IjQwIiB5PSIxNSI+CiAgIDxQT1JUX0JJVE1BUD4kQU1FL2xpYnBvcnRzL0ljb25zL3NpZ25hbDFweC5zdmc8L1BPUlRfQklUTUFQPgogIDwvUE9SVD4KIDwvUE9SVFM+Cg==" cirPortHidden="0">
      <IconMap data="H4sIAAAAAAACCo1SwY7bIBC95ytGswe30gYbO6vaUchqe+iphx7ac+Q62EHBYAFrO/36Do7TXnooQprh8XgzDzi8zr2GUTqvrBEJZ1kC0jT2rEwnkh/fv2zL5PW4OfixA2IaL/ASwrBP02ma2FQw67o0z7IsJQbeKftZK3P9F5FXVZUuu/inJnKWI/ysvfzmbKu0FBiUuSGos8CvapRa2xMnaYHZMCPc1jipc7gI3C2Li1TdJQjMq7galZw+23gAMthlkFcIluq12k4CfeOs1kuvez/UDRUcnPTSjRLJaXfcAMChUa7REqghLfCpXQaCD85e6cBTtowHsO1VkE4rCuSH4IaK8x17oez2yFxMML3LBzkHCK42vrWuF9jXwan5A4fYMgdOs2R5seMfEVprwrate6VJK3lzqtbJinr1S0ZZcn28HtKoShbSLvpYLrB59+HET151ptZ4r033/zBmrJH/72rmAouCnoA/PM15fAFC8hVZ7Q1W3zprYLDKBPozefnMOXuBImf8ORIhIp/WWLISioJVf3cylgNEsbuX+LmOm9+vXzT5rAIAAA==" format="svgz/base64"/>
     </CirCompIcon>
     <Ports>
      <Port connect="1" decorationOrientation="0" decorationVisible="0" face="3" name="" type="signal">
       <Pos x="40" y="15"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="1" port="0"/>
       </Connects>
      </Port>
     </Ports>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="0" codeGenVersion="2.0" dir="$AME/libsig/submodels" discontinuity="1" hasTerminate="1" idMax="29" idsReset="0" label="constant signal" name="CONS00" needsUpdateCheck="1" outputType="1" type="0" unit="1">
      <RealParams>
       <Params>
        <Param defValue="1" historyVariable="k0GEN" maxValue="1e+30" minValue="-1e+30" subId="3" title="constant value" tunable="True" units="null" value="1" varName="k" visibility="True"/>
       </Params>
      </RealParams>
      <ParamsGroups>
       <Group circuitScopeId="4" editable="0" editableTitle="1" groupHeadIcon="" name="ROOTGROUP" origTitle="ROOTGROUP" subId="29">
        <Elements>
         <Element display="0" varName="k"/>
         <Element display="1" varName="out"/>
        </Elements>
       </Group>
      </ParamsGroups>
      <IntVars>
       <Vars>
        <Var defValue="0" dimension="1" maxValue="1e+30" minValue="-1e+30" saveValue="1" subId="28" title="constant value - Linked variable" type="10" units="null" value="0" varName="k0GEN" visibility="False">
         <LaData>
          <Data laStatus="0"/>
         </LaData>
        </Var>
       </Vars>
      </IntVars>
      <ExtVars>
       <Port tag="signal">
        <Vars>
         <Var dimension="1" io="2" saveValue="1" subId="24" title="output" type="0" units="null" varName="out" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
      </ExtVars>
     </Submodel>
    </Comp>
    <Comp alias="signalsink" circuitScopeId="2" depth="202" displayName="signalsink" geometry="1" iconDescription="general signal sink" labelVisible="0" libraryId="sig.signalsink" name="signalsink" scaleX="1.000000" scaleY="1.000000" type="0">
     <Pos x="107" y="106"/>
     <LabelPos configured="0" direction="0" x="0" y="0"/>
     <CirCompIcon cirIconIdentity="1" cirPortGraphics="IDxQT1JUUz4KICA8UE9SVCBmYWNlPSIyIiB0eXBlPSJzaWduYWwiIHg9IjEiIHk9IjUiPgogICA8UE9SVF9CSVRNQVA+JEFNRS9saWJwb3J0cy9JY29ucy9zaWduYWwxcHguc3ZnPC9QT1JUX0JJVE1BUD4KICA8L1BPUlQ+CiA8L1BPUlRTPgo=" cirPortHidden="0">
      <IconMap data="H4sIAAAAAAACCp1RPW/DIBDd+ytO18FLaoz7kTgKidShU4cO7RylDsEoBCygxv73PTtp1KFTGbgPHu/d0602/clAJ33QzoqM50UG0tZur60S2cf7y90i26xvVqFTQEgbBDYxtkvGUkp5us+dV6wsioIRAs+QZW+0Pf4F5FVVsekVr5rI8xLhcxfkm3cHbaTAqO2AoPcCX3UnjXFbTtQCi7ZHGC4x6X1sBFZj3kitmngpOi3TsxvhUEAFFYIjrYNxSWCovTNmmnMZ2l1NYq2XQfpOIrn0so6j0PxKX/4iR0YQNc1Vf4W45dugld0Z+gkAK7IlgQwYgdZZiRCid0dSuC2m89O4O+kovdEUyDy1e06zkjEKD/kj1aXApzEZynOHnQVaZ4Z/i7RO20jbK2cc5jNihXK2AJg8MTVetMD1NyXBqRUPAgAA" format="svgz/base64"/>
     </CirCompIcon>
     <Ports>
      <Port connect="1" decorationOrientation="0" decorationVisible="0" face="2" name="" type="signal">
       <Pos x="1" y="5"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="0" port="0"/>
       </Connects>
      </Port>
     </Ports>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="0" codeGenVersion="2.0" dir="$AME/libsig/submodels" hasNoCalc="1" hasTerminate="1" idMax="2" idsReset="0" label="plug for signal port" name="SSINK" needsUpdateCheck="1" outputType="1" type="0" unit="1">
      <ParamsGroups>
       <Group circuitScopeId="6" editable="0" editableTitle="1" groupHeadIcon="" name="ROOTGROUP" origTitle="ROOTGROUP" subId="2">
        <Elements>
         <Element display="1" varName="sink"/>
        </Elements>
       </Group>
      </ParamsGroups>
      <ExtVars>
       <Port tag="signal">
        <Vars>
         <Var dimension="1" io="1" saveValue="1" subId="1" title="signal input" type="0" units="null" varName="sink" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
      </ExtVars>
     </Submodel>
    </Comp>
    <Comp alias="component_1" circuitScopeId="3" depth="203" displayName="SCStepSnk1" geometry="1" hasDefaultIcon="1" iconDescription="description for supercomponent" isTextShown="1" labelVisible="0" libraryId="StepSnk1.SCStepSnk1" name="SCStepSnk1" scaleX="1.000000" scaleY="1.000000" text="SCStepSnk1" type="0">
     <Pos x="161" y="67"/>
     <LabelPos configured="0" direction="0" x="0" y="0"/>
     <CirCompIcon cirIconIdentity="1" cirPortGraphics="IDxQT1JUUy8+Cg==" cirPortHidden="0">
      <IconMap data="H4sIAAAAAAACCs1TTY/bIBC991cgcmnV2mBvoiaW8UpVtVKv7VY9s4AdGhssIHHy7zvQxJuNtu21SMYzb958MVDfH4ceHZTz2hqGi5xipIywUpuO4e+PD9kaIx+4kby3RjFsLL5van/oEDgaX0nB8DaEsSJk3Ls+t64jUhDVq0GZ4EmRFwSfueKZK5ziQR+UsMNgjU9uxi8uTCfbmTpNUz7dJUax2WwILUlZZsDI/MkEfsyu/KCu1/xKSikB24V27LXZ/TFBsp6pf4920Gr6ZI8MU0TR+g59XOLrsyww0pJhoK5xUw8qcMkDT9hFWYEBWqm+fn5oaiGqH9btUAT4k90HhhHYpaha6wYeGj3wTsXU76G4mjwbIiecRpVcnfJ274R6dTBSDDoyybeg+/5LDIjJb38degUiOZcB0lwZudTb1B0KjhsfE0MbPDh9fAvXBk5g3pJalPP+7h9N/h89jrY/weQVasGJ4UWbFk5qZkcuIGZ6IfBERqvhcjO8zFf0A4UNrdY34nITZXorRmn2ik/L2R10saBpXYBMcr/lznHI+AKzbesVHBnNr8ixasFHhp/2IbxAf0KdMCUdlJvxpPUafgyX12Fuejyjk5Zhe8biyXXwwXSaN78AUoubQDsEAAA=" format="svgz/base64"/>
     </CirCompIcon>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="1" codeGenVersion="1.0" dir="D:/Test_Libraries/StepSnk1/submodels" name="SMSTEPSNK1" needsUpdateCheck="1" outputType="0" type="1" unit="0">
      <ExposedOrder>
       <Params>
        <Groups/>
       </Params>
       <Vars>
        <Groups/>
       </Vars>
      </ExposedOrder>
     </Submodel>
     <Supercomponent catname="StepSnk1" scDir="D:/Test_Libraries/StepSnk1/submodels">
      <PortsMap/>
      <Circuit ameApplication="AMESim" highestId="36">
       <Comps>
        <Comp alias="step" circuitScopeId="1" depth="201" displayName="step" geometry="1" iconDescription="step signal source" labelVisible="0" libraryId="sig.step" name="step" scaleX="1.000000" scaleY="1.000000" type="0">
         <Pos x="67" y="67"/>
         <LabelPos configured="0" direction="0" x="0" y="0"/>
         <CirCompIcon cirIconIdentity="1" cirPortGraphics="IDxQT1JUUz4KICA8UE9SVCBmYWNlPSIzIiB0eXBlPSJzaWduYWwiIHg9IjQwIiB5PSIxNSI+CiAgIDxQT1JUX0JJVE1BUD4kQU1FL2xpYnBvcnRzL0ljb25zL3NpZ25hbDFweC5zdmc8L1BPUlRfQklUTUFQPgogIDwvUE9SVD4KIDwvUE9SVFM+Cg==" cirPortHidden="0">
          <IconMap data="H4sIAAAAAAACCp1SsXLjIBDt/RU7m8KNgwDZE8ljnJkrrroiRa72ODKWmRDQAJHkv79FtnMurrgJzS7LY997LJvn8cNCr0M03qm5YHwO2jX+YFyr5r9ffz5W8+ftbBP7FgjposJTSt26KIZhYEPJfGgLyTkvCIEXyHq0xr3/Cyjqui6mU/ziRMEkwts+6pfgj8Zqhcm4M4I5KPxlem2t3wlqrZB3I8L5GgdzSCeFy2lz0qY9JYWyzrve6OGHzxeAw5KDrBE88R2tHxTGJnhrJ63r2O0bIuyCjjr0Gslpu50BwKYxobEaSJBV+HCcFkJMwb/ThQc+rVvh8cMkHayhQH6o3BC5WLIVZedbFnKCxaV95+2Z3uFG4LzT/9+988YlmsRqISq2AsHZfZYTWU4BMt2maLOt6T2bz5h2YhdN6/YWL1K+LWMUCsuSJiJuFkeZB0IVea3cuW29+xIuq4UQpK+UTCwyEHLl6RorVkFZsvrvCWfy3kv+a9vZHz/V+s+7AgAA" format="svgz/base64"/>
         </CirCompIcon>
         <Ports>
          <Port connect="1" decorationOrientation="0" decorationVisible="0" face="3" name="" type="signal">
           <Pos x="40" y="15"/>
           <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
           <Connects>
            <Connect num="4" port="0"/>
           </Connects>
          </Port>
         </Ports>
         <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="0" codeGenVersion="2.0" dir="$AME/libsig/submodels" discontinuity="1" hasTerminate="1" iStoresNumber="1" idMax="38" idsReset="0" label="step function" name="STEP0" needsUpdateCheck="1" outputType="1" rStoresNumber="6" timeRequired="1" type="0" unit="0">
          <RealParams>
           <Params>
            <Param defValue="0" historyVariable="out00GEN" maxValue="1e+30" minValue="-1e+30" paramImage="${library_node}/embedded_files/images/STEP0_out0.png" subId="2" title="value before step" tunable="True" units="null" value="0" varName="out0" visibility="True"/>
            <Param defValue="1" historyVariable="out10GEN" maxValue="1e+30" minValue="-1e+30" paramImage="${library_node}/embedded_files/images/STEP0_out1.png" subId="3" title="value after step" tunable="True" units="null" value="1" varName="out1" visibility="True"/>
            <Param defValue="0" historyVariable="t00GEN" maxValue="1e+30" minValue="-1e+30" paramImage="${library_node}/embedded_files/images/STEP0_t0.png" subId="4" title="step time" tunable="True" units="s" value="0" varName="t0" visibility="True"/>
            <Param defValue="0.1" maxValue="1e+30" minValue="0" paramImage="${library_node}/embedded_files/images/SQW00_transition.png" subId="7" title="transition duration" units="s" value="0.1" varName="td" visibility="transitionType>1"/>
           </Params>
          </RealParams>
          <IntParams>
           <Params>
            <Param defValue="1" maxValue="3" minValue="1" paramImage="${library_node}/embedded_files/images/SQW00_transition.png" subId="5" title="transition type" value="1" varName="transitionType" visibility="True">
             <Enums>
              <Enum string="discontinuous"/>
              <Enum string="polynomial (order 3)"/>
              <Enum string="polynomial (order 5)"/>
             </Enums>
            </Param>
           </Params>
          </IntParams>
          <ParamsGroups>
           <Group circuitScopeId="16" editable="0" editableTitle="1" groupHeadIcon="" name="ROOTGROUP" origTitle="ROOTGROUP" subId="38">
            <Elements>
             <Element display="0" varName="transitionType"/>
             <Element display="0" varName="out0"/>
             <Element display="0" varName="out1"/>
             <Element display="0" varName="t0"/>
             <Element display="0" varName="td"/>
             <Element display="1" varName="out"/>
            </Elements>
           </Group>
          </ParamsGroups>
          <IntVars>
           <Vars>
            <Var defValue="0" dimension="1" maxValue="1e+30" minValue="-1e+30" saveValue="1" subId="35" title="value before step - Linked variable" type="10" units="null" value="0" varName="out00GEN" visibility="False">
             <LaData>
              <Data laStatus="0"/>
             </LaData>
            </Var>
            <Var defValue="0" dimension="1" maxValue="1e+30" minValue="-1e+30" saveValue="1" subId="36" title="value after step - Linked variable" type="10" units="null" value="0" varName="out10GEN" visibility="False">
             <LaData>
              <Data laStatus="0"/>
             </LaData>
            </Var>
            <Var defValue="0" dimension="1" maxValue="1e+30" minValue="-1e+30" saveValue="1" subId="37" title="step time - Linked variable" type="10" units="s" value="0" varName="t00GEN" visibility="False">
             <LaData>
              <Data laStatus="0"/>
             </LaData>
            </Var>
           </Vars>
          </IntVars>
          <ExtVars>
           <Port tag="signal">
            <Vars>
             <Var dimension="1" io="2" saveValue="1" subId="1" title="step output" type="0" units="null" varName="out" visibility="True">
              <LaData>
               <Data laStatus="0"/>
              </LaData>
             </Var>
            </Vars>
           </Port>
          </ExtVars>
         </Submodel>
        </Comp>
        <Comp alias="signalsink_1" circuitScopeId="2" depth="202" displayName="signalsink" geometry="1" iconDescription="general signal sink" labelVisible="0" libraryId="sig.signalsink" name="signalsink" scaleX="1.000000" scaleY="1.000000" type="0">
         <Pos x="107" y="77"/>
         <LabelPos configured="0" direction="0" x="0" y="0"/>
         <CirCompIcon cirIconIdentity="1" cirPortGraphics="IDxQT1JUUz4KICA8UE9SVCBmYWNlPSIyIiB0eXBlPSJzaWduYWwiIHg9IjEiIHk9IjUiPgogICA8UE9SVF9CSVRNQVA+JEFNRS9saWJwb3J0cy9JY29ucy9zaWduYWwxcHguc3ZnPC9QT1JUX0JJVE1BUD4KICA8L1BPUlQ+CiA8L1BPUlRTPgo=" cirPortHidden="0">
          <IconMap data="H4sIAAAAAAACCp1RPW/DIBDd+ytO18FLaoz7kTgKidShU4cO7RylDsEoBCygxv73PTtp1KFTGbgPHu/d0602/clAJ33QzoqM50UG0tZur60S2cf7y90i26xvVqFTQEgbBDYxtkvGUkp5us+dV6wsioIRAs+QZW+0Pf4F5FVVsekVr5rI8xLhcxfkm3cHbaTAqO2AoPcCX3UnjXFbTtQCi7ZHGC4x6X1sBFZj3kitmngpOi3TsxvhUEAFFYIjrYNxSWCovTNmmnMZ2l1NYq2XQfpOIrn0so6j0PxKX/4iR0YQNc1Vf4W45dugld0Z+gkAK7IlgQwYgdZZiRCid0dSuC2m89O4O+kovdEUyDy1e06zkjEKD/kj1aXApzEZynOHnQVaZ4Z/i7RO20jbK2cc5jNihXK2AJg8MTVetMD1NyXBqRUPAgAA" format="svgz/base64"/>
         </CirCompIcon>
         <Ports>
          <Port connect="1" decorationOrientation="0" decorationVisible="0" face="2" name="" type="signal">
           <Pos x="1" y="5"/>
           <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
           <Connects>
            <Connect num="3" port="0"/>
           </Connects>
          </Port>
         </Ports>
         <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="0" codeGenVersion="2.0" dir="$AME/libsig/submodels" hasNoCalc="1" hasTerminate="1" idMax="2" idsReset="0" label="plug for signal port" name="SSINK" needsUpdateCheck="1" outputType="1" type="0" unit="1">
          <ParamsGroups>
           <Group circuitScopeId="18" editable="0" editableTitle="1" groupHeadIcon="" name="ROOTGROUP" origTitle="ROOTGROUP" subId="2">
            <Elements>
             <Element display="1" varName="sink"/>
            </Elements>
           </Group>
          </ParamsGroups>
          <ExtVars>
           <Port tag="signal">
            <Vars>
             <Var dimension="1" io="1" saveValue="1" subId="1" title="signal input" type="0" units="null" varName="sink" visibility="True">
              <LaData>
               <Data laStatus="0"/>
              </LaData>
             </Var>
            </Vars>
           </Port>
          </ExtVars>
         </Submodel>
        </Comp>
       </Comps>
       <animationProperties loop="0" speed="1"/>
       <globalParams/>
      </Circuit>
     </Supercomponent>
    </Comp>
    <Comp alias="runstats" circuitScopeId="1" depth="204" displayName="runstats" geometry="1" iconDescription="statistics of current run" labelVisible="0" libraryId="simu.runstats" name="runstats" scaleX="1.000000" scaleY="1.000000" type="0">
     <Pos x="323" y="82"/>
     <LabelPos configured="0" direction="0" x="0" y="0"/>
     <CirCompIcon cirIconIdentity="1" cirPortGraphics="IDxQT1JUUy8+Cg==" cirPortHidden="0">
      <IconMap data="H4sIAAAAAAACCo1SPU/DMBDd+ytO1yEw1PmgpU0VB8HAhBCCMqPQOsmpjl3ZVhL49Thp+RgYeoNPfr577/ns7KZvJLTCWNKKBzGLAhBqq3ekKh68bu5nq+Amn2S2rcBXKrsuGmGp4diqHZONZdQUFSnBjjgeqzjWzh3WYdh1HeuumDZVmERRFHqeU8m6l6T2/xXGaZqG4yn+OMOYJQjvhRVPRpckBUdH6gOBdhwfqBVS6rfYU3OMDj3Cxyl3tHM1x/ly2NSCqtpxTNJh15Lo7vTQABHMl5CkCNrrlVJ3HO3WaClHr2t7KLZe8GCEFaYV6OdR5RMAyIzYulGTLY6aQ/b2JMdpOQaCdUbvffs0GuMbmJ2sxT9AQ04YST55NPr1fv3H+QrDo7ITvQNnCmVLbfxzNIUz1F/EMNwmhjhhi3G59H60crOyaEh6h8GtoUIGJ9TSpxjE/Dzy59fHLBxozxJYef5kfj77y+Z28/LNn4XVsPjPkE++ACmHSEeCAgAA" format="svgz/base64"/>
     </CirCompIcon>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="0" codeGenVersion="2.0" dir="$AME/libame/submodels" hasTerminate="1" idMax="20" label="statistics of current run" name="RSTAT" outputType="1" rStoresNumber="27" type="0" unit="0">
      <ParamsGroups>
       <Group circuitScopeId="36" editable="0" editableTitle="1" groupHeadIcon="" name="ROOTGROUP" origTitle="ROOTGROUP" subId="20">
        <Elements>
         <Element display="1" varName="cpu"/>
         <Element display="1" varName="wallTime"/>
         <Element display="1" varName="step"/>
         <Element display="1" varName="minh"/>
         <Element display="1" varName="maxh"/>
         <Element display="1" varName="minhprint"/>
         <Element display="1" varName="maxhprint"/>
         <Element display="1" varName="njacs"/>
         <Element display="1" varName="nfes"/>
         <Element display="1" varName="ndisc"/>
         <Element display="1" varName="nsteps"/>
         <Element display="1" varName="fetime"/>
         <Element display="1" varName="stime"/>
         <Element display="1" varName="nadams"/>
         <Element display="1" varName="nbdf"/>
         <Element display="1" varName="adams_1"/>
         <Element display="1" varName="bdf_1"/>
        </Elements>
       </Group>
      </ParamsGroups>
      <IntVars>
       <Vars>
        <Var dimension="1" saveValue="1" subId="1" title="CPU time" type="0" units="s" varName="cpu" visibility="True">
         <LaData>
          <Data laStatus="0"/>
         </LaData>
        </Var>
        <Var dimension="1" saveValue="1" subId="15" title="elapsed time" type="0" units="s" varName="wallTime" visibility="True">
         <LaData>
          <Data laStatus="0"/>
         </LaData>
        </Var>
        <Var dimension="1" saveValue="1" subId="2" title="log 10 current integration step" type="0" units="s" varName="step" visibility="True">
         <LaData>
          <Data laStatus="0"/>
         </LaData>
        </Var>
        <Var dimension="1" saveValue="1" subId="3" title="log 10 minimum integration step" type="0" units="s" varName="minh" visibility="True">
         <LaData>
          <Data laStatus="0"/>
         </LaData>
        </Var>
        <Var dimension="1" saveValue="1" subId="4" title="log 10 maximum integration step" type="0" units="s" varName="maxh" visibility="True">
         <LaData>
          <Data laStatus="0"/>
         </LaData>
        </Var>
        <Var dimension="1" saveValue="1" subId="18" title="log 10 minimum integration step since last print" type="0" units="s" varName="minhprint" visibility="True">
         <LaData>
          <Data laStatus="0"/>
         </LaData>
        </Var>
        <Var dimension="1" saveValue="1" subId="19" title="log 10 maximum integration step since last print" type="0" units="s" varName="maxhprint" visibility="True">
         <LaData>
          <Data laStatus="0"/>
         </LaData>
        </Var>
        <Var dimension="1" saveValue="1" subId="6" title="current total number of Jacobians" type="0" units="null" varName="njacs" visibility="True">
         <LaData>
          <Data laStatus="0"/>
         </LaData>
        </Var>
        <Var dimension="1" saveValue="1" subId="5" title="current total number of function evaluations" type="0" units="null" varName="nfes" visibility="True">
         <LaData>
          <Data laStatus="0"/>
         </LaData>
        </Var>
        <Var dimension="1" saveValue="1" subId="7" title="current total number of discontinuities processed" type="0" units="null" varName="ndisc" visibility="True">
         <LaData>
          <Data laStatus="0"/>
         </LaData>
        </Var>
        <Var dimension="1" saveValue="1" subId="8" title="current total number of steps" type="0" units="null" varName="nsteps" visibility="True">
         <LaData>
          <Data laStatus="0"/>
         </LaData>
        </Var>
        <Var dimension="1" saveValue="1" subId="9" title="mean CPU time per function evaluation" type="0" units="s" varName="fetime" visibility="True">
         <LaData>
          <Data laStatus="0"/>
         </LaData>
        </Var>
        <Var dimension="1" saveValue="1" subId="10" title="mean CPU time per step" type="0" units="s" varName="stime" visibility="True">
         <LaData>
          <Data laStatus="0"/>
         </LaData>
        </Var>
        <Var dimension="1" saveValue="1" subId="11" title="total number of Adams steps" type="0" units="null" varName="nadams" visibility="True">
         <LaData>
          <Data laStatus="0"/>
         </LaData>
        </Var>
        <Var dimension="1" saveValue="1" subId="12" title="total number of bdf steps" type="0" units="null" varName="nbdf" visibility="True">
         <LaData>
          <Data laStatus="0"/>
         </LaData>
        </Var>
        <Var dimension="12" saveValue="1" subId="13" title="number of Adams steps of order" type="0" units="null" varName="adams" visibility="True">
         <TitleList>
          <Title>number of Adams steps of order</Title>
          <Title>number of Adams steps of order</Title>
          <Title>number of Adams steps of order</Title>
          <Title>number of Adams steps of order</Title>
          <Title>number of Adams steps of order</Title>
          <Title>number of Adams steps of order</Title>
          <Title>number of Adams steps of order</Title>
          <Title>number of Adams steps of order</Title>
          <Title>number of Adams steps of order</Title>
          <Title>number of Adams steps of order</Title>
          <Title>number of Adams steps of order</Title>
          <Title>number of Adams steps of order</Title>
         </TitleList>
         <LaData>
          <Data laStatus="0"/>
          <Data laStatus="6"/>
          <Data laStatus="6"/>
          <Data laStatus="6"/>
          <Data laStatus="6"/>
          <Data laStatus="6"/>
          <Data laStatus="6"/>
          <Data laStatus="6"/>
          <Data laStatus="6"/>
          <Data laStatus="6"/>
          <Data laStatus="6"/>
          <Data laStatus="6"/>
         </LaData>
        </Var>
        <Var dimension="5" saveValue="1" subId="14" title="number of BDF steps of order" type="0" units="null" varName="bdf" visibility="True">
         <TitleList>
          <Title>number of BDF steps of order</Title>
          <Title>number of BDF steps of order</Title>
          <Title>number of BDF steps of order</Title>
          <Title>number of BDF steps of order</Title>
          <Title>number of BDF steps of order</Title>
         </TitleList>
         <LaData>
          <Data laStatus="0"/>
          <Data laStatus="6"/>
          <Data laStatus="6"/>
          <Data laStatus="6"/>
          <Data laStatus="6"/>
         </LaData>
        </Var>
       </Vars>
      </IntVars>
     </Submodel>
    </Comp>
   </Comps>
   <animationProperties loop="0" speed="1"/>
   <globalParams/>
  </Circuit>
 </Supercomponent>
</SUB>
