<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE SUB>
<SUB AME_VERSION="2604" DOC_VERSION="6" HOTFIX="0" MAJ="20261" UPDATE="0">
 <Supercomponent catname="CnstSink1" scSubName="SMCNSTSINK23">
  <PortsMap/>
  <Circuit ameApplication="AMESim" highestId="51">
   <Comps>
    <Comp alias="constant" circuitScopeId="1" depth="201" displayName="constant" geometry="1" iconDescription="constant signal source" labelVisible="0" libraryId="sig.constant" name="constant" scaleX="1.000000" scaleY="1.000000" type="0">
     <Pos x="67" y="96"/>
     <LabelPos configured="0" direction="0" x="0" y="0"/>
     <CirCompIcon cirIconIdentity="1" cirPortGraphics="IDxQT1JUUz4KICA8UE9SVCBmYWNlPSIzIiB0eXBlPSJzaWduYWwiIHg9IjQwIiB5PSIxNSI+CiAgIDxQT1JUX0JJVE1BUD4kQU1FL2xpYnBvcnRzL0ljb25zL3NpZ25hbDFweC5zdmc8L1BPUlRfQklUTUFQPgogIDwvUE9SVD4KIDwvUE9SVFM+Cg==" cirPortHidden="0">
      <IconMap data="H4sIAAAAAAACCo1SwY7bIBC95ytGswe30gYbO6vaUchqe+iphx7ac+Q62EHBYAFrO/36Do7TXnooQprh8XgzDzi8zr2GUTqvrBEJZ1kC0jT2rEwnkh/fv2zL5PW4OfixA2IaL/ASwrBP02ma2FQw67o0z7IsJQbeKftZK3P9F5FXVZUuu/inJnKWI/ysvfzmbKu0FBiUuSGos8CvapRa2xMnaYHZMCPc1jipc7gI3C2Li1TdJQjMq7galZw+23gAMthlkFcIluq12k4CfeOs1kuvez/UDRUcnPTSjRLJaXfcAMChUa7REqghLfCpXQaCD85e6cBTtowHsO1VkE4rCuSH4IaK8x17oez2yFxMML3LBzkHCK42vrWuF9jXwan5A4fYMgdOs2R5seMfEVprwrate6VJK3lzqtbJinr1S0ZZcn28HtKoShbSLvpYLrB59+HET151ptZ4r033/zBmrJH/72rmAouCnoA/PM15fAFC8hVZ7Q1W3zprYLDKBPozefnMOXuBImf8ORIhIp/WWLISioJVf3cylgNEsbuX+LmOm9+vXzT5rAIAAA==" format="svgz/base64"/>
     </CirCompIcon>
     <Ports>
      <Port connect="1" decorationOrientation="0" decorationVisible="0" face="3" name="" type="signal">
       <Pos x="40" y="15"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="1" port="0"/>
       </Connects>
      </Port>
     </Ports>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="0" codeGenVersion="2.0" dir="$AME/libsig/submodels" discontinuity="1" hasTerminate="1" idMax="29" idsReset="0" label="constant signal" name="CONS00" needsUpdateCheck="1" outputType="1" type="0" unit="1">
      <RealParams>
       <Params>
        <Param defValue="1" historyVariable="k0GEN" maxValue="1e+30" minValue="-1e+30" subId="3" title="constant value" tunable="True" units="null" value="1" varName="k" visibility="True"/>
       </Params>
      </RealParams>
      <ParamsGroups>
       <Group circuitScopeId="4" editable="0" editableTitle="1" groupHeadIcon="" name="ROOTGROUP" origTitle="ROOTGROUP" subId="29">
        <Elements>
         <Element display="0" varName="k"/>
         <Element display="1" varName="out"/>
        </Elements>
       </Group>
      </ParamsGroups>
      <IntVars>
       <Vars>
        <Var defValue="0" dimension="1" maxValue="1e+30" minValue="-1e+30" saveValue="1" subId="28" title="constant value - Linked variable" type="10" units="null" value="0" varName="k0GEN" visibility="False">
         <LaData>
          <Data laStatus="0"/>
         </LaData>
        </Var>
       </Vars>
      </IntVars>
      <ExtVars>
       <Port tag="signal">
        <Vars>
         <Var dimension="1" io="2" saveValue="1" subId="24" title="output" type="0" units="null" varName="out" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
      </ExtVars>
     </Submodel>
    </Comp>
    <Comp alias="signalsink" circuitScopeId="2" depth="202" displayName="signalsink" geometry="1" iconDescription="general signal sink" labelVisible="0" libraryId="sig.signalsink" name="signalsink" scaleX="1.000000" scaleY="1.000000" type="0">
     <Pos x="107" y="106"/>
     <LabelPos configured="0" direction="0" x="0" y="0"/>
     <CirCompIcon cirIconIdentity="1" cirPortGraphics="IDxQT1JUUz4KICA8UE9SVCBmYWNlPSIyIiB0eXBlPSJzaWduYWwiIHg9IjEiIHk9IjUiPgogICA8UE9SVF9CSVRNQVA+JEFNRS9saWJwb3J0cy9JY29ucy9zaWduYWwxcHguc3ZnPC9QT1JUX0JJVE1BUD4KICA8L1BPUlQ+CiA8L1BPUlRTPgo=" cirPortHidden="0">
      <IconMap data="H4sIAAAAAAACCp1RPW/DIBDd+ytO18FLaoz7kTgKidShU4cO7RylDsEoBCygxv73PTtp1KFTGbgPHu/d0602/clAJ33QzoqM50UG0tZur60S2cf7y90i26xvVqFTQEgbBDYxtkvGUkp5us+dV6wsioIRAs+QZW+0Pf4F5FVVsekVr5rI8xLhcxfkm3cHbaTAqO2AoPcCX3UnjXFbTtQCi7ZHGC4x6X1sBFZj3kitmngpOi3TsxvhUEAFFYIjrYNxSWCovTNmmnMZ2l1NYq2XQfpOIrn0so6j0PxKX/4iR0YQNc1Vf4W45dugld0Z+gkAK7IlgQwYgdZZiRCid0dSuC2m89O4O+kovdEUyDy1e06zkjEKD/kj1aXApzEZynOHnQVaZ4Z/i7RO20jbK2cc5jNihXK2AJg8MTVetMD1NyXBqRUPAgAA" format="svgz/base64"/>
     </CirCompIcon>
     <Ports>
      <Port connect="1" decorationOrientation="0" decorationVisible="0" face="2" name="" type="signal">
       <Pos x="1" y="5"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="0" port="0"/>
       </Connects>
      </Port>
     </Ports>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="0" codeGenVersion="2.0" dir="$AME/libsig/submodels" hasNoCalc="1" hasTerminate="1" idMax="2" idsReset="0" label="plug for signal port" name="SSINK" needsUpdateCheck="1" outputType="1" type="0" unit="1">
      <ParamsGroups>
       <Group circuitScopeId="6" editable="0" editableTitle="1" groupHeadIcon="" name="ROOTGROUP" origTitle="ROOTGROUP" subId="2">
        <Elements>
         <Element display="1" varName="sink"/>
        </Elements>
       </Group>
      </ParamsGroups>
      <ExtVars>
       <Port tag="signal">
        <Vars>
         <Var dimension="1" io="1" saveValue="1" subId="1" title="signal input" type="0" units="null" varName="sink" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
      </ExtVars>
     </Submodel>
    </Comp>
    <Comp alias="component_1" circuitScopeId="3" depth="203" displayName="SCStepSnk1" geometry="1" hasDefaultIcon="1" iconDescription="description for supercomponent" isTextShown="1" labelVisible="0" libraryId="StepSnk1.SCStepSnk1" name="SCStepSnk1" scaleX="1.000000" scaleY="1.000000" text="SCStepSnk1" type="0">
     <Pos x="161" y="67"/>
     <LabelPos configured="0" direction="0" x="0" y="0"/>
     <CirCompIcon cirIconIdentity="1" cirPortGraphics="IDxQT1JUUy8+Cg==" cirPortHidden="0">
      <IconMap data="H4sIAAAAAAACCs1TTY/bIBC991cgcmnV2mBvoiaW8UpVtVKv7VY9s4AdGhssIHHy7zvQxJuNtu21SMYzb958MVDfH4ceHZTz2hqGi5xipIywUpuO4e+PD9kaIx+4kby3RjFsLL5van/oEDgaX0nB8DaEsSJk3Ls+t64jUhDVq0GZ4EmRFwSfueKZK5ziQR+UsMNgjU9uxi8uTCfbmTpNUz7dJUax2WwILUlZZsDI/MkEfsyu/KCu1/xKSikB24V27LXZ/TFBsp6pf4920Gr6ZI8MU0TR+g59XOLrsyww0pJhoK5xUw8qcMkDT9hFWYEBWqm+fn5oaiGqH9btUAT4k90HhhHYpaha6wYeGj3wTsXU76G4mjwbIiecRpVcnfJ274R6dTBSDDoyybeg+/5LDIjJb38degUiOZcB0lwZudTb1B0KjhsfE0MbPDh9fAvXBk5g3pJalPP+7h9N/h89jrY/weQVasGJ4UWbFk5qZkcuIGZ6IfBERqvhcjO8zFf0A4UNrdY34nITZXorRmn2ik/L2R10saBpXYBMcr/lznHI+AKzbesVHBnNr8ixasFHhp/2IbxAf0KdMCUdlJvxpPUafgyX12Fuejyjk5Zhe8biyXXwwXSaN78AUoubQDsEAAA=" format="svgz/base64"/>
     </CirCompIcon>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="1" codeGenVersion="1.0" dir="D:/Test_Libraries/StepSnk1/submodels" name="SMSTEPSNK1" needsUpdateCheck="1" outputType="0" type="1" unit="0">
      <ExposedOrder>
       <Params>
        <Groups/>
       </Params>
       <Vars>
        <Groups/>
       </Vars>
      </ExposedOrder>
     </Submodel>
     <Supercomponent catname="StepSnk1" scDir="D:/Test_Libraries/StepSnk1/submodels">
      <PortsMap/>
      <Circuit ameApplication="AMESim" highestId="51">
       <Comps>
        <Comp alias="step" circuitScopeId="1" depth="201" displayName="step" geometry="1" iconDescription="step signal source" labelVisible="0" libraryId="sig.step" name="step" scaleX="1.000000" scaleY="1.000000" type="0">
         <Pos x="67" y="67"/>
         <LabelPos configured="0" direction="0" x="0" y="0"/>
         <CirCompIcon cirIconIdentity="1" cirPortGraphics="IDxQT1JUUz4KICA8UE9SVCBmYWNlPSIzIiB0eXBlPSJzaWduYWwiIHg9IjQwIiB5PSIxNSI+CiAgIDxQT1JUX0JJVE1BUD4kQU1FL2xpYnBvcnRzL0ljb25zL3NpZ25hbDFweC5zdmc8L1BPUlRfQklUTUFQPgogIDwvUE9SVD4KIDwvUE9SVFM+Cg==" cirPortHidden="0">
          <IconMap data="H4sIAAAAAAACCp1SsXLjIBDt/RU7m8KNgwDZE8ljnJkrrroiRa72ODKWmRDQAJHkv79FtnMurrgJzS7LY997LJvn8cNCr0M03qm5YHwO2jX+YFyr5r9ffz5W8+ftbBP7FgjposJTSt26KIZhYEPJfGgLyTkvCIEXyHq0xr3/Cyjqui6mU/ziRMEkwts+6pfgj8Zqhcm4M4I5KPxlem2t3wlqrZB3I8L5GgdzSCeFy2lz0qY9JYWyzrve6OGHzxeAw5KDrBE88R2tHxTGJnhrJ63r2O0bIuyCjjr0Gslpu50BwKYxobEaSJBV+HCcFkJMwb/ThQc+rVvh8cMkHayhQH6o3BC5WLIVZedbFnKCxaV95+2Z3uFG4LzT/9+988YlmsRqISq2AsHZfZYTWU4BMt2maLOt6T2bz5h2YhdN6/YWL1K+LWMUCsuSJiJuFkeZB0IVea3cuW29+xIuq4UQpK+UTCwyEHLl6RorVkFZsvrvCWfy3kv+a9vZHz/V+s+7AgAA" format="svgz/base64"/>
         </CirCompIcon>
         <Ports>
          <Port connect="1" decorationOrientation="0" decorationVisible="0" face="3" name="" type="signal">
           <Pos x="40" y="15"/>
           <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
           <Connects>
            <Connect num="4" port="0"/>
           </Connects>
          </Port>
         </Ports>
         <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="0" codeGenVersion="2.0" dir="$AME/libsig/submodels" discontinuity="1" hasTerminate="1" iStoresNumber="1" idMax="38" idsReset="0" label="step function" name="STEP0" needsUpdateCheck="1" outputType="1" rStoresNumber="6" timeRequired="1" type="0" unit="0">
          <RealParams>
           <Params>
            <Param defValue="0" historyVariable="out00GEN" maxValue="1e+30" minValue="-1e+30" paramImage="${library_node}/embedded_files/images/STEP0_out0.png" subId="2" title="value before step" tunable="True" units="null" value="0" varName="out0" visibility="True"/>
            <Param defValue="1" historyVariable="out10GEN" maxValue="1e+30" minValue="-1e+30" paramImage="${library_node}/embedded_files/images/STEP0_out1.png" subId="3" title="value after step" tunable="True" units="null" value="1" varName="out1" visibility="True"/>
            <Param defValue="0" historyVariable="t00GEN" maxValue="1e+30" minValue="-1e+30" paramImage="${library_node}/embedded_files/images/STEP0_t0.png" subId="4" title="step time" tunable="True" units="s" value="0" varName="t0" visibility="True"/>
            <Param defValue="0.1" maxValue="1e+30" minValue="0" paramImage="${library_node}/embedded_files/images/SQW00_transition.png" subId="7" title="transition duration" units="s" value="0.1" varName="td" visibility="transitionType>1"/>
           </Params>
          </RealParams>
          <IntParams>
           <Params>
            <Param defValue="1" maxValue="3" minValue="1" paramImage="${library_node}/embedded_files/images/SQW00_transition.png" subId="5" title="transition type" value="1" varName="transitionType" visibility="True">
             <Enums>
              <Enum string="discontinuous"/>
              <Enum string="polynomial (order 3)"/>
              <Enum string="polynomial (order 5)"/>
             </Enums>
            </Param>
           </Params>
          </IntParams>
          <ParamsGroups>
           <Group circuitScopeId="16" editable="0" editableTitle="1" groupHeadIcon="" name="ROOTGROUP" origTitle="ROOTGROUP" subId="38">
            <Elements>
             <Element display="0" varName="transitionType"/>
             <Element display="0" varName="out0"/>
             <Element display="0" varName="out1"/>
             <Element display="0" varName="t0"/>
             <Element display="0" varName="td"/>
             <Element display="1" varName="out"/>
            </Elements>
           </Group>
          </ParamsGroups>
          <IntVars>
           <Vars>
            <Var defValue="0" dimension="1" maxValue="1e+30" minValue="-1e+30" saveValue="1" subId="35" title="value before step - Linked variable" type="10" units="null" value="0" varName="out00GEN" visibility="False">
             <LaData>
              <Data laStatus="0"/>
             </LaData>
            </Var>
            <Var defValue="0" dimension="1" maxValue="1e+30" minValue="-1e+30" saveValue="1" subId="36" title="value after step - Linked variable" type="10" units="null" value="0" varName="out10GEN" visibility="False">
             <LaData>
              <Data laStatus="0"/>
             </LaData>
            </Var>
            <Var defValue="0" dimension="1" maxValue="1e+30" minValue="-1e+30" saveValue="1" subId="37" title="step time - Linked variable" type="10" units="s" value="0" varName="t00GEN" visibility="False">
             <LaData>
              <Data laStatus="0"/>
             </LaData>
            </Var>
           </Vars>
          </IntVars>
          <ExtVars>
           <Port tag="signal">
            <Vars>
             <Var dimension="1" io="2" saveValue="1" subId="1" title="step output" type="0" units="null" varName="out" visibility="True">
              <LaData>
               <Data laStatus="0"/>
              </LaData>
             </Var>
            </Vars>
           </Port>
          </ExtVars>
         </Submodel>
        </Comp>
        <Comp alias="signalsink_1" circuitScopeId="2" depth="202" displayName="signalsink" geometry="1" iconDescription="general signal sink" labelVisible="0" libraryId="sig.signalsink" name="signalsink" scaleX="1.000000" scaleY="1.000000" type="0">
         <Pos x="107" y="77"/>
         <LabelPos configured="0" direction="0" x="0" y="0"/>
         <CirCompIcon cirIconIdentity="1" cirPortGraphics="IDxQT1JUUz4KICA8UE9SVCBmYWNlPSIyIiB0eXBlPSJzaWduYWwiIHg9IjEiIHk9IjUiPgogICA8UE9SVF9CSVRNQVA+JEFNRS9saWJwb3J0cy9JY29ucy9zaWduYWwxcHguc3ZnPC9QT1JUX0JJVE1BUD4KICA8L1BPUlQ+CiA8L1BPUlRTPgo=" cirPortHidden="0">
          <IconMap data="H4sIAAAAAAACCp1RPW/DIBDd+ytO18FLaoz7kTgKidShU4cO7RylDsEoBCygxv73PTtp1KFTGbgPHu/d0602/clAJ33QzoqM50UG0tZur60S2cf7y90i26xvVqFTQEgbBDYxtkvGUkp5us+dV6wsioIRAs+QZW+0Pf4F5FVVsekVr5rI8xLhcxfkm3cHbaTAqO2AoPcCX3UnjXFbTtQCi7ZHGC4x6X1sBFZj3kitmngpOi3TsxvhUEAFFYIjrYNxSWCovTNmmnMZ2l1NYq2XQfpOIrn0so6j0PxKX/4iR0YQNc1Vf4W45dugld0Z+gkAK7IlgQwYgdZZiRCid0dSuC2m89O4O+kovdEUyDy1e06zkjEKD/kj1aXApzEZynOHnQVaZ4Z/i7RO20jbK2cc5jNihXK2AJg8MTVetMD1NyXBqRUPAgAA" format="svgz/base64"/>
         </CirCompIcon>
         <Ports>
          <Port connect="1" decorationOrientation="0" decorationVisible="0" face="2" name="" type="signal">
           <Pos x="1" y="5"/>
           <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
           <Connects>
            <Connect num="3" port="0"/>
           </Connects>
          </Port>
         </Ports>
         <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="0" codeGenVersion="2.0" dir="$AME/libsig/submodels" hasNoCalc="1" hasTerminate="1" idMax="2" idsReset="0" label="plug for signal port" name="SSINK" needsUpdateCheck="1" outputType="1" type="0" unit="1">
          <ParamsGroups>
           <Group circuitScopeId="18" editable="0" editableTitle="1" groupHeadIcon="" name="ROOTGROUP" origTitle="ROOTGROUP" subId="2">
            <Elements>
             <Element display="1" varName="sink"/>
            </Elements>
           </Group>
          </ParamsGroups>
          <ExtVars>
           <Port tag="signal">
            <Vars>
             <Var dimension="1" io="1" saveValue="1" subId="1" title="signal input" type="0" units="null" varName="sink" visibility="True">
              <LaData>
               <Data laStatus="0"/>
              </LaData>
             </Var>
            </Vars>
           </Port>
          </ExtVars>
         </Submodel>
        </Comp>
       </Comps>
       <animationProperties loop="0" speed="1"/>
       <globalParams/>
      </Circuit>
     </Supercomponent>
    </Comp>
    <Comp alias="constant_1" circuitScopeId="1" depth="204" displayName="constant" geometry="1" iconDescription="constant signal source" labelVisible="0" libraryId="sig.constant" name="constant" scaleX="1.000000" scaleY="1.000000" type="0">
     <Pos x="133" y="200"/>
     <LabelPos configured="0" direction="0" x="0" y="0"/>
     <CirCompIcon cirIconIdentity="1" cirPortGraphics="IDxQT1JUUz4KICA8UE9SVCBmYWNlPSIzIiB0eXBlPSJzaWduYWwiIHg9IjQwIiB5PSIxNSI+CiAgIDxQT1JUX0JJVE1BUD4kQU1FL2xpYnBvcnRzL0ljb25zL3NpZ25hbDFweC5zdmc8L1BPUlRfQklUTUFQPgogIDwvUE9SVD4KIDwvUE9SVFM+Cg==" cirPortHidden="0">
      <IconMap data="H4sIAAAAAAACCo1SsY7bMAzd8xUEb3ALXGTLzqF2EOVwHTp16NDOgevIDhFZMiSd7fTrKzlOu3SoIIDUE/XIR/HwOvcKRmkdGS0SzrIEpG7MmXQnkh/fv2zL5PW4ObixgxCp3b7upaNe4KjPTPWOUV93pCW743iPEnjxftin6TRNbCqYsV2aZ1mWBp41ZD8r0td/BfKqqtLlFv9UhpzlCD9rJ79Z05KSAj3pGwKdBX6lUSplTjxQC8yGGeG22onO/iJwtxwukrqLF5hX8TSSnD6b+AAy2GWQVwgm5GuVmQS6xhqlllr3bqibkHCw0kk7Sgz96I4bADg0ZBslIRSkBD61y0Jw3pprePCULesBbHvy0ioKJugJcBOS8x17Cd7t4dnoYHqn93L24G2tXWts6Hlfe0vzBw6xZA487JLlxY5/RGiN9tu27kkFruTNUq2SFXX0S0baoPp4PaSRNUhIu6hjaWDz7vyJnxx1ulZ4zx36/xCmjZb/r2rmAosifAF/aJrz+AMByVdklTcYdeuMhsGQ9mFm8vKZc/YCRc74cwyEiHxabclKKApW/b3JWA4Qye5a4nAdN78BjYBj0dICAAA=" format="svgz/base64"/>
     </CirCompIcon>
     <Ports>
      <Port connect="1" decorationOrientation="0" decorationVisible="0" face="3" name="" type="signal">
       <Pos x="40" y="15"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="6" port="0"/>
       </Connects>
      </Port>
     </Ports>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="0" codeGenVersion="2.0" dir="$AME/libsig/submodels" discontinuity="1" hasTerminate="1" idMax="29" idsReset="0" label="constant signal" name="CONS00" outputType="1" type="0" unit="1">
      <RealParams>
       <Params>
        <Param defValue="1" historyVariable="k0GEN" maxValue="1e+30" minValue="-1e+30" subId="3" title="constant value" tunable="True" units="null" value="1" varName="k" visibility="True"/>
       </Params>
      </RealParams>
      <ParamsGroups>
       <Group circuitScopeId="22" editable="0" editableTitle="1" groupHeadIcon="" name="ROOTGROUP" origTitle="ROOTGROUP" subId="29">
        <Elements>
         <Element display="0" varName="k"/>
         <Element display="1" varName="out"/>
        </Elements>
       </Group>
      </ParamsGroups>
      <IntVars>
       <Vars>
        <Var defValue="0" dimension="1" maxValue="1e+30" minValue="-1e+30" saveValue="1" subId="28" title="constant value - Linked variable" type="10" units="null" value="0" varName="k0GEN" visibility="False">
         <LaData>
          <Data laStatus="0"/>
         </LaData>
        </Var>
       </Vars>
      </IntVars>
      <ExtVars>
       <Port tag="signal">
        <Vars>
         <Var dimension="1" io="2" saveValue="1" subId="24" title="output" type="0" units="null" varName="out" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
      </ExtVars>
     </Submodel>
    </Comp>
    <Comp alias="signalsink_1" catname="sig" circuitScopeId="2" depth="205" displayName="signalsink" geometry="1" iconDescription="general signal sink" labelVisible="0" libraryId="sig.signalsink" name="signalsink" scaleX="1.000000" scaleY="1.000000" type="0">
     <Pos x="173" y="210"/>
     <LabelPos configured="0" direction="0" x="0" y="0"/>
     <CirCompIcon cirIconIdentity="1" cirPortGraphics="IDxQT1JUUz4KICA8UE9SVCBmYWNlPSIyIiB0eXBlPSJzaWduYWwiIHg9IjEiIHk9IjUiPgogICA8UE9SVF9CSVRNQVA+JEFNRS9saWJwb3J0cy9JY29ucy9zaWduYWwxcHguc3ZnPC9QT1JUX0JJVE1BUD4KICA8L1BPUlQ+CiA8L1BPUlRTPgo=" cirPortHidden="0">
      <IconMap data="H4sIAAAAAAACCp1RuVLDMBDt+YqdpXATfHEk9kTJDAUVBQXUGWMr9k5kySMJH3/P2gkZCipUaA89vbdP2u7HVkEvrSOjRZCEcQBSl6YiXYvg4/3lbhPsdzdb19fASO3yopWOWoG9rkLVupDaoiYtw3MfzyiBjfddHkXDMITDfWhsHaVxHEfMc4HkoyJ9+guYZFkWLad4nQyTMEX4LJx8s+ZISgr0pCcEqgS+Ui+VMoeEqQXG3YgwXeJAlW8EZnPeSKobfyl6ksOzmeEQQwYZgmGtozKDQFdao9QyZ+66omSxzkonbS+R38LK0s9C6yt9+oscI4bUy1zll/OH5OCo1oXimwCwZVsS2IASqI2WCM5bc2KF23hZP427lry0ijiweW6PCc/Kxjg8hI9cpwKf5mRKz53oLNAZNf1bpDOkPf9eukpgvWJWSFcbgMVTVM8bf+DuG+p4C5w1AgAA" format="svgz/base64"/>
     </CirCompIcon>
     <Ports>
      <Port connect="1" decorationOrientation="0" decorationVisible="0" face="2" name="" type="signal">
       <Pos x="1" y="5"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="5" port="0"/>
       </Connects>
      </Port>
     </Ports>
    </Comp>
    <Comp alias="sim_params" circuitScopeId="1" depth="206" displayName="sim_params" geometry="1" iconDescription="set simulation parameters from submodel" labelVisible="0" libraryId="simu.sim_params" name="sim_params" scaleX="1.000000" scaleY="1.000000" type="0">
     <Pos x="376" y="114"/>
     <LabelPos configured="0" direction="0" x="0" y="0"/>
     <CirCompIcon cirIconIdentity="1" cirPortGraphics="IDxQT1JUUy8+Cg==" cirPortHidden="0">
      <IconMap data="H4sIAAAAAAACCo1STY+bMBC951eMvIdciPEHNjiKs1IPPe1hD+25osQBaw1GgCD59x1I0lMPtSx7/Oa9N2PLp/dbG2B2w+hjZ/ecsj24rooX39V2//PH90Oxfz/vTuNcAzK78Vi2bvStJXN3oaEdqW/L2neOPnDyYFnSTFN/TNNlWegiaRzqVDDGUvR5Uo634LuvfxG5MSbdsuRvZ4RTQeB3ObrPIV59cJZMvrsT8BdLPvzsQoi/OFpbwvobgftzX/xlaiwRZj00ztfN9DrN3i3f4ioABsLgJBCx3jXExZKxGmIIW6/HsS8rLNgPbnTD7Ai+R33eAcCp8kMVHGBDwZK36zYIjNMQv1DwxrbxAg6tn9wQPG54H4QrLM4zqjC6v6JhDUj6sO/LqXmad7Fz/++Mj9JCTnWeG615IjIqszxTBVTAEgaSai64EiaRNMswxUFTwXmhpUkO+AnEKgNBmZbK6OQgqVJM5wbWpOZaFkiTlMtCmwwYZXIT5lRKplhRAKcyF4ojKDBikq1uRppCyRXKciWUEFg1Q9vVDL1MgeL16qe0Xhf8K+fdH6Cc6n2hAgAA" format="svgz/base64"/>
     </CirCompIcon>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="0" codeGenVersion="2.0" dir="$AME/libame/submodels" hasTerminate="1" iStoresNumber="1" idMax="47" idsReset="0" label="change simulation parameters" name="SIMP00" outputType="1" type="0" unit="0">
      <RealParams>
       <Params>
        <Param defValue="1e+30" maxValue="1e+30" minValue="1e-05" subId="2" title="maximum time step" units="s" value="1e+30" varName="maxstep" visibility="(setmaxstep == 2)"/>
        <Param defValue="1e-07" maxValue="0.01" minValue="1e-14" subId="1" title="integrator fixed tolerance" units="null" value="1e-07" varName="toler" visibility="(tolermode == 2 &amp;&amp; tolermethod&lt;=3)"/>
        <Param defValue="1e-08" maxValue="1e+30" minValue="1e-16" subId="44" title="absolute tolerance" units="null" value="1e-08" varName="abstol" visibility="tolermode == 2 &amp;&amp; tolermethod>=4"/>
        <Param defValue="1e-06" maxValue="1e+30" minValue="1e-16" subId="45" title="relative tolerance" units="null" value="1e-06" varName="reltol" visibility="tolermode == 2 &amp;&amp; tolermethod>=4"/>
        <Param defValue="1e+30" maxValue="1e+30" minValue="1e-05" subId="3" title="maximum time" units="s" value="1e+30" varName="maxcpu" visibility="(setmaxcpu >= 2)"/>
        <Param defValue="1e-07" maxValue="1e+30" minValue="1e-14" subId="20" title="initial time step value" units="s" value="1e-07" varName="inith" visibility="inithmode == 2"/>
        <Param defValue="0" maxValue="1e+30" minValue="0" subId="25" title="fixed time step" units="s" value="0" varName="fixedh" visibility="True"/>
        <Param defValue="1.49011611938477e-08" maxValue="1.49011611938477e-08" minValue="0" subId="31" title="user-defined perturbation value for numerical Jacobian" units="null" value="1.49011611938477e-08" varName="pertvalue" visibility="jacmethod==4"/>
       </Params>
      </RealParams>
      <IntParams>
       <Params>
        <Param defValue="1" maxValue="2" minValue="1" subId="11" title="set a maximum time step" value="1" varName="setmaxstep" visibility="True">
         <Enums>
          <Enum string="no"/>
          <Enum string="yes"/>
         </Enums>
        </Param>
        <Param defValue="1" maxValue="3" minValue="1" subId="6" title="set integrator tolerance" value="1" varName="tolermode" visibility="True">
         <Enums>
          <Enum string="no"/>
          <Enum string="normal"/>
          <Enum string="log to base 10"/>
         </Enums>
        </Param>
        <Param defValue="5" maxValue="5" minValue="1" subId="4" title="tolerance method" value="5" varName="tolermethod" visibility="tolermode>=2">
         <Enums>
          <Enum string="fixed mixed"/>
          <Enum string="fixed relative"/>
          <Enum string="fixed absolute"/>
          <Enum string="fixed with specified values"/>
          <Enum string="auto scale absolute"/>
         </Enums>
        </Param>
        <Param defValue="-7" maxValue="-2" minValue="-14" subId="7" title="integrator tolerance (log to base 10)" value="-7" varName="intol" visibility="(tolermode == 3 &amp;&amp; tolermethod &lt;=3)"/>
        <Param defValue="-8" maxValue="-2" minValue="-14" subId="46" title="integrator absolute tolerance (log to base 10)" value="-8" varName="inatol" visibility="(tolermode == 3 &amp;&amp; tolermethod>=4)"/>
        <Param defValue="-6" maxValue="-2" minValue="-14" subId="47" title="integrator relative tolerance (log to base 10)" value="-6" varName="inrtol" visibility="(tolermode == 3 &amp;&amp; tolermethod>=4)"/>
        <Param defValue="1" maxValue="3" minValue="1" subId="5" title="set a maximum time" value="1" varName="setmaxcpu" visibility="True">
         <Enums>
          <Enum string="no"/>
          <Enum string="CPU time"/>
          <Enum string="elapsed time"/>
         </Enums>
        </Param>
        <Param defValue="1" maxValue="3" minValue="1" subId="12" title="expression evaluation error handling" value="1" varName="expevalerror" visibility="True">
         <Enums>
          <Enum string="fatal error"/>
          <Enum string="warning"/>
          <Enum string="ignore"/>
         </Enums>
        </Param>
        <Param defValue="1" maxValue="2" minValue="1" subId="17" title="initial time step computation" value="1" varName="inithmode" visibility="True">
         <Enums>
          <Enum string="automatic"/>
          <Enum string="manual"/>
         </Enums>
        </Param>
        <Param defValue="20" maxValue="100000" minValue="0" subId="34" title="maximum consecutive solver step restarts" value="20" varName="maxallowedconsrestart" visibility="True"/>
        <Param defValue="1" maxValue="2" minValue="1" subId="26" title="matrix equilibration" value="1" varName="matequilib" visibility="True">
         <Enums>
          <Enum string="disabled"/>
          <Enum string="enabled"/>
         </Enums>
        </Param>
        <Param defValue="1" maxValue="4" minValue="1" subId="28" title="perturbation for numerical Jacobian" value="1" varName="jacmethod" visibility="True">
         <Enums>
          <Enum string="model-defined"/>
          <Enum string="forced adaptive"/>
          <Enum string="forced legacy"/>
          <Enum string="user-defined"/>
         </Enums>
        </Param>
        <Param defValue="2" maxValue="2" minValue="1" subId="36" title="heuristic for Jacobian computation" value="2" varName="jacheur" visibility="True">
         <Enums>
          <Enum string="legacy"/>
          <Enum string="Jacobian saving"/>
         </Enums>
        </Param>
        <Param defValue="4" maxValue="4" minValue="1" subId="14" title="Jacobian storage method" value="4" varName="jacstore" visibility="True">
         <Enums>
          <Enum string="automatic"/>
          <Enum string="dense"/>
          <Enum string="sparse"/>
          <Enum string="KLU sparse"/>
         </Enums>
        </Param>
        <Param defValue="1" maxValue="2" minValue="1" subId="37" title="btf pre ordering" value="1" varName="klubtf" visibility="jacstore == 4">
         <Enums>
          <Enum string="yes"/>
          <Enum string="no"/>
         </Enums>
        </Param>
        <Param defValue="1" maxValue="2" minValue="1" subId="38" title="ordering" value="1" varName="kluordering" visibility="jacstore == 4">
         <Enums>
          <Enum string="AMD"/>
          <Enum string="COLAMD"/>
         </Enums>
        </Param>
        <Param defValue="1" maxValue="3" minValue="1" subId="39" title="scaling" value="1" varName="kluscaling" visibility="jacstore == 4">
         <Enums>
          <Enum string="none"/>
          <Enum string="sum"/>
          <Enum string="max"/>
         </Enums>
        </Param>
       </Params>
      </IntParams>
      <ParamsGroups>
       <Group circuitScopeId="48" editable="0" editableTitle="1" groupHeadIcon="" name="ROOTGROUP" origTitle="ROOTGROUP" subId="27">
        <Elements>
         <Element display="0" varName="setmaxcpu"/>
         <Element display="0" varName="expevalerror"/>
         <Element display="0" varName="maxcpu"/>
         <Element display="2" varName="varstepsolv"/>
         <Element display="2" varName="fixedstepsolv"/>
        </Elements>
       </Group>
       <Group circuitScopeId="49" editable="0" editableTitle="1" groupHeadIcon="" name="varstepsolv" origTitle="variable step solver specific" subId="22">
        <Elements>
         <Element display="0" varName="tolermode"/>
         <Element display="0" varName="tolermethod"/>
         <Element display="0" varName="toler"/>
         <Element display="0" varName="abstol"/>
         <Element display="0" varName="reltol"/>
         <Element display="0" varName="intol"/>
         <Element display="0" varName="inatol"/>
         <Element display="0" varName="inrtol"/>
         <Element display="0" varName="setmaxstep"/>
         <Element display="0" varName="maxstep"/>
         <Element display="0" varName="inithmode"/>
         <Element display="0" varName="inith"/>
         <Element display="0" varName="maxallowedconsrestart"/>
         <Element display="0" varName="matequilib"/>
         <Element display="0" varName="jacmethod"/>
         <Element display="0" varName="pertvalue"/>
         <Element display="0" varName="jacheur"/>
         <Element display="0" varName="jacstore"/>
         <Element display="2" varName="kluptions"/>
        </Elements>
       </Group>
       <Group circuitScopeId="50" editable="0" editableTitle="1" groupHeadIcon="" name="fixedstepsolv" origTitle="fixed step solver specific" subId="23">
        <Elements>
         <Element display="0" varName="fixedh"/>
        </Elements>
       </Group>
       <Group circuitScopeId="51" editable="0" editableTitle="1" groupHeadIcon="" name="kluptions" origTitle="KLU options" subId="40">
        <Elements>
         <Element display="0" varName="klubtf"/>
         <Element display="0" varName="kluordering"/>
         <Element display="0" varName="kluscaling"/>
        </Elements>
       </Group>
      </ParamsGroups>
     </Submodel>
    </Comp>
   </Comps>
   <animationProperties loop="0" speed="1"/>
   <globalParams/>
  </Circuit>
 </Supercomponent>
</SUB>
