<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE SUB>
<SUB AME_VERSION="2604" DOC_VERSION="6" HOTFIX="0" MAJ="20261" UPDATE="0">
 <Supercomponent catname="Lib_Boosters" scSubName="SC_BOOSTER_1">
  <PortsMap>
   <Map>
    <PortMap component="1" face="3" labelX="0.000000" labelY="0.000000" port="3" type="lshaft" x="613" y="337"/>
    <PortMap component="0" face="2" labelX="0.000000" labelY="0.000000" port="3" type="lshaft" x="155" y="337"/>
   </Map>
  </PortsMap>
  <Circuit ameApplication="AMESim" highestId="18328">
   <Comps>
    <Comp alias="linear2signal3_2" circuitScopeId="659" depth="201" displayName="linear2signal3" geometry="8" iconDescription="conversion between linear mechanical and signal variables (with displacement)" labelVisible="0" libraryId="meca.linear2signal3" name="linear2signal3" scaleX="1.000000" scaleY="1.000000" type="0">
     <Pos x="154" y="312"/>
     <LabelPos configured="0" direction="0" x="0" y="0"/>
     <CirCompIcon cirIconIdentity="1" cirPortGraphics="IDxQT1JUUz4KICA8UE9SVCBmYWNlPSIzIiB0eXBlPSJzaWduYWwiIHg9IjQ5IiB5PSIxMyI+CiAgIDxQT1JUX0JJVE1BUD4kQU1FL2xpYnBvcnRzL0ljb25zL3NpZ25hbDFweC5zdmc8L1BPUlRfQklUTUFQPgogIDwvUE9SVD4KICA8UE9SVCBmYWNlPSIzIiB0eXBlPSJzaWduYWwiIHg9IjQ5IiB5PSIyNSI+CiAgIDxQT1JUX0JJVE1BUD4kQU1FL2xpYnBvcnRzL0ljb25zL3NpZ25hbDFweC5zdmc8L1BPUlRfQklUTUFQPgogIDwvUE9SVD4KICA8UE9SVCBmYWNlPSIzIiB0eXBlPSJzaWduYWwiIHg9IjQ5IiB5PSIzNyI+CiAgIDxQT1JUX0JJVE1BUD4kQU1FL2xpYnBvcnRzL0ljb25zL3NpZ25hbDFweC5zdmc8L1BPUlRfQklUTUFQPgogIDwvUE9SVD4KICA8UE9SVCBmYWNlPSIyIiB0eXBlPSJsc2hhZnQiIHg9IjEiIHk9IjI1Ij4KICAgPFBPUlRfQklUTUFQPiRBTUUvbGlicG9ydHMvSWNvbnMvbHNoYWZ0MXB4LnN2ZzwvUE9SVF9CSVRNQVA+CiAgPC9QT1JUPgogPC9QT1JUUz4K" cirPortHidden="0">
      <IconMap data="H4sIAAAAAAACCq1VTY+bMBC976+wvIe0Eh+2gV2IQlbtYdVDK/XQVr1FlBiw1rEj7Ibs/vqODcmmVXOINsjCM48xb549A4uH/UaiHe+N0Kqc0YjMEFe1XgvVlrPv3x7DfPawvFmYXYsgUpkSd9Zu53E8DEM0JJHu25gRQmKIwGPIfC+FevpfIC2KIvZP8ZET04hh9Ksy/GuvGyF5ia1QzxiJdYk/ix2XUq8ovLrEZLvH6HmaB7G2XYnTwjkdF21nD95O8OGjdgsQQWkBAyMNfI3UQ4lN3Wspfa5zs61qINz23PB+xzEobT1x/dvYVbqSpqsaCzBCaAF5cwQZyhIrrThGxvb6CZbfEn8dgHAjLO+lgAnUAbynJWZplEHyYKUAsCMAFsHxSLDV8vmE5Lbx13meaQvYWeKtFsrCkbE8oBmCe4oYHW/gI8e7iFsnekqgst3VyGEXvyR3URYkoLTOwCABJSE4bqLEODP0JowuZCmkUIc+EIBgfAqxZlwyjk/ulS+HHbN8b5HtK2Ua3W9KvKlsL/bv7iLKEpakPKT3KKSIor8QGCx/j1GjlQ2baiMkFNXsQy8qOZtQI15AM2VQTsvHRex43sLI8ii7iPPH2zlTciHnzwPnVBOvjZCsjGhVJa/RCO78pkYoxk6YEG+daYXLaA5lnySB34SxCqGwYE9G5LT0X2WyK8o86ffi34a/skzX0v6s04NM1+nnZdIryqRsEklGkd5nXvSJxFarY7Y0858ERFmQ5FGO8tG9nzDIu4AGjajzT/J3/5flzR/BG6/JrwYAAA==" format="svgz/base64"/>
     </CirCompIcon>
     <Ports>
      <Port connect="2" decorationOrientation="0" decorationVisible="0" face="3" name="" type="signal">
       <Pos x="49" y="13"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="2" port="0"/>
       </Connects>
      </Port>
      <Port connect="2" decorationOrientation="0" decorationVisible="0" face="3" name="" type="signal">
       <Pos x="49" y="25"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="1" port="0"/>
       </Connects>
      </Port>
      <Port connect="2" decorationOrientation="0" decorationVisible="0" face="3" name="" type="signal">
       <Pos x="49" y="37"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="0" port="1"/>
       </Connects>
      </Port>
      <Port connect="0" decorationOrientation="0" decorationVisible="0" face="2" name="" type="lshaft">
       <Pos x="1" y="25"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="32" port="0"/>
       </Connects>
      </Port>
     </Ports>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="0" codeGenVersion="2.0" dir="$AME/libmec/submodels" hasNoCalc="1" hasTerminate="1" idMax="10" idsReset="0" label="conversion between linear mechanical and signal variables" name="FVXSG1" outputType="1" type="0" unit="1">
      <ParamsGroups>
       <Group circuitScopeId="17136" editable="0" editableTitle="1" groupHeadIcon="" name="ROOTGROUP" origTitle="ROOTGROUP" subId="10">
        <Elements>
         <Element display="1" varName="v4"/>
         <Element display="1" varName="x4"/>
         <Element display="1" varName="f4"/>
        </Elements>
       </Group>
      </ParamsGroups>
      <ExtVars>
       <Port tag="signal">
        <Vars>
         <Var express2="@_4_3" saveValue="1" subId="9" title="output force signal at port 1" type="7" units="null" unplottable="1" varName="fsig" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
       <Port tag="signal">
        <Vars>
         <Var dimension="1" io="1" saveValue="1" subId="2" title="input velocity signal at port 2" type="0" units="null" unplottable="1" varName="vsig" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
       <Port tag="signal">
        <Vars>
         <Var dimension="1" io="1" saveValue="1" subId="3" title="input displacement signal at port 3" type="0" units="null" unplottable="1" varName="xsig" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
       <Port tag="lshaft">
        <Vars>
         <Var express2="@_2_1" saveValue="1" subId="7" title="velocity at port 4" type="7" units="m/s" varName="v4" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
         <Var express2="@_3_1" origTitle="displacement at port 4" saveValue="1" subId="8" title="displacement at booster inlet" type="7" units="m" varName="x4" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
         <Var dimension="1" io="1" saveValue="1" subId="4" title="force at port 4" type="0" units="N" varName="f4" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
      </ExtVars>
     </Submodel>
    </Comp>
    <Comp alias="linear2signal4_2" circuitScopeId="660" depth="202" displayName="linear2signal4" geometry="2" iconDescription="conversion between linear mechanical and signal variables (with displacement)" labelVisible="0" libraryId="meca.linear2signal4" name="linear2signal4" scaleX="1.000000" scaleY="1.000000" type="0">
     <Pos x="564" y="312"/>
     <LabelPos configured="0" direction="0" x="0" y="0"/>
     <CirCompIcon cirIconIdentity="1" cirPortGraphics="IDxQT1JUUz4KICA8UE9SVCBmYWNlPSIyIiB0eXBlPSJzaWduYWwiIHg9IjEiIHk9IjEzIj4KICAgPFBPUlRfQklUTUFQPiRBTUUvbGlicG9ydHMvSWNvbnMvc2lnbmFsMXB4LnN2ZzwvUE9SVF9CSVRNQVA+CiAgPC9QT1JUPgogIDxQT1JUIGZhY2U9IjIiIHR5cGU9InNpZ25hbCIgeD0iMSIgeT0iMjUiPgogICA8UE9SVF9CSVRNQVA+JEFNRS9saWJwb3J0cy9JY29ucy9zaWduYWwxcHguc3ZnPC9QT1JUX0JJVE1BUD4KICA8L1BPUlQ+CiAgPFBPUlQgZmFjZT0iMiIgdHlwZT0ic2lnbmFsIiB4PSIxIiB5PSIzNyI+CiAgIDxQT1JUX0JJVE1BUD4kQU1FL2xpYnBvcnRzL0ljb25zL3NpZ25hbDFweC5zdmc8L1BPUlRfQklUTUFQPgogIDwvUE9SVD4KICA8UE9SVCBmYWNlPSIzIiB0eXBlPSJsc2hhZnQiIHg9IjQ5IiB5PSIyNSI+CiAgIDxQT1JUX0JJVE1BUD4kQU1FL2xpYnBvcnRzL0ljb25zL2xzaGFmdDFweC5zdmc8L1BPUlRfQklUTUFQPgogIDwvUE9SVD4KIDwvUE9SVFM+Cg==" cirPortHidden="0">
      <IconMap data="H4sIAAAAAAACCq1VwY7aMBC971dY3gOtRBLbSShBhFV7WPXQSj20VW8oBSex1tgodgns13dsB5ZWpRJaIiueeRn7zbNnYP6w30i0450RWpUjGpMR4mql10I15ejb18doOnpY3M3NrkEQqUyJW2u3syTp+z7u01h3TcIIIQlE4BAy20uhnv4VSIuiSPxXfOLENGYY/awM/9LpWkheYivUASOxLvEnseNS6iWFrUtMtnuMDsPci7VtS5wVzmm5aFp79HaC9x+0W4AIygoYGGngq6XuS2xWnZbS5zoz22oFhNuOG97tOAaljSde/TJ2mS2laavaAowQmkPeHEGGssRKK46RsZ1+guX3xD9HINoIyzspYAJ1AO9piVkW55A8WBkA7ASARXASCLZaHs5I7mv/XOYZjoBdJN5qoSxcGZuOaY7gnSFGwwt85HjnSeNEDwlUtr0ZOZzi53QS5+MUlK5yMMiYkggcN1FinBl5E0YbsQxSWEU+EIBx+AqxJiwJ46Pb8vl4YpbvLbJdpUytu02JN5XtxP7NJKYsZWnGI/oORRRR9AcCg03fYlRrZaO62ggJRTV634lKjgbUiGfQTBmU0+Jxnjie1zCyaZxfxfn99ZwZuZLzx5FzqImXRkiXRjSqkrdoBHd/QyOQ0AkDwlz7nrdCo9WpgjMCZYRCOU3jKUpT71NfXgEHvdDqNJ445Ly2X3SwG+o4a2jyd0df1gE9CNm5yKADOhF8WgQdHvc6WPE/HfSGOig76SiCjgHxN3Php+k6mqP4Yuxr0u0/TnNnTQJyptL9jyzufgNe55MSlwYAAA==" format="svgz/base64"/>
     </CirCompIcon>
     <Ports>
      <Port connect="2" decorationOrientation="0" decorationVisible="0" face="2" name="" type="signal">
       <Pos x="1" y="13"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="14" port="1"/>
       </Connects>
      </Port>
      <Port connect="2" decorationOrientation="0" decorationVisible="0" face="2" name="" type="signal">
       <Pos x="1" y="25"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="1" port="1"/>
       </Connects>
      </Port>
      <Port connect="2" decorationOrientation="0" decorationVisible="0" face="2" name="" type="signal">
       <Pos x="1" y="37"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="0" port="0"/>
       </Connects>
      </Port>
      <Port connect="0" decorationOrientation="0" decorationVisible="0" face="3" name="" type="lshaft">
       <Pos x="49" y="25"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="26" port="0"/>
       </Connects>
      </Port>
     </Ports>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="0" codeGenVersion="2.0" dir="$AME/libmec/submodels" hasNoCalc="1" hasTerminate="1" idMax="16" idsReset="0" label="conversion between linear mechanical and signal variables" name="FVXSG2" outputType="1" type="0" unit="1">
      <ParamsGroups>
       <Group circuitScopeId="17143" editable="0" editableTitle="1" groupHeadIcon="" name="ROOTGROUP" origTitle="ROOTGROUP" subId="16">
        <Elements>
         <Element display="1" varName="f4"/>
         <Element display="1" varName="v4"/>
         <Element display="1" varName="x4"/>
        </Elements>
       </Group>
      </ParamsGroups>
      <ExtVars>
       <Port tag="signal">
        <Vars>
         <Var dimension="1" io="1" saveValue="1" subId="10" title="input force signal at port 1" type="0" units="null" unplottable="1" varName="fsig" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
       <Port tag="signal">
        <Vars>
         <Var express2="@_4_2" saveValue="1" subId="11" title="output velocity signal at port 2" type="7" units="null" unplottable="1" varName="vsig" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
       <Port tag="signal">
        <Vars>
         <Var express2="@_4_3" saveValue="1" subId="12" title="output displacement signal at port 3" type="7" units="null" unplottable="1" varName="xsig" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
       <Port tag="lshaft">
        <Vars>
         <Var express2="@_1_1" origTitle="force at port 4" saveValue="1" subId="15" title="force at port 4 - after booster amplification" type="7" units="N" varName="f4" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
         <Var dimension="1" io="1" saveValue="1" subId="13" title="velocity at port 4" type="0" units="m/s" varName="v4" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
         <Var dimension="1" io="1" saveValue="1" subId="14" title="displacement at port 4" type="0" units="m" varName="x4" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
      </ExtVars>
     </Submodel>
    </Comp>
    <Comp alias="splitter2p2_9" circuitScopeId="665" depth="203" displayName="splitter2p2" geometry="1" iconDescription="signal duplication (alternative)" labelVisible="0" libraryId="sig.splitter2p2" name="splitter2p2" scaleX="1.000000" scaleY="1.000000" type="0">
     <Pos x="295" y="309"/>
     <LabelPos configured="0" direction="0" x="0" y="0"/>
     <CirCompIcon cirIconIdentity="1" cirPortGraphics="IDxQT1JUUz4KICA8UE9SVCBmYWNlPSIzIiB0eXBlPSJzaWduYWwiIHg9IjMxIiB5PSIxNiI+CiAgIDxQT1JUX0JJVE1BUD4kQU1FL2xpYnBvcnRzL0ljb25zL3NpZ25hbDFweC5zdmc8L1BPUlRfQklUTUFQPgogIDwvUE9SVD4KICA8UE9SVCBmYWNlPSIwIiB0eXBlPSJzaWduYWwiIHg9IjE2IiB5PSIxIj4KICAgPFBPUlRfQklUTUFQPiRBTUUvbGlicG9ydHMvSWNvbnMvc2lnbmFsMXB4LnN2ZzwvUE9SVF9CSVRNQVA+CiAgPC9QT1JUPgogIDxQT1JUIGZhY2U9IjIiIHR5cGU9InNpZ25hbCIgeD0iMSIgeT0iMTYiPgogICA8UE9SVF9CSVRNQVA+JEFNRS9saWJwb3J0cy9JY29ucy9zaWduYWwxcHguc3ZnPC9QT1JUX0JJVE1BUD4KICA8L1BPUlQ+CiA8L1BPUlRTPgo=" cirPortHidden="0">
      <IconMap data="H4sIAAAAAAACCq1UPW/bMBDd8ysO7OBFoUgqaiTDcoAOnTp0aGfDkRmZCEMKpKqPf9+jPhwjcZdCgoDjPZ7u3bsjtXvq3zS00nllTbHhlG1AmtKelKmKze9f3++zzdP+bufbCjDS+IKcm6bexnHXdbRLqHVVLBhjMUaQKWTba2VebwXyPM/jcZdcOAmngsDz0cufzr4oLQvSKDMQUKeC/FCt1NoeOKYuCKt7AsNsO3VqzgVJeHDOUlXnZvFaJbtvNnwADBKOLwGLfC/adgXxpbNaj7VufX0skbB20kvXSoJKq/0dAOywSAlYji6IsUYS8I2zrxj7hY3PAty/qUY6rdCgFIR7jhYVDWgzmiIgEMgREBMQr0AgRMg8zFSBYUYmrpUp0kVGduFIVxIy5R57NXcqvcVRKldqCWW/BJTDsnLhBI2Bu7gK8xsPTvnHN4fk4FVljpqsUCj71IvPVdZWD/9NUltlGrxeCU0jLiALBnPD6OcANxWKFRW+j+Lh4yjYtcLKmkuxHA9JlEOIjB4oLrLJz2m2wAnlwPGOR//SwFfUIB4/jinc/VtzulYhRBSEgPhK+dT0gGSzRS0gHmn+voNqrrWEX9/+L7mnfsNJBQAA" format="svgz/base64"/>
     </CirCompIcon>
     <Ports>
      <Port connect="2" decorationOrientation="0" decorationVisible="0" face="3" name="" type="signal">
       <Pos x="31" y="16"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="7" port="0"/>
       </Connects>
      </Port>
      <Port connect="1" decorationOrientation="0" decorationVisible="0" face="0" name="" type="signal">
       <Pos x="16" y="1"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="3" port="0"/>
       </Connects>
      </Port>
      <Port connect="2" decorationOrientation="0" decorationVisible="0" face="2" name="" type="signal">
       <Pos x="1" y="16"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="2" port="1"/>
       </Connects>
      </Port>
     </Ports>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="0" codeGenVersion="2.0" dir="$AME/libsig/submodels" hasNoCalc="1" hasTerminate="1" idMax="4" idsReset="0" label="splitter junction" name="SPLT0" outputType="1" type="0" unit="0">
      <ParamsGroups>
       <Group circuitScopeId="17147" editable="0" editableTitle="1" groupHeadIcon="" name="ROOTGROUP" origTitle="ROOTGROUP" subId="4">
        <Elements>
         <Element display="1" varName="in3"/>
        </Elements>
       </Group>
      </ParamsGroups>
      <ExtVars>
       <Port tag="signal">
        <Vars>
         <Var dupType="0" primaryPort="2" primaryVar="0" saveValue="1" subId="1" title="input to junction" type="4" varName="out1" visibility="True"/>
        </Vars>
       </Port>
       <Port tag="signal">
        <Vars>
         <Var dupType="0" primaryPort="2" primaryVar="0" saveValue="1" subId="2" title="input to junction" type="4" varName="out2" visibility="True"/>
        </Vars>
       </Port>
       <Port tag="signal">
        <Vars>
         <Var dimension="1" io="1" saveValue="1" subId="3" title="input to junction" type="0" units="null" varName="in3" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
      </ExtVars>
     </Submodel>
    </Comp>
    <Comp alias="fofxyz_4" circuitScopeId="666" depth="204" displayName="fofxyz" geometry="1" iconDescription="defined by expression" labelVisible="0" libraryId="sig.fofxyz" name="fofxyz" scaleX="1.000000" scaleY="1.000000" type="0">
     <Pos x="296" y="260"/>
     <LabelPos configured="0" direction="0" x="0" y="0"/>
     <CirCompIcon cirIconIdentity="1" cirPortGraphics="IDxQT1JUUz4KICA8UE9SVCBmYWNlPSIxIiB0eXBlPSJzaWduYWwiIHg9IjE1IiB5PSI0OSI+CiAgIDxQT1JUX0JJVE1BUD4kQU1FL2xpYnBvcnRzL0ljb25zL3NpZ25hbDFweC5zdmc8L1BPUlRfQklUTUFQPgogIDwvUE9SVD4KICA8UE9SVCBmYWNlPSIzIiB0eXBlPSJzaWduYWwiIHg9IjYxIiB5PSIyNSI+CiAgIDxQT1JUX0JJVE1BUD4kQU1FL2xpYnBvcnRzL0ljb25zL3NpZ25hbDFweC5zdmc8L1BPUlRfQklUTUFQPgogIDwvUE9SVD4KICA8UE9SVCBmYWNlPSIwIiB0eXBlPSJzaWduYWwiIHg9IjE1IiB5PSIxIj4KICAgPFBPUlRfQklUTUFQPiRBTUUvbGlicG9ydHMvSWNvbnMvc2lnbmFsMXB4LnN2ZzwvUE9SVF9CSVRNQVA+CiAgPC9QT1JUPgogIDxQT1JUIGZhY2U9IjIiIHR5cGU9InNpZ25hbCIgeD0iMSIgeT0iMjUiPgogICA8UE9SVF9CSVRNQVA+JEFNRS9saWJwb3J0cy9JY29ucy9zaWduYWwxcHguc3ZnPC9QT1JUX0JJVE1BUD4KICA8L1BPUlQ+CiA8L1BPUlRTPgo=" cirPortHidden="0">
      <IconMap data="H4sIAAAAAAACCrVVTZOaMBi+7694J3twd0aBREBwjDvtoaceemjPDtWImY2JE1IBf33fIOv2wwN2LJckL8nzwfMCi5dmr+AobCWN5iMaRCMQem02Upd89O3rp0k2elk+LKpjCbhTV5zsnDvMw7Cu66CeBsaWIYuiKMQd5Lxl3iipX69tpHmeh91dcuEkNGAEvheV+GLNVirBiZO6JSA3nHyWR6GUWVGE5iQ6NATafqzlxu04Salf7IQsd46TOPeroxT1R+MPQAQphTgnYJBvq0zNSbW2RqlO67w6FGskPFhRCXsUBJ2WywcAWFixdp4zC5KOk0Z+gvoUJ4/b7iJQOWte8fxj1F1vhcleOmGVxMEfvGiN2btSlpHwzORE48DZQldbY/ec7AtnZfNEwaunwJAYZs/IbbSbbIu9VChn9MHKQo36aiVPqMJ7XzaL0AMOgqaITPPB0KcboDvVcRIkg9HbW4RPgeXDsGnqwbe3gOfABj1v6vtw+dSM2/Hp+Y1gEZa+ibruXf+o3CpeVbLUhSJncmx+0beRNloM76GGYj9jK+LAYt+LDeNkhgXWF/p2OhjV/jPJwUjt8B1nQTJmFGZ+QGzo1hmAJ/nL4fSODmlnrT179Q77As7yuzqk2dgb8/Dj3E9ot77ukN3RYZL+GWJKr6dYGn2Rm1DMA/UlSUDPkfjKrB+zIIMkDfL3OxF+VK85of8lK/+B/T2sOLpvWpjOJa5pl1d2rvwSmP8FLR9+Aq4eY5rSBgAA" format="svgz/base64"/>
     </CirCompIcon>
     <Ports>
      <Port connect="1" decorationOrientation="0" decorationVisible="0" face="1" name="" type="signal">
       <Pos x="15" y="49"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="2" port="1"/>
       </Connects>
      </Port>
      <Port connect="2" decorationOrientation="0" decorationVisible="0" face="3" name="" type="signal">
       <Pos x="61" y="25"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="13" port="0"/>
       </Connects>
      </Port>
      <Port connect="2" decorationOrientation="0" decorationVisible="0" face="0" name="" type="signal">
       <Pos x="15" y="1"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="8" port="1"/>
       </Connects>
      </Port>
      <Port connect="1" decorationOrientation="0" decorationVisible="0" face="2" name="" type="signal">
       <Pos x="1" y="25"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="6" port="0"/>
       </Connects>
      </Port>
     </Ports>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="0" codeGenVersion="2.0" dir="$AME/libsig/submodels" hasTerminate="1" iStoresNumber="1" idMax="11" idsReset="0" label="signal output as function of inputs x,y,z" name="FXYZ" outputType="1" type="0" unit="0">
      <IntParams>
       <Params>
        <Param defValue="1" maxValue="4" minValue="1" subId="8" title="output value" value="1" varName="outputtype" visibility="True">
         <Enums>
          <Enum string="f">
           <IconMap data="$AME/libsig/Icons/layers/FXYZ_outputtype_f.svg" format="path"/>
          </Enum>
          <Enum string="df/dx">
           <IconMap data="$AME/libsig/Icons/layers/FXYZ_outputtype_df_dx.svg" format="path"/>
          </Enum>
          <Enum string="df/dy">
           <IconMap data="$AME/libsig/Icons/layers/FXYZ_outputtype_df_dy.svg" format="path"/>
          </Enum>
          <Enum string="df/dz">
           <IconMap data="$AME/libsig/Icons/layers/FXYZ_outputtype_df_dz.svg" format="path"/>
          </Enum>
         </Enums>
        </Param>
        <Param defValue="2" maxValue="2" minValue="1" subId="10" title="discontinuity handling" value="2" varName="disc" visibility="True">
         <Enums>
          <Enum string="inactive"/>
          <Enum string="active"/>
         </Enums>
        </Param>
       </Params>
      </IntParams>
      <TextParams>
       <Params>
        <Param defValue="(y>=x)*(y-x)*z" subId="5" textType="2" title="expression for output as a function of x, y and z" tokenList="x,y,z" value="(y>=x)*(y-x)*z" varName="fstr" visibility="True"/>
       </Params>
      </TextParams>
      <ParamsGroups>
       <Group circuitScopeId="17155" editable="0" editableTitle="1" groupHeadIcon="" name="ROOTGROUP" origTitle="ROOTGROUP" subId="11">
        <Elements>
         <Element display="0" varName="outputtype"/>
         <Element display="0" varName="disc"/>
         <Element display="0" varName="fstr"/>
         <Element display="1" varName="y"/>
         <Element display="1" varName="output"/>
         <Element display="1" varName="x"/>
         <Element display="1" varName="z"/>
        </Elements>
       </Group>
      </ParamsGroups>
      <ExtVars>
       <Port tag="signal">
        <Vars>
         <Var dimension="1" io="1" saveValue="1" subId="1" title="input y" type="0" units="null" varName="y" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
       <Port tag="signal">
        <Vars>
         <Var dimension="1" io="2" origTitle="output from f(x,y,z)" saveValue="1" subId="2" title="force amplified" type="0" units="null" varName="output" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
       <Port tag="signal">
        <Vars>
         <Var dimension="1" io="1" saveValue="1" subId="3" title="input x" type="0" units="null" varName="x" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
       <Port tag="signal">
        <Vars>
         <Var dimension="1" io="1" saveValue="1" subId="4" title="input z" type="0" units="null" varName="z" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
      </ExtVars>
      <IconMap data="$AME/libsig/Icons/layers/FXYZ_frame.svg" format="path"/>
     </Submodel>
    </Comp>
    <Comp alias="constant_6" circuitScopeId="667" depth="205" displayName="constant" geometry="1" iconDescription="constant signal source" labelVisible="0" libraryId="sig.constant" name="constant" scaleX="1.000000" scaleY="1.000000" type="0">
     <Pos x="225" y="270"/>
     <LabelPos configured="0" direction="0" x="0" y="0"/>
     <CirCompIcon cirIconIdentity="1" cirPortGraphics="IDxQT1JUUz4KICA8UE9SVCBmYWNlPSIzIiB0eXBlPSJzaWduYWwiIHg9IjQwIiB5PSIxNSI+CiAgIDxQT1JUX0JJVE1BUD4kQU1FL2xpYnBvcnRzL0ljb25zL3NpZ25hbDFweC5zdmc8L1BPUlRfQklUTUFQPgogIDwvUE9SVD4KIDwvUE9SVFM+Cg==" cirPortHidden="0">
      <IconMap data="H4sIAAAAAAACCo1SwY7bIBC95ytGswe30gYbO6vaUchqe+iphx7ac+Q62EHBYAFrO/36Do7TXnooQprh8XgzDzi8zr2GUTqvrBEJZ1kC0jT2rEwnkh/fv2zL5PW4OfixA2IaL/ASwrBP02ma2FQw67o0z7IsJQbeKftZK3P9F5FXVZUuu/inJnKWI/ysvfzmbKu0FBiUuSGos8CvapRa2xMnaYHZMCPc1jipc7gI3C2Li1TdJQjMq7galZw+23gAMthlkFcIluq12k4CfeOs1kuvez/UDRUcnPTSjRLJaXfcAMChUa7REqghLfCpXQaCD85e6cBTtowHsO1VkE4rCuSH4IaK8x17oez2yFxMML3LBzkHCK42vrWuF9jXwan5A4fYMgdOs2R5seMfEVprwrate6VJK3lzqtbJinr1S0ZZcn28HtKoShbSLvpYLrB59+HET151ptZ4r033/zBmrJH/72rmAouCnoA/PM15fAFC8hVZ7Q1W3zprYLDKBPozefnMOXuBImf8ORIhIp/WWLISioJVf3cylgNEsbuX+LmOm9+vXzT5rAIAAA==" format="svgz/base64"/>
     </CirCompIcon>
     <Ports>
      <Port connect="1" decorationOrientation="0" decorationVisible="0" face="3" name="" type="signal">
       <Pos x="40" y="15"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="6" port="2"/>
       </Connects>
      </Port>
     </Ports>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="0" codeGenVersion="2.0" dir="$AME/libsig/submodels" discontinuity="1" hasTerminate="1" idMax="29" idsReset="0" label="constant signal" name="CONS00" outputType="1" type="0" unit="1">
      <RealParams>
       <Params>
        <Param defValue="2500/700" historyVariable="k0GEN" maxValue="1e+30" minValue="-1e+30" subId="3" title="constant value" tunable="True" units="null" value="2500/700" varName="k" visibility="True"/>
       </Params>
      </RealParams>
      <ParamsGroups>
       <Group circuitScopeId="17159" editable="0" editableTitle="1" groupHeadIcon="" name="ROOTGROUP" origTitle="ROOTGROUP" subId="29">
        <Elements>
         <Element display="0" varName="k"/>
         <Element display="1" varName="out"/>
        </Elements>
       </Group>
      </ParamsGroups>
      <IntVars>
       <Vars>
        <Var defValue="0" dimension="1" maxValue="1e+30" minValue="-1e+30" saveValue="1" subId="28" title="constant value - Linked variable" type="10" units="null" value="0" varName="k0GEN" visibility="False">
         <LaData>
          <Data laStatus="0"/>
         </LaData>
        </Var>
       </Vars>
      </IntVars>
      <ExtVars>
       <Port tag="signal">
        <Vars>
         <Var dimension="1" io="2" saveValue="1" subId="24" title="output" type="0" units="null" varName="out" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
      </ExtVars>
     </Submodel>
    </Comp>
    <Comp alias="fofxyz_5" circuitScopeId="668" depth="206" displayName="fofxyz" geometry="1" iconDescription="defined by expression" labelVisible="0" libraryId="sig.fofxyz" name="fofxyz" scaleX="1.000000" scaleY="1.000000" type="0">
     <Pos x="424" y="156"/>
     <LabelPos configured="0" direction="0" x="0" y="0"/>
     <CirCompIcon cirIconIdentity="1" cirPortGraphics="IDxQT1JUUz4KICA8UE9SVCBmYWNlPSIxIiB0eXBlPSJzaWduYWwiIHg9IjE1IiB5PSI0OSI+CiAgIDxQT1JUX0JJVE1BUD4kQU1FL2xpYnBvcnRzL0ljb25zL3NpZ25hbDFweC5zdmc8L1BPUlRfQklUTUFQPgogIDwvUE9SVD4KICA8UE9SVCBmYWNlPSIzIiB0eXBlPSJzaWduYWwiIHg9IjYxIiB5PSIyNSI+CiAgIDxQT1JUX0JJVE1BUD4kQU1FL2xpYnBvcnRzL0ljb25zL3NpZ25hbDFweC5zdmc8L1BPUlRfQklUTUFQPgogIDwvUE9SVD4KICA8UE9SVCBmYWNlPSIwIiB0eXBlPSJzaWduYWwiIHg9IjE1IiB5PSIxIj4KICAgPFBPUlRfQklUTUFQPiRBTUUvbGlicG9ydHMvSWNvbnMvc2lnbmFsMXB4LnN2ZzwvUE9SVF9CSVRNQVA+CiAgPC9QT1JUPgogIDxQT1JUIGZhY2U9IjIiIHR5cGU9InNpZ25hbCIgeD0iMSIgeT0iMjUiPgogICA8UE9SVF9CSVRNQVA+JEFNRS9saWJwb3J0cy9JY29ucy9zaWduYWwxcHguc3ZnPC9QT1JUX0JJVE1BUD4KICA8L1BPUlQ+CiA8L1BPUlRTPgo=" cirPortHidden="0">
      <IconMap data="H4sIAAAAAAACCrVVTZOaMBi+7694J3twd0aBREBwjDvtoaceemjPDtWImY2JE1IBf33fIOv2wwN2LJckL8nzwfMCi5dmr+AobCWN5iMaRCMQem02Upd89O3rp0k2elk+LKpjCbhTV5zsnDvMw7Cu66CeBsaWIYuiKMQd5Lxl3iipX69tpHmeh91dcuEkNGAEvheV+GLNVirBiZO6JSA3nHyWR6GUWVGE5iQ6NATafqzlxu04Salf7IQsd46TOPeroxT1R+MPQAQphTgnYJBvq0zNSbW2RqlO67w6FGskPFhRCXsUBJ2WywcAWFixdp4zC5KOk0Z+gvoUJ4/b7iJQOWte8fxj1F1vhcleOmGVxMEfvGiN2btSlpHwzORE48DZQldbY/ec7AtnZfNEwaunwJAYZs/IbbSbbIu9VChn9MHKQo36aiVPqMJ7XzaL0AMOgqaITPPB0KcboDvVcRIkg9HbW4RPgeXDsGnqwbe3gOfABj1v6vtw+dSM2/Hp+Y1gEZa+ibruXf+o3CpeVbLUhSJncmx+0beRNloM76GGYj9jK+LAYt+LDeNkhgXWF/p2OhjV/jPJwUjt8B1nQTJmFGZ+QGzo1hmAJ/nL4fSODmlnrT179Q77As7yuzqk2dgb8/Dj3E9ot77ukN3RYZL+GWJKr6dYGn2Rm1DMA/UlSUDPkfjKrB+zIIMkDfL3OxF+VK85of8lK/+B/T2sOLpvWpjOJa5pl1d2rvwSmP8FLR9+Aq4eY5rSBgAA" format="svgz/base64"/>
     </CirCompIcon>
     <Ports>
      <Port connect="2" decorationOrientation="0" decorationVisible="0" face="1" name="" type="signal">
       <Pos x="15" y="49"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="7" port="1"/>
       </Connects>
      </Port>
      <Port connect="2" decorationOrientation="0" decorationVisible="0" face="3" name="" type="signal">
       <Pos x="61" y="25"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="12" port="0"/>
       </Connects>
      </Port>
      <Port connect="2" decorationOrientation="0" decorationVisible="0" face="0" name="" type="signal">
       <Pos x="15" y="1"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="9" port="1"/>
       </Connects>
      </Port>
      <Port connect="2" decorationOrientation="0" decorationVisible="0" face="2" name="" type="signal">
       <Pos x="1" y="25"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="3" port="1"/>
       </Connects>
      </Port>
     </Ports>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="0" codeGenVersion="2.0" dir="$AME/libsig/submodels" hasTerminate="1" iStoresNumber="1" idMax="11" idsReset="0" label="signal output as function of inputs x,y,z" name="FXYZ" outputType="1" type="0" unit="0">
      <IntParams>
       <Params>
        <Param defValue="1" maxValue="4" minValue="1" subId="8" title="output value" value="1" varName="outputtype" visibility="True">
         <Enums>
          <Enum string="f">
           <IconMap data="$AME/libsig/Icons/layers/FXYZ_outputtype_f.svg" format="path"/>
          </Enum>
          <Enum string="df/dx">
           <IconMap data="$AME/libsig/Icons/layers/FXYZ_outputtype_df_dx.svg" format="path"/>
          </Enum>
          <Enum string="df/dy">
           <IconMap data="$AME/libsig/Icons/layers/FXYZ_outputtype_df_dy.svg" format="path"/>
          </Enum>
          <Enum string="df/dz">
           <IconMap data="$AME/libsig/Icons/layers/FXYZ_outputtype_df_dz.svg" format="path"/>
          </Enum>
         </Enums>
        </Param>
        <Param defValue="2" maxValue="2" minValue="1" subId="10" title="discontinuity handling" value="2" varName="disc" visibility="True">
         <Enums>
          <Enum string="inactive"/>
          <Enum string="active"/>
         </Enums>
        </Param>
       </Params>
      </IntParams>
      <TextParams>
       <Params>
        <Param defValue="(y>=z)*(x+(y-z))" subId="5" textType="2" title="expression for output as a function of x, y and z" tokenList="x,y,z" value="(y>=z)*(x+(y-z))" varName="fstr" visibility="True"/>
       </Params>
      </TextParams>
      <ParamsGroups>
       <Group circuitScopeId="17167" editable="0" editableTitle="1" groupHeadIcon="" name="ROOTGROUP" origTitle="ROOTGROUP" subId="11">
        <Elements>
         <Element display="0" varName="outputtype"/>
         <Element display="0" varName="disc"/>
         <Element display="0" varName="fstr"/>
         <Element display="1" varName="y"/>
         <Element display="1" varName="output"/>
         <Element display="1" varName="x"/>
         <Element display="1" varName="z"/>
        </Elements>
       </Group>
      </ParamsGroups>
      <ExtVars>
       <Port tag="signal">
        <Vars>
         <Var dimension="1" io="1" saveValue="1" subId="1" title="input y" type="0" units="null" varName="y" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
       <Port tag="signal">
        <Vars>
         <Var dimension="1" io="2" origTitle="output from f(x,y,z)" saveValue="1" subId="2" title="force after run out" type="0" units="null" varName="output" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
       <Port tag="signal">
        <Vars>
         <Var dimension="1" io="1" saveValue="1" subId="3" title="input x" type="0" units="null" varName="x" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
       <Port tag="signal">
        <Vars>
         <Var dimension="1" io="1" saveValue="1" subId="4" title="input z" type="0" units="null" varName="z" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
      </ExtVars>
      <IconMap data="$AME/libsig/Icons/layers/FXYZ_frame.svg" format="path"/>
     </Submodel>
    </Comp>
    <Comp alias="splitter2p2_10" circuitScopeId="669" depth="207" displayName="splitter2p2" geometry="1" iconDescription="signal duplication (alternative)" labelVisible="0" libraryId="sig.splitter2p2" name="splitter2p2" scaleX="1.000000" scaleY="1.000000" type="0">
     <Pos x="265" y="269"/>
     <LabelPos configured="0" direction="0" x="0" y="0"/>
     <CirCompIcon cirIconIdentity="1" cirPortGraphics="IDxQT1JUUz4KICA8UE9SVCBmYWNlPSIzIiB0eXBlPSJzaWduYWwiIHg9IjMxIiB5PSIxNiI+CiAgIDxQT1JUX0JJVE1BUD4kQU1FL2xpYnBvcnRzL0ljb25zL3NpZ25hbDFweC5zdmc8L1BPUlRfQklUTUFQPgogIDwvUE9SVD4KICA8UE9SVCBmYWNlPSIwIiB0eXBlPSJzaWduYWwiIHg9IjE2IiB5PSIxIj4KICAgPFBPUlRfQklUTUFQPiRBTUUvbGlicG9ydHMvSWNvbnMvc2lnbmFsMXB4LnN2ZzwvUE9SVF9CSVRNQVA+CiAgPC9QT1JUPgogIDxQT1JUIGZhY2U9IjIiIHR5cGU9InNpZ25hbCIgeD0iMSIgeT0iMTYiPgogICA8UE9SVF9CSVRNQVA+JEFNRS9saWJwb3J0cy9JY29ucy9zaWduYWwxcHguc3ZnPC9QT1JUX0JJVE1BUD4KICA8L1BPUlQ+CiA8L1BPUlRTPgo=" cirPortHidden="0">
      <IconMap data="H4sIAAAAAAACCq1UPW/bMBDd8ysO7OBFoUgqaiTDcoAOnTp0aGfDkRmZCEMKpKqPf9+jPhwjcZdCgoDjPZ7u3bsjtXvq3zS00nllTbHhlG1AmtKelKmKze9f3++zzdP+bufbCjDS+IKcm6bexnHXdbRLqHVVLBhjMUaQKWTba2VebwXyPM/jcZdcOAmngsDz0cufzr4oLQvSKDMQUKeC/FCt1NoeOKYuCKt7AsNsO3VqzgVJeHDOUlXnZvFaJbtvNnwADBKOLwGLfC/adgXxpbNaj7VufX0skbB20kvXSoJKq/0dAOywSAlYji6IsUYS8I2zrxj7hY3PAty/qUY6rdCgFIR7jhYVDWgzmiIgEMgREBMQr0AgRMg8zFSBYUYmrpUp0kVGduFIVxIy5R57NXcqvcVRKldqCWW/BJTDsnLhBI2Bu7gK8xsPTvnHN4fk4FVljpqsUCj71IvPVdZWD/9NUltlGrxeCU0jLiALBnPD6OcANxWKFRW+j+Lh4yjYtcLKmkuxHA9JlEOIjB4oLrLJz2m2wAnlwPGOR//SwFfUIB4/jinc/VtzulYhRBSEgPhK+dT0gGSzRS0gHmn+voNqrrWEX9/+L7mnfsNJBQAA" format="svgz/base64"/>
     </CirCompIcon>
     <Ports>
      <Port connect="1" decorationOrientation="0" decorationVisible="0" face="3" name="" type="signal">
       <Pos x="31" y="16"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="3" port="3"/>
       </Connects>
      </Port>
      <Port connect="2" decorationOrientation="0" decorationVisible="0" face="0" name="" type="signal">
       <Pos x="16" y="1"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="6" port="0"/>
       </Connects>
      </Port>
      <Port connect="1" decorationOrientation="0" decorationVisible="0" face="2" name="" type="signal">
       <Pos x="1" y="16"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="4" port="0"/>
       </Connects>
      </Port>
     </Ports>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="0" codeGenVersion="2.0" dir="$AME/libsig/submodels" hasNoCalc="1" hasTerminate="1" idMax="4" idsReset="0" label="splitter junction" name="SPLT0" outputType="1" type="0" unit="0">
      <ParamsGroups>
       <Group circuitScopeId="17171" editable="0" editableTitle="1" groupHeadIcon="" name="ROOTGROUP" origTitle="ROOTGROUP" subId="4">
        <Elements>
         <Element display="1" varName="in3"/>
        </Elements>
       </Group>
      </ParamsGroups>
      <ExtVars>
       <Port tag="signal">
        <Vars>
         <Var dupType="0" primaryPort="2" primaryVar="0" saveValue="1" subId="1" title="input to junction" type="4" varName="out1" visibility="True"/>
        </Vars>
       </Port>
       <Port tag="signal">
        <Vars>
         <Var dupType="0" primaryPort="2" primaryVar="0" saveValue="1" subId="2" title="input to junction" type="4" varName="out2" visibility="True"/>
        </Vars>
       </Port>
       <Port tag="signal">
        <Vars>
         <Var dimension="1" io="1" saveValue="1" subId="3" title="input to junction" type="0" units="null" varName="in3" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
      </ExtVars>
     </Submodel>
    </Comp>
    <Comp alias="fofxyz_6" circuitScopeId="670" depth="208" displayName="fofxyz" geometry="1" iconDescription="defined by expression" labelVisible="0" libraryId="sig.fofxyz" name="fofxyz" scaleX="1.000000" scaleY="1.000000" type="0">
     <Pos x="328" y="156"/>
     <LabelPos configured="0" direction="0" x="0" y="0"/>
     <CirCompIcon cirIconIdentity="1" cirPortGraphics="IDxQT1JUUz4KICA8UE9SVCBmYWNlPSIxIiB0eXBlPSJzaWduYWwiIHg9IjE1IiB5PSI0OSI+CiAgIDxQT1JUX0JJVE1BUD4kQU1FL2xpYnBvcnRzL0ljb25zL3NpZ25hbDFweC5zdmc8L1BPUlRfQklUTUFQPgogIDwvUE9SVD4KICA8UE9SVCBmYWNlPSIzIiB0eXBlPSJzaWduYWwiIHg9IjYxIiB5PSIyNSI+CiAgIDxQT1JUX0JJVE1BUD4kQU1FL2xpYnBvcnRzL0ljb25zL3NpZ25hbDFweC5zdmc8L1BPUlRfQklUTUFQPgogIDwvUE9SVD4KICA8UE9SVCBmYWNlPSIwIiB0eXBlPSJzaWduYWwiIHg9IjE1IiB5PSIxIj4KICAgPFBPUlRfQklUTUFQPiRBTUUvbGlicG9ydHMvSWNvbnMvc2lnbmFsMXB4LnN2ZzwvUE9SVF9CSVRNQVA+CiAgPC9QT1JUPgogIDxQT1JUIGZhY2U9IjIiIHR5cGU9InNpZ25hbCIgeD0iMSIgeT0iMjUiPgogICA8UE9SVF9CSVRNQVA+JEFNRS9saWJwb3J0cy9JY29ucy9zaWduYWwxcHguc3ZnPC9QT1JUX0JJVE1BUD4KICA8L1BPUlQ+CiA8L1BPUlRTPgo=" cirPortHidden="0">
      <IconMap data="H4sIAAAAAAACCrVVTZOaMBi+7694J3twd0aBREBwjDvtoaceemjPDtWImY2JE1IBf33fIOv2wwN2LJckL8nzwfMCi5dmr+AobCWN5iMaRCMQem02Upd89O3rp0k2elk+LKpjCbhTV5zsnDvMw7Cu66CeBsaWIYuiKMQd5Lxl3iipX69tpHmeh91dcuEkNGAEvheV+GLNVirBiZO6JSA3nHyWR6GUWVGE5iQ6NATafqzlxu04Salf7IQsd46TOPeroxT1R+MPQAQphTgnYJBvq0zNSbW2RqlO67w6FGskPFhRCXsUBJ2WywcAWFixdp4zC5KOk0Z+gvoUJ4/b7iJQOWte8fxj1F1vhcleOmGVxMEfvGiN2btSlpHwzORE48DZQldbY/ec7AtnZfNEwaunwJAYZs/IbbSbbIu9VChn9MHKQo36aiVPqMJ7XzaL0AMOgqaITPPB0KcboDvVcRIkg9HbW4RPgeXDsGnqwbe3gOfABj1v6vtw+dSM2/Hp+Y1gEZa+ibruXf+o3CpeVbLUhSJncmx+0beRNloM76GGYj9jK+LAYt+LDeNkhgXWF/p2OhjV/jPJwUjt8B1nQTJmFGZ+QGzo1hmAJ/nL4fSODmlnrT179Q77As7yuzqk2dgb8/Dj3E9ot77ukN3RYZL+GWJKr6dYGn2Rm1DMA/UlSUDPkfjKrB+zIIMkDfL3OxF+VK85of8lK/+B/T2sOLpvWpjOJa5pl1d2rvwSmP8FLR9+Aq4eY5rSBgAA" format="svgz/base64"/>
     </CirCompIcon>
     <Ports>
      <Port connect="2" decorationOrientation="0" decorationVisible="0" face="1" name="" type="signal">
       <Pos x="15" y="49"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="6" port="1"/>
       </Connects>
      </Port>
      <Port connect="2" decorationOrientation="0" decorationVisible="0" face="3" name="" type="signal">
       <Pos x="61" y="25"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="3" port="0"/>
       </Connects>
      </Port>
      <Port connect="2" decorationOrientation="0" decorationVisible="0" face="0" name="" type="signal">
       <Pos x="15" y="1"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="4" port="1"/>
       </Connects>
      </Port>
      <Port connect="2" decorationOrientation="0" decorationVisible="0" face="2" name="" type="signal">
       <Pos x="1" y="25"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="5" port="1"/>
       </Connects>
      </Port>
     </Ports>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="0" codeGenVersion="2.0" dir="$AME/libsig/submodels" hasTerminate="1" iStoresNumber="1" idMax="11" idsReset="0" label="signal output as function of inputs x,y,z" name="FXYZ" outputType="1" type="0" unit="0">
      <IntParams>
       <Params>
        <Param defValue="1" maxValue="4" minValue="1" subId="8" title="output value" value="1" varName="outputtype" visibility="True">
         <Enums>
          <Enum string="f">
           <IconMap data="$AME/libsig/Icons/layers/FXYZ_outputtype_f.svg" format="path"/>
          </Enum>
          <Enum string="df/dx">
           <IconMap data="$AME/libsig/Icons/layers/FXYZ_outputtype_df_dx.svg" format="path"/>
          </Enum>
          <Enum string="df/dy">
           <IconMap data="$AME/libsig/Icons/layers/FXYZ_outputtype_df_dy.svg" format="path"/>
          </Enum>
          <Enum string="df/dz">
           <IconMap data="$AME/libsig/Icons/layers/FXYZ_outputtype_df_dz.svg" format="path"/>
          </Enum>
         </Enums>
        </Param>
        <Param defValue="2" maxValue="2" minValue="1" subId="10" title="discontinuity handling" value="2" varName="disc" visibility="True">
         <Enums>
          <Enum string="inactive"/>
          <Enum string="active"/>
         </Enums>
        </Param>
       </Params>
      </IntParams>
      <TextParams>
       <Params>
        <Param defValue="x/y+z" subId="5" textType="2" title="expression for output as a function of x, y and z" tokenList="x,y,z" value="x/y+z" varName="fstr" visibility="True"/>
       </Params>
      </TextParams>
      <ParamsGroups>
       <Group circuitScopeId="17179" editable="0" editableTitle="1" groupHeadIcon="" name="ROOTGROUP" origTitle="ROOTGROUP" subId="11">
        <Elements>
         <Element display="0" varName="outputtype"/>
         <Element display="0" varName="disc"/>
         <Element display="0" varName="fstr"/>
         <Element display="1" varName="y"/>
         <Element display="1" varName="output"/>
         <Element display="1" varName="x"/>
         <Element display="1" varName="z"/>
        </Elements>
       </Group>
      </ParamsGroups>
      <ExtVars>
       <Port tag="signal">
        <Vars>
         <Var dimension="1" io="1" saveValue="1" subId="1" title="input y" type="0" units="null" varName="y" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
       <Port tag="signal">
        <Vars>
         <Var dimension="1" io="2" saveValue="1" subId="2" title="output from f(x,y,z)" type="0" units="null" varName="output" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
       <Port tag="signal">
        <Vars>
         <Var dimension="1" io="1" saveValue="1" subId="3" title="input x" type="0" units="null" varName="x" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
       <Port tag="signal">
        <Vars>
         <Var dimension="1" io="1" saveValue="1" subId="4" title="input z" type="0" units="null" varName="z" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
      </ExtVars>
      <IconMap data="$AME/libsig/Icons/layers/FXYZ_frame.svg" format="path"/>
     </Submodel>
    </Comp>
    <Comp alias="constant_7" circuitScopeId="671" depth="209" displayName="constant" geometry="1" iconDescription="constant signal source" labelVisible="0" libraryId="sig.constant" name="constant" scaleX="1.000000" scaleY="1.000000" type="0">
     <Pos x="225" y="202"/>
     <LabelPos configured="0" direction="0" x="0" y="0"/>
     <CirCompIcon cirIconIdentity="1" cirPortGraphics="IDxQT1JUUz4KICA8UE9SVCBmYWNlPSIzIiB0eXBlPSJzaWduYWwiIHg9IjQwIiB5PSIxNSI+CiAgIDxQT1JUX0JJVE1BUD4kQU1FL2xpYnBvcnRzL0ljb25zL3NpZ25hbDFweC5zdmc8L1BPUlRfQklUTUFQPgogIDwvUE9SVD4KIDwvUE9SVFM+Cg==" cirPortHidden="0">
      <IconMap data="H4sIAAAAAAACCo1SwY7bIBC95ytGswe30gYbO6vaUchqe+iphx7ac+Q62EHBYAFrO/36Do7TXnooQprh8XgzDzi8zr2GUTqvrBEJZ1kC0jT2rEwnkh/fv2zL5PW4OfixA2IaL/ASwrBP02ma2FQw67o0z7IsJQbeKftZK3P9F5FXVZUuu/inJnKWI/ysvfzmbKu0FBiUuSGos8CvapRa2xMnaYHZMCPc1jipc7gI3C2Li1TdJQjMq7galZw+23gAMthlkFcIluq12k4CfeOs1kuvez/UDRUcnPTSjRLJaXfcAMChUa7REqghLfCpXQaCD85e6cBTtowHsO1VkE4rCuSH4IaK8x17oez2yFxMML3LBzkHCK42vrWuF9jXwan5A4fYMgdOs2R5seMfEVprwrate6VJK3lzqtbJinr1S0ZZcn28HtKoShbSLvpYLrB59+HET151ptZ4r033/zBmrJH/72rmAouCnoA/PM15fAFC8hVZ7Q1W3zprYLDKBPozefnMOXuBImf8ORIhIp/WWLISioJVf3cylgNEsbuX+LmOm9+vXzT5rAIAAA==" format="svgz/base64"/>
     </CirCompIcon>
     <Ports>
      <Port connect="1" decorationOrientation="0" decorationVisible="0" face="3" name="" type="signal">
       <Pos x="40" y="15"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="10" port="2"/>
       </Connects>
      </Port>
     </Ports>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="0" codeGenVersion="2.0" dir="$AME/libsig/submodels" discontinuity="1" hasTerminate="1" idMax="29" idsReset="0" label="constant signal" name="CONS00" outputType="1" type="0" unit="1">
      <RealParams>
       <Params>
        <Param defValue="10" historyVariable="k0GEN" maxValue="1e+30" minValue="-1e+30" subId="3" title="constant value" tunable="True" units="null" value="10" varName="k" visibility="True"/>
       </Params>
      </RealParams>
      <ParamsGroups>
       <Group circuitScopeId="17183" editable="0" editableTitle="1" groupHeadIcon="" name="ROOTGROUP" origTitle="ROOTGROUP" subId="29">
        <Elements>
         <Element display="0" varName="k"/>
         <Element display="1" varName="out"/>
        </Elements>
       </Group>
      </ParamsGroups>
      <IntVars>
       <Vars>
        <Var defValue="0" dimension="1" maxValue="1e+30" minValue="-1e+30" saveValue="1" subId="28" title="constant value - Linked variable" type="10" units="null" value="0" varName="k0GEN" visibility="False">
         <LaData>
          <Data laStatus="0"/>
         </LaData>
        </Var>
       </Vars>
      </IntVars>
      <ExtVars>
       <Port tag="signal">
        <Vars>
         <Var dimension="1" io="2" saveValue="1" subId="24" title="output" type="0" units="null" varName="out" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
      </ExtVars>
     </Submodel>
    </Comp>
    <Comp alias="constant_8" circuitScopeId="1071" depth="210" displayName="constant" geometry="1" iconDescription="constant signal source" labelVisible="0" libraryId="sig.constant" name="constant" scaleX="1.000000" scaleY="1.000000" type="0">
     <Pos x="225" y="133"/>
     <LabelPos configured="0" direction="0" x="0" y="0"/>
     <CirCompIcon cirIconIdentity="1" cirPortGraphics="IDxQT1JUUz4KICA8UE9SVCBmYWNlPSIzIiB0eXBlPSJzaWduYWwiIHg9IjQwIiB5PSIxNSI+CiAgIDxQT1JUX0JJVE1BUD4kQU1FL2xpYnBvcnRzL0ljb25zL3NpZ25hbDFweC5zdmc8L1BPUlRfQklUTUFQPgogIDwvUE9SVD4KIDwvUE9SVFM+Cg==" cirPortHidden="0">
      <IconMap data="H4sIAAAAAAACCo1SwY7bIBC95ytGswe30gYbO6vaUchqe+iphx7ac+Q62EHBYAFrO/36Do7TXnooQprh8XgzDzi8zr2GUTqvrBEJZ1kC0jT2rEwnkh/fv2zL5PW4OfixA2IaL/ASwrBP02ma2FQw67o0z7IsJQbeKftZK3P9F5FXVZUuu/inJnKWI/ysvfzmbKu0FBiUuSGos8CvapRa2xMnaYHZMCPc1jipc7gI3C2Li1TdJQjMq7galZw+23gAMthlkFcIluq12k4CfeOs1kuvez/UDRUcnPTSjRLJaXfcAMChUa7REqghLfCpXQaCD85e6cBTtowHsO1VkE4rCuSH4IaK8x17oez2yFxMML3LBzkHCK42vrWuF9jXwan5A4fYMgdOs2R5seMfEVprwrate6VJK3lzqtbJinr1S0ZZcn28HtKoShbSLvpYLrB59+HET151ptZ4r033/zBmrJH/72rmAouCnoA/PM15fAFC8hVZ7Q1W3zprYLDKBPozefnMOXuBImf8ORIhIp/WWLISioJVf3cylgNEsbuX+LmOm9+vXzT5rAIAAA==" format="svgz/base64"/>
     </CirCompIcon>
     <Ports>
      <Port connect="1" decorationOrientation="0" decorationVisible="0" face="3" name="" type="signal">
       <Pos x="40" y="15"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="11" port="2"/>
       </Connects>
      </Port>
     </Ports>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="0" codeGenVersion="2.0" dir="$AME/libsig/submodels" discontinuity="1" hasTerminate="1" idMax="29" idsReset="0" label="constant signal" name="CONS00" outputType="1" type="0" unit="1">
      <RealParams>
       <Params>
        <Param defValue="2500" historyVariable="k0GEN" maxValue="1e+30" minValue="-1e+30" subId="3" title="constant value" tunable="True" units="null" value="2500" varName="k" visibility="True"/>
       </Params>
      </RealParams>
      <ParamsGroups>
       <Group circuitScopeId="17187" editable="0" editableTitle="1" groupHeadIcon="" name="ROOTGROUP" origTitle="ROOTGROUP" subId="29">
        <Elements>
         <Element display="0" varName="k"/>
         <Element display="1" varName="out"/>
        </Elements>
       </Group>
      </ParamsGroups>
      <IntVars>
       <Vars>
        <Var defValue="0" dimension="1" maxValue="1e+30" minValue="-1e+30" saveValue="1" subId="28" title="constant value - Linked variable" type="10" units="null" value="0" varName="k0GEN" visibility="False">
         <LaData>
          <Data laStatus="0"/>
         </LaData>
        </Var>
       </Vars>
      </IntVars>
      <ExtVars>
       <Port tag="signal">
        <Vars>
         <Var dimension="1" io="2" saveValue="1" subId="24" title="output" type="0" units="null" varName="out" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
      </ExtVars>
     </Submodel>
    </Comp>
    <Comp alias="splitter2p2_11" circuitScopeId="673" depth="211" displayName="splitter2p2" geometry="7" iconDescription="signal duplication (alternative)" labelVisible="0" libraryId="sig.splitter2p2" name="splitter2p2" scaleX="1.000000" scaleY="1.000000" type="0">
     <Pos x="265" y="201"/>
     <LabelPos configured="0" direction="0" x="0" y="0"/>
     <CirCompIcon cirIconIdentity="1" cirPortGraphics="IDxQT1JUUz4KICA8UE9SVCBmYWNlPSIzIiB0eXBlPSJzaWduYWwiIHg9IjMxIiB5PSIxNiI+CiAgIDxQT1JUX0JJVE1BUD4kQU1FL2xpYnBvcnRzL0ljb25zL3NpZ25hbDFweC5zdmc8L1BPUlRfQklUTUFQPgogIDwvUE9SVD4KICA8UE9SVCBmYWNlPSIxIiB0eXBlPSJzaWduYWwiIHg9IjE2IiB5PSIzMSI+CiAgIDxQT1JUX0JJVE1BUD4kQU1FL2xpYnBvcnRzL0ljb25zL3NpZ25hbDFweC5zdmc8L1BPUlRfQklUTUFQPgogIDwvUE9SVD4KICA8UE9SVCBmYWNlPSIyIiB0eXBlPSJzaWduYWwiIHg9IjEiIHk9IjE2Ij4KICAgPFBPUlRfQklUTUFQPiRBTUUvbGlicG9ydHMvSWNvbnMvc2lnbmFsMXB4LnN2ZzwvUE9SVF9CSVRNQVA+CiAgPC9QT1JUPgogPC9QT1JUUz4K" cirPortHidden="0">
      <IconMap data="H4sIAAAAAAACCq1UPW/bMBDd8ysO7OBFoUgqaiTDcoAOnTp0aGfDkRmZCEMKpKqPf9+jPhwjcZdCgoDjPZ7u3bsjtXvq3zS00nllTbHhlG1AmtKelKmKze9f3++zzdP+bufbCjDS+IKcm6bexnHXdbRLqHVVLBhjMUaQKWTba2VebwXyPM/jcZdcOAmngsDz0cufzr4oLQvSKDMQUKeC/FCt1NoeOKYuCKt7AsNsO3VqzgVJeHDOUlXnZvFaJbtvNnwADBKOLwGLfC/adgXxpbNaj7VufX0skbB20kvXSoJKq/0dAOywSAlYji6IsUYS8I2zrxj7hY3PAty/qUY6rdCgFIR7jhYVDWgzmiIgEMgREBMQr0AgRMg8zFSBYUYmrpUp0kVGduFIVxIy5R57NXcqvcVRKldqCWW/BJTDsnLhBI2Bu7gK8xsPTvnHN4fk4FVljpqsUCj71IvPVdZWD/9NUltlGrxeCU0jLiALBnPD6OcANxWKFRW+j+Lh4yjYtcLKmkuxHA9JlEOIjB4oLrLJz2m2wAnlwPGOR//SwFfUIB4/jinc/VtzulYhRBSEgPhK+dT0gGSzRS0gHmn+voNqrrWEX9/+L7mnfsNJBQAA" format="svgz/base64"/>
     </CirCompIcon>
     <Ports>
      <Port connect="2" decorationOrientation="0" decorationVisible="0" face="3" name="" type="signal">
       <Pos x="31" y="16"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="5" port="0"/>
       </Connects>
      </Port>
      <Port connect="2" decorationOrientation="0" decorationVisible="0" face="1" name="" type="signal">
       <Pos x="16" y="31"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="8" port="0"/>
       </Connects>
      </Port>
      <Port connect="1" decorationOrientation="0" decorationVisible="0" face="2" name="" type="signal">
       <Pos x="1" y="16"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="8" port="0"/>
       </Connects>
      </Port>
     </Ports>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="0" codeGenVersion="2.0" dir="$AME/libsig/submodels" hasNoCalc="1" hasTerminate="1" idMax="4" idsReset="0" label="splitter junction" name="SPLT0" outputType="1" type="0" unit="0">
      <ParamsGroups>
       <Group circuitScopeId="17191" editable="0" editableTitle="1" groupHeadIcon="" name="ROOTGROUP" origTitle="ROOTGROUP" subId="4">
        <Elements>
         <Element display="1" varName="in3"/>
        </Elements>
       </Group>
      </ParamsGroups>
      <ExtVars>
       <Port tag="signal">
        <Vars>
         <Var dupType="0" primaryPort="2" primaryVar="0" saveValue="1" subId="1" title="input to junction" type="4" varName="out1" visibility="True"/>
        </Vars>
       </Port>
       <Port tag="signal">
        <Vars>
         <Var dupType="0" primaryPort="2" primaryVar="0" saveValue="1" subId="2" title="input to junction" type="4" varName="out2" visibility="True"/>
        </Vars>
       </Port>
       <Port tag="signal">
        <Vars>
         <Var dimension="1" io="1" saveValue="1" subId="3" title="input to junction" type="0" units="null" varName="in3" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
      </ExtVars>
     </Submodel>
    </Comp>
    <Comp alias="splitter2p2_12" circuitScopeId="674" depth="212" displayName="splitter2p2" geometry="1" iconDescription="signal duplication (alternative)" labelVisible="0" libraryId="sig.splitter2p2" name="splitter2p2" scaleX="1.000000" scaleY="1.000000" type="0">
     <Pos x="265" y="132"/>
     <LabelPos configured="0" direction="0" x="0" y="0"/>
     <CirCompIcon cirIconIdentity="1" cirPortGraphics="IDxQT1JUUz4KICA8UE9SVCBmYWNlPSIzIiB0eXBlPSJzaWduYWwiIHg9IjMxIiB5PSIxNiI+CiAgIDxQT1JUX0JJVE1BUD4kQU1FL2xpYnBvcnRzL0ljb25zL3NpZ25hbDFweC5zdmc8L1BPUlRfQklUTUFQPgogIDwvUE9SVD4KICA8UE9SVCBmYWNlPSIwIiB0eXBlPSJzaWduYWwiIHg9IjE2IiB5PSIxIj4KICAgPFBPUlRfQklUTUFQPiRBTUUvbGlicG9ydHMvSWNvbnMvc2lnbmFsMXB4LnN2ZzwvUE9SVF9CSVRNQVA+CiAgPC9QT1JUPgogIDxQT1JUIGZhY2U9IjIiIHR5cGU9InNpZ25hbCIgeD0iMSIgeT0iMTYiPgogICA8UE9SVF9CSVRNQVA+JEFNRS9saWJwb3J0cy9JY29ucy9zaWduYWwxcHguc3ZnPC9QT1JUX0JJVE1BUD4KICA8L1BPUlQ+CiA8L1BPUlRTPgo=" cirPortHidden="0">
      <IconMap data="H4sIAAAAAAACCq1UPW/bMBDd8ysO7OBFoUgqaiTDcoAOnTp0aGfDkRmZCEMKpKqPf9+jPhwjcZdCgoDjPZ7u3bsjtXvq3zS00nllTbHhlG1AmtKelKmKze9f3++zzdP+bufbCjDS+IKcm6bexnHXdbRLqHVVLBhjMUaQKWTba2VebwXyPM/jcZdcOAmngsDz0cufzr4oLQvSKDMQUKeC/FCt1NoeOKYuCKt7AsNsO3VqzgVJeHDOUlXnZvFaJbtvNnwADBKOLwGLfC/adgXxpbNaj7VufX0skbB20kvXSoJKq/0dAOywSAlYji6IsUYS8I2zrxj7hY3PAty/qUY6rdCgFIR7jhYVDWgzmiIgEMgREBMQr0AgRMg8zFSBYUYmrpUp0kVGduFIVxIy5R57NXcqvcVRKldqCWW/BJTDsnLhBI2Bu7gK8xsPTvnHN4fk4FVljpqsUCj71IvPVdZWD/9NUltlGrxeCU0jLiALBnPD6OcANxWKFRW+j+Lh4yjYtcLKmkuxHA9JlEOIjB4oLrLJz2m2wAnlwPGOR//SwFfUIB4/jinc/VtzulYhRBSEgPhK+dT0gGSzRS0gHmn+voNqrrWEX9/+L7mnfsNJBQAA" format="svgz/base64"/>
     </CirCompIcon>
     <Ports>
      <Port connect="2" decorationOrientation="0" decorationVisible="0" face="3" name="" type="signal">
       <Pos x="31" y="16"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="4" port="0"/>
       </Connects>
      </Port>
      <Port connect="2" decorationOrientation="0" decorationVisible="0" face="0" name="" type="signal">
       <Pos x="16" y="1"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="10" port="0"/>
       </Connects>
      </Port>
      <Port connect="1" decorationOrientation="0" decorationVisible="0" face="2" name="" type="signal">
       <Pos x="1" y="16"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="9" port="0"/>
       </Connects>
      </Port>
     </Ports>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="0" codeGenVersion="2.0" dir="$AME/libsig/submodels" hasNoCalc="1" hasTerminate="1" idMax="4" idsReset="0" label="splitter junction" name="SPLT0" outputType="1" type="0" unit="0">
      <ParamsGroups>
       <Group circuitScopeId="17195" editable="0" editableTitle="1" groupHeadIcon="" name="ROOTGROUP" origTitle="ROOTGROUP" subId="4">
        <Elements>
         <Element display="1" varName="in3"/>
        </Elements>
       </Group>
      </ParamsGroups>
      <ExtVars>
       <Port tag="signal">
        <Vars>
         <Var dupType="0" primaryPort="2" primaryVar="0" saveValue="1" subId="1" title="input to junction" type="4" varName="out1" visibility="True"/>
        </Vars>
       </Port>
       <Port tag="signal">
        <Vars>
         <Var dupType="0" primaryPort="2" primaryVar="0" saveValue="1" subId="2" title="input to junction" type="4" varName="out2" visibility="True"/>
        </Vars>
       </Port>
       <Port tag="signal">
        <Vars>
         <Var dimension="1" io="1" saveValue="1" subId="3" title="input to junction" type="0" units="null" varName="in3" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
      </ExtVars>
     </Submodel>
    </Comp>
    <Comp alias="fofxyz_7" circuitScopeId="675" depth="213" displayName="fofxyz" geometry="1" iconDescription="defined by expression" labelVisible="0" libraryId="sig.fofxyz" name="fofxyz" scaleX="1.000000" scaleY="1.000000" type="0">
     <Pos x="484" y="217"/>
     <LabelPos configured="0" direction="0" x="0" y="0"/>
     <CirCompIcon cirIconIdentity="1" cirPortGraphics="IDxQT1JUUz4KICA8UE9SVCBmYWNlPSIxIiB0eXBlPSJzaWduYWwiIHg9IjE1IiB5PSI0OSI+CiAgIDxQT1JUX0JJVE1BUD4kQU1FL2xpYnBvcnRzL0ljb25zL3NpZ25hbDFweC5zdmc8L1BPUlRfQklUTUFQPgogIDwvUE9SVD4KICA8UE9SVCBmYWNlPSIzIiB0eXBlPSJzaWduYWwiIHg9IjYxIiB5PSIyNSI+CiAgIDxQT1JUX0JJVE1BUD4kQU1FL2xpYnBvcnRzL0ljb25zL3NpZ25hbDFweC5zdmc8L1BPUlRfQklUTUFQPgogIDwvUE9SVD4KICA8UE9SVCBmYWNlPSIwIiB0eXBlPSJzaWduYWwiIHg9IjE1IiB5PSIxIj4KICAgPFBPUlRfQklUTUFQPiRBTUUvbGlicG9ydHMvSWNvbnMvc2lnbmFsMXB4LnN2ZzwvUE9SVF9CSVRNQVA+CiAgPC9QT1JUPgogIDxQT1JUIGZhY2U9IjIiIHR5cGU9InNpZ25hbCIgeD0iMSIgeT0iMjUiPgogICA8UE9SVF9CSVRNQVA+JEFNRS9saWJwb3J0cy9JY29ucy9zaWduYWwxcHguc3ZnPC9QT1JUX0JJVE1BUD4KICA8L1BPUlQ+CiA8L1BPUlRTPgo=" cirPortHidden="0">
      <IconMap data="H4sIAAAAAAACCrVVTZOaMBi+7694J3twd0aBREBwjDvtoaceemjPDtWImY2JE1IBf33fIOv2wwN2LJckL8nzwfMCi5dmr+AobCWN5iMaRCMQem02Upd89O3rp0k2elk+LKpjCbhTV5zsnDvMw7Cu66CeBsaWIYuiKMQd5Lxl3iipX69tpHmeh91dcuEkNGAEvheV+GLNVirBiZO6JSA3nHyWR6GUWVGE5iQ6NATafqzlxu04Salf7IQsd46TOPeroxT1R+MPQAQphTgnYJBvq0zNSbW2RqlO67w6FGskPFhRCXsUBJ2WywcAWFixdp4zC5KOk0Z+gvoUJ4/b7iJQOWte8fxj1F1vhcleOmGVxMEfvGiN2btSlpHwzORE48DZQldbY/ec7AtnZfNEwaunwJAYZs/IbbSbbIu9VChn9MHKQo36aiVPqMJ7XzaL0AMOgqaITPPB0KcboDvVcRIkg9HbW4RPgeXDsGnqwbe3gOfABj1v6vtw+dSM2/Hp+Y1gEZa+ibruXf+o3CpeVbLUhSJncmx+0beRNloM76GGYj9jK+LAYt+LDeNkhgXWF/p2OhjV/jPJwUjt8B1nQTJmFGZ+QGzo1hmAJ/nL4fSODmlnrT179Q77As7yuzqk2dgb8/Dj3E9ot77ukN3RYZL+GWJKr6dYGn2Rm1DMA/UlSUDPkfjKrB+zIIMkDfL3OxF+VK85of8lK/+B/T2sOLpvWpjOJa5pl1d2rvwSmP8FLR9+Aq4eY5rSBgAA" format="svgz/base64"/>
     </CirCompIcon>
     <Ports>
      <Port connect="2" decorationOrientation="0" decorationVisible="0" face="1" name="" type="signal">
       <Pos x="15" y="49"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="13" port="1"/>
       </Connects>
      </Port>
      <Port connect="2" decorationOrientation="0" decorationVisible="0" face="3" name="" type="signal">
       <Pos x="61" y="25"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="14" port="0"/>
       </Connects>
      </Port>
      <Port connect="2" decorationOrientation="0" decorationVisible="0" face="0" name="" type="signal">
       <Pos x="15" y="1"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="12" port="1"/>
       </Connects>
      </Port>
      <Port connect="2" decorationOrientation="0" decorationVisible="0" face="2" name="" type="signal">
       <Pos x="1" y="25"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="11" port="1"/>
       </Connects>
      </Port>
     </Ports>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="0" codeGenVersion="2.0" dir="$AME/libsig/submodels" hasTerminate="1" iStoresNumber="1" idMax="11" idsReset="0" label="signal output as function of inputs x,y,z" name="FXYZ" outputType="1" type="0" unit="0">
      <IntParams>
       <Params>
        <Param defValue="1" maxValue="4" minValue="1" subId="8" title="output value" value="1" varName="outputtype" visibility="True">
         <Enums>
          <Enum string="f">
           <IconMap data="$AME/libsig/Icons/layers/FXYZ_outputtype_f.svg" format="path"/>
          </Enum>
          <Enum string="df/dx">
           <IconMap data="$AME/libsig/Icons/layers/FXYZ_outputtype_df_dx.svg" format="path"/>
          </Enum>
          <Enum string="df/dy">
           <IconMap data="$AME/libsig/Icons/layers/FXYZ_outputtype_df_dy.svg" format="path"/>
          </Enum>
          <Enum string="df/dz">
           <IconMap data="$AME/libsig/Icons/layers/FXYZ_outputtype_df_dz.svg" format="path"/>
          </Enum>
         </Enums>
        </Param>
        <Param defValue="2" maxValue="2" minValue="1" subId="10" title="discontinuity handling" value="2" varName="disc" visibility="True">
         <Enums>
          <Enum string="inactive"/>
          <Enum string="active"/>
         </Enums>
        </Param>
       </Params>
      </IntParams>
      <TextParams>
       <Params>
        <Param defValue="(y>=z)*x+(y&lt;z)*y" subId="5" textType="2" title="expression for output as a function of x, y and z" tokenList="x,y,z" value="(y>=z)*x+(y&lt;z)*y" varName="fstr" visibility="True"/>
       </Params>
      </TextParams>
      <ParamsGroups>
       <Group circuitScopeId="17203" editable="0" editableTitle="1" groupHeadIcon="" name="ROOTGROUP" origTitle="ROOTGROUP" subId="11">
        <Elements>
         <Element display="0" varName="outputtype"/>
         <Element display="0" varName="disc"/>
         <Element display="0" varName="fstr"/>
         <Element display="1" varName="y"/>
         <Element display="1" varName="output"/>
         <Element display="1" varName="x"/>
         <Element display="1" varName="z"/>
        </Elements>
       </Group>
      </ParamsGroups>
      <ExtVars>
       <Port tag="signal">
        <Vars>
         <Var dimension="1" io="1" saveValue="1" subId="1" title="input y" type="0" units="null" varName="y" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
       <Port tag="signal">
        <Vars>
         <Var dimension="1" io="2" origTitle="output from f(x,y,z)" saveValue="1" subId="2" title="applied force" type="0" units="null" varName="output" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
       <Port tag="signal">
        <Vars>
         <Var dimension="1" io="1" saveValue="1" subId="3" title="input x" type="0" units="null" varName="x" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
       <Port tag="signal">
        <Vars>
         <Var dimension="1" io="1" saveValue="1" subId="4" title="input z" type="0" units="null" varName="z" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
      </ExtVars>
      <IconMap data="$AME/libsig/Icons/layers/FXYZ_frame.svg" format="path"/>
     </Submodel>
    </Comp>
    <Comp alias="splitter2p2_13" circuitScopeId="676" depth="214" displayName="splitter2p2" geometry="7" iconDescription="signal duplication (alternative)" labelVisible="0" libraryId="sig.splitter2p2" name="splitter2p2" scaleX="1.000000" scaleY="1.000000" type="0">
     <Pos x="384" y="110"/>
     <LabelPos configured="0" direction="0" x="0" y="0"/>
     <CirCompIcon cirIconIdentity="1" cirPortGraphics="IDxQT1JUUz4KICA8UE9SVCBmYWNlPSIzIiB0eXBlPSJzaWduYWwiIHg9IjMxIiB5PSIxNiI+CiAgIDxQT1JUX0JJVE1BUD4kQU1FL2xpYnBvcnRzL0ljb25zL3NpZ25hbDFweC5zdmc8L1BPUlRfQklUTUFQPgogIDwvUE9SVD4KICA8UE9SVCBmYWNlPSIxIiB0eXBlPSJzaWduYWwiIHg9IjE2IiB5PSIzMSI+CiAgIDxQT1JUX0JJVE1BUD4kQU1FL2xpYnBvcnRzL0ljb25zL3NpZ25hbDFweC5zdmc8L1BPUlRfQklUTUFQPgogIDwvUE9SVD4KICA8UE9SVCBmYWNlPSIyIiB0eXBlPSJzaWduYWwiIHg9IjEiIHk9IjE2Ij4KICAgPFBPUlRfQklUTUFQPiRBTUUvbGlicG9ydHMvSWNvbnMvc2lnbmFsMXB4LnN2ZzwvUE9SVF9CSVRNQVA+CiAgPC9QT1JUPgogPC9QT1JUUz4K" cirPortHidden="0">
      <IconMap data="H4sIAAAAAAACCq1UPW/bMBDd8ysO7OBFoUgqaiTDcoAOnTp0aGfDkRmZCEMKpKqPf9+jPhwjcZdCgoDjPZ7u3bsjtXvq3zS00nllTbHhlG1AmtKelKmKze9f3++zzdP+bufbCjDS+IKcm6bexnHXdbRLqHVVLBhjMUaQKWTba2VebwXyPM/jcZdcOAmngsDz0cufzr4oLQvSKDMQUKeC/FCt1NoeOKYuCKt7AsNsO3VqzgVJeHDOUlXnZvFaJbtvNnwADBKOLwGLfC/adgXxpbNaj7VufX0skbB20kvXSoJKq/0dAOywSAlYji6IsUYS8I2zrxj7hY3PAty/qUY6rdCgFIR7jhYVDWgzmiIgEMgREBMQr0AgRMg8zFSBYUYmrpUp0kVGduFIVxIy5R57NXcqvcVRKldqCWW/BJTDsnLhBI2Bu7gK8xsPTvnHN4fk4FVljpqsUCj71IvPVdZWD/9NUltlGrxeCU0jLiALBnPD6OcANxWKFRW+j+Lh4yjYtcLKmkuxHA9JlEOIjB4oLrLJz2m2wAnlwPGOR//SwFfUIB4/jinc/VtzulYhRBSEgPhK+dT0gGSzRS0gHmn+voNqrrWEX9/+L7mnfsNJBQAA" format="svgz/base64"/>
     </CirCompIcon>
     <Ports>
      <Port connect="2" decorationOrientation="0" decorationVisible="0" face="3" name="" type="signal">
       <Pos x="31" y="16"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="9" port="0"/>
       </Connects>
      </Port>
      <Port connect="2" decorationOrientation="0" decorationVisible="0" face="1" name="" type="signal">
       <Pos x="16" y="31"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="11" port="0"/>
       </Connects>
      </Port>
      <Port connect="2" decorationOrientation="0" decorationVisible="0" face="2" name="" type="signal">
       <Pos x="1" y="16"/>
       <DecorationBoundingRect height="0" width="0" x="0" y="0"/>
       <Connects>
        <Connect num="10" port="1"/>
       </Connects>
      </Port>
     </Ports>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="0" codeGenVersion="2.0" dir="$AME/libsig/submodels" hasNoCalc="1" hasTerminate="1" idMax="4" idsReset="0" label="splitter junction" name="SPLT0" outputType="1" type="0" unit="0">
      <ParamsGroups>
       <Group circuitScopeId="17207" editable="0" editableTitle="1" groupHeadIcon="" name="ROOTGROUP" origTitle="ROOTGROUP" subId="4">
        <Elements>
         <Element display="1" varName="in3"/>
        </Elements>
       </Group>
      </ParamsGroups>
      <ExtVars>
       <Port tag="signal">
        <Vars>
         <Var dupType="0" primaryPort="2" primaryVar="0" saveValue="1" subId="1" title="input to junction" type="4" varName="out1" visibility="True"/>
        </Vars>
       </Port>
       <Port tag="signal">
        <Vars>
         <Var dupType="0" primaryPort="2" primaryVar="0" saveValue="1" subId="2" title="input to junction" type="4" varName="out2" visibility="True"/>
        </Vars>
       </Port>
       <Port tag="signal">
        <Vars>
         <Var dimension="1" io="1" saveValue="1" subId="3" title="input to junction" type="0" units="null" varName="in3" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
      </ExtVars>
     </Submodel>
    </Comp>
   </Comps>
   <Lines>
    <Line alias="control_29" circuitScopeId="620" endEntity="0" endPort="2" endType="0" labelVisible="0" startEntity="1" startPort="2" startType="0" type="2">
     <pos configured="0" direction="0" x="0" y="0"/>
     <Points>
      <Point x="564" y="348"/>
      <Point x="202" y="348"/>
     </Points>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="1" codeGenVersion="1.0" idMax="2" label="Direct connection" name="DIRECT" outputType="1" type="0" unit="0">
      <ExtVars>
       <Port tag="undefined">
        <Vars>
         <Var dimension="1" io="1" saveValue="1" subId="1" title="input displacement signal at port 3" type="0" units="null" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
       <Port tag="undefined">
        <Vars>
         <Var dimension="1" io="2" saveValue="1" subId="2" title="output displacement signal at port 3" type="0" units="null" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
      </ExtVars>
     </Submodel>
    </Line>
    <Line alias="control_36" circuitScopeId="621" endEntity="1" endPort="1" endType="0" labelVisible="0" startEntity="0" startPort="1" startType="0" type="2">
     <pos configured="0" direction="0" x="0" y="0"/>
     <Points>
      <Point x="202" y="336"/>
      <Point x="564" y="336"/>
     </Points>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="1" codeGenVersion="1.0" idMax="2" label="Direct connection" name="DIRECT" outputType="1" type="0" unit="0">
      <ExtVars>
       <Port tag="undefined">
        <Vars>
         <Var dimension="1" io="2" saveValue="1" subId="1" title="output velocity signal at port 2" type="0" units="null" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
       <Port tag="undefined">
        <Vars>
         <Var dimension="1" io="1" saveValue="1" subId="2" title="input velocity signal at port 2" type="0" units="null" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
      </ExtVars>
     </Submodel>
    </Line>
    <Line alias="control_37" circuitScopeId="622" endEntity="2" endPort="2" endType="0" labelVisible="0" startEntity="0" startPort="0" startType="0" type="2">
     <pos configured="0" direction="0" x="0" y="0"/>
     <Points>
      <Point x="202" y="324"/>
      <Point x="295" y="324"/>
     </Points>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="1" codeGenVersion="1.0" idMax="2" label="Direct connection" name="DIRECT" outputType="1" type="0" unit="0">
      <ExtVars>
       <Port tag="undefined">
        <Vars>
         <Var dimension="1" io="1" saveValue="1" subId="1" title="input to junction" type="0" units="null" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
       <Port tag="undefined">
        <Vars>
         <Var dimension="1" io="2" saveValue="1" subId="2" title="output force signal at port 1" type="0" units="null" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
      </ExtVars>
     </Submodel>
    </Line>
    <Line alias="control_38" circuitScopeId="623" endEntity="5" endPort="3" endType="0" labelVisible="0" startEntity="7" startPort="1" startType="0" type="2">
     <pos configured="0" direction="0" x="0" y="0"/>
     <Points>
      <Point x="388" y="180"/>
      <Point x="424" y="180"/>
     </Points>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="1" codeGenVersion="1.0" idMax="2" label="Direct connection" name="DIRECT" outputType="1" type="0" unit="0">
      <ExtVars>
       <Port tag="undefined">
        <Vars>
         <Var dimension="1" io="1" saveValue="1" subId="1" title="input z" type="0" units="null" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
       <Port tag="undefined">
        <Vars>
         <Var dimension="1" io="2" saveValue="1" subId="2" title="output from f(x,y,z)" type="0" units="null" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
      </ExtVars>
     </Submodel>
    </Line>
    <Line alias="control_39" circuitScopeId="624" endEntity="7" endPort="2" endType="0" labelVisible="0" startEntity="11" startPort="0" startType="0" type="2">
     <pos configured="0" direction="0" x="0" y="0"/>
     <Points>
      <Point x="295" y="147"/>
      <Point x="342" y="147"/>
      <Point x="342" y="156"/>
     </Points>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="1" codeGenVersion="1.0" idMax="2" label="Direct connection" name="DIRECT" outputType="1" type="0" unit="0">
      <ExtVars>
       <Port tag="undefined">
        <Vars>
         <Var dimension="1" io="1" saveValue="1" subId="1" title="input x" type="0" units="null" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
       <Port tag="undefined">
        <Vars>
         <Var dimension="1" io="2" saveValue="1" subId="2" title="input to junction" type="0" units="null" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
      </ExtVars>
     </Submodel>
    </Line>
    <Line alias="control_40" circuitScopeId="625" endEntity="7" endPort="3" endType="0" labelVisible="0" startEntity="10" startPort="0" startType="0" type="2">
     <pos configured="0" direction="0" x="0" y="0"/>
     <Points>
      <Point x="295" y="216"/>
      <Point x="312" y="216"/>
      <Point x="312" y="180"/>
      <Point x="328" y="180"/>
     </Points>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="1" codeGenVersion="1.0" idMax="2" label="Direct connection" name="DIRECT" outputType="1" type="0" unit="0">
      <ExtVars>
       <Port tag="undefined">
        <Vars>
         <Var dimension="1" io="1" saveValue="1" subId="1" title="input z" type="0" units="null" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
       <Port tag="undefined">
        <Vars>
         <Var dimension="1" io="2" saveValue="1" subId="2" title="input to junction" type="0" units="null" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
      </ExtVars>
     </Submodel>
    </Line>
    <Line alias="control_41" circuitScopeId="626" endEntity="7" endPort="0" endType="0" labelVisible="0" startEntity="6" startPort="1" startType="0" type="2">
     <pos configured="0" direction="0" x="0" y="0"/>
     <Points>
      <Point x="280" y="269"/>
      <Point x="280" y="245"/>
      <Point x="342" y="245"/>
      <Point x="342" y="204"/>
     </Points>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="1" codeGenVersion="1.0" idMax="2" label="Direct connection" name="DIRECT" outputType="1" type="0" unit="0">
      <ExtVars>
       <Port tag="undefined">
        <Vars>
         <Var dimension="1" io="1" saveValue="1" subId="1" title="input y" type="0" units="null" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
       <Port tag="undefined">
        <Vars>
         <Var dimension="1" io="2" saveValue="1" subId="2" title="input to junction" type="0" units="null" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
      </ExtVars>
     </Submodel>
    </Line>
    <Line alias="control_42" circuitScopeId="627" endEntity="5" endPort="0" endType="0" labelVisible="0" startEntity="2" startPort="0" startType="0" type="2">
     <pos configured="0" direction="0" x="0" y="0"/>
     <Points>
      <Point x="325" y="324"/>
      <Point x="438" y="324"/>
      <Point x="438" y="204"/>
     </Points>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="1" codeGenVersion="1.0" idMax="2" label="Direct connection" name="DIRECT" outputType="1" type="0" unit="0">
      <ExtVars>
       <Port tag="undefined">
        <Vars>
         <Var dimension="1" io="1" saveValue="1" subId="1" title="input y" type="0" units="null" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
       <Port tag="undefined">
        <Vars>
         <Var dimension="1" io="2" saveValue="1" subId="2" title="input to junction" type="0" units="null" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
      </ExtVars>
     </Submodel>
    </Line>
    <Line alias="control_43" circuitScopeId="628" endEntity="3" endPort="2" endType="0" labelVisible="0" startEntity="10" startPort="1" startType="0" type="2">
     <pos configured="0" direction="0" x="0" y="0"/>
     <Points>
      <Point x="280" y="231"/>
      <Point x="280" y="237"/>
      <Point x="310" y="237"/>
      <Point x="310" y="260"/>
     </Points>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="1" codeGenVersion="1.0" idMax="2" label="Direct connection" name="DIRECT" outputType="1" type="0" unit="0">
      <ExtVars>
       <Port tag="undefined">
        <Vars>
         <Var dimension="1" io="1" saveValue="1" subId="1" title="input x" type="0" units="null" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
       <Port tag="undefined">
        <Vars>
         <Var dimension="1" io="2" saveValue="1" subId="2" title="input to junction" type="0" units="null" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
      </ExtVars>
     </Submodel>
    </Line>
    <Line alias="control_44" circuitScopeId="629" endEntity="5" endPort="2" endType="0" labelVisible="0" startEntity="13" startPort="0" startType="0" type="2">
     <pos configured="0" direction="0" x="0" y="0"/>
     <Points>
      <Point x="414" y="125"/>
      <Point x="438" y="125"/>
      <Point x="438" y="156"/>
     </Points>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="1" codeGenVersion="1.0" idMax="2" label="Direct connection" name="DIRECT" outputType="1" type="0" unit="0">
      <ExtVars>
       <Port tag="undefined">
        <Vars>
         <Var dimension="1" io="1" saveValue="1" subId="1" title="input x" type="0" units="null" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
       <Port tag="undefined">
        <Vars>
         <Var dimension="1" io="2" saveValue="1" subId="2" title="input to junction" type="0" units="null" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
      </ExtVars>
     </Submodel>
    </Line>
    <Line alias="control_45" circuitScopeId="630" endEntity="13" endPort="2" endType="0" labelVisible="0" startEntity="11" startPort="1" startType="0" type="2">
     <pos configured="0" direction="0" x="0" y="0"/>
     <Points>
      <Point x="280" y="132"/>
      <Point x="280" y="125"/>
      <Point x="384" y="125"/>
     </Points>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="1" codeGenVersion="1.0" idMax="2" label="Direct connection" name="DIRECT" outputType="1" type="0" unit="0">
      <ExtVars>
       <Port tag="undefined">
        <Vars>
         <Var dimension="1" io="1" saveValue="1" subId="1" title="input to junction" type="0" units="null" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
       <Port tag="undefined">
        <Vars>
         <Var dimension="1" io="2" saveValue="1" subId="2" title="input to junction" type="0" units="null" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
      </ExtVars>
     </Submodel>
    </Line>
    <Line alias="control_46" circuitScopeId="631" endEntity="12" endPort="3" endType="0" labelVisible="0" startEntity="13" startPort="1" startType="0" type="2">
     <pos configured="0" direction="0" x="0" y="0"/>
     <Points>
      <Point x="399" y="140"/>
      <Point x="399" y="241"/>
      <Point x="484" y="241"/>
     </Points>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="1" codeGenVersion="1.0" idMax="2" label="Direct connection" name="DIRECT" outputType="1" type="0" unit="0">
      <ExtVars>
       <Port tag="undefined">
        <Vars>
         <Var dimension="1" io="1" saveValue="1" subId="1" title="input z" type="0" units="null" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
       <Port tag="undefined">
        <Vars>
         <Var dimension="1" io="2" saveValue="1" subId="2" title="input to junction" type="0" units="null" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
      </ExtVars>
     </Submodel>
    </Line>
    <Line alias="control_47" circuitScopeId="632" endEntity="12" endPort="2" endType="0" labelVisible="0" startEntity="5" startPort="1" startType="0" type="2">
     <pos configured="0" direction="0" x="0" y="0"/>
     <Points>
      <Point x="484" y="180"/>
      <Point x="498" y="180"/>
      <Point x="498" y="217"/>
     </Points>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="1" codeGenVersion="1.0" idMax="2" label="Direct connection" name="DIRECT" outputType="1" type="0" unit="0">
      <ExtVars>
       <Port tag="undefined">
        <Vars>
         <Var dimension="1" io="1" saveValue="1" subId="1" title="input x" type="0" units="null" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
       <Port tag="undefined">
        <Vars>
         <Var dimension="1" io="2" origTitle="output from f(x,y,z)" saveValue="1" subId="2" title="force after run out" type="0" units="null" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
      </ExtVars>
     </Submodel>
    </Line>
    <Line alias="control_48" circuitScopeId="633" endEntity="12" endPort="0" endType="0" labelVisible="0" startEntity="3" startPort="1" startType="0" type="2">
     <pos configured="0" direction="0" x="0" y="0"/>
     <Points>
      <Point x="356" y="284"/>
      <Point x="498" y="284"/>
      <Point x="498" y="265"/>
     </Points>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="1" codeGenVersion="1.0" idMax="2" label="Direct connection" name="DIRECT" outputType="1" type="0" unit="0">
      <ExtVars>
       <Port tag="undefined">
        <Vars>
         <Var dimension="1" io="1" saveValue="1" subId="1" title="input y" type="0" units="null" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
       <Port tag="undefined">
        <Vars>
         <Var dimension="1" io="2" origTitle="output from f(x,y,z)" saveValue="1" subId="2" title="force amplified" type="0" units="null" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
      </ExtVars>
     </Submodel>
    </Line>
    <Line alias="control_49" circuitScopeId="634" endEntity="1" endPort="0" endType="0" labelVisible="0" startEntity="12" startPort="1" startType="0" type="2">
     <pos configured="0" direction="0" x="0" y="0"/>
     <Points>
      <Point x="544" y="241"/>
      <Point x="554" y="241"/>
      <Point x="554" y="324"/>
      <Point x="564" y="324"/>
     </Points>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="1" codeGenVersion="1.0" idMax="2" label="Direct connection" name="DIRECT" outputType="1" type="0" unit="0">
      <ExtVars>
       <Port tag="undefined">
        <Vars>
         <Var dimension="1" io="1" saveValue="1" subId="1" title="input force signal at port 1" type="0" units="null" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
       <Port tag="undefined">
        <Vars>
         <Var dimension="1" io="2" origTitle="output from f(x,y,z)" saveValue="1" subId="2" title="applied force" type="0" units="null" visibility="True">
          <LaData>
           <Data laStatus="0"/>
          </LaData>
         </Var>
        </Vars>
       </Port>
      </ExtVars>
     </Submodel>
    </Line>
   </Lines>
   <Texts>
    <Text html="&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;>&#xa;&lt;html>&lt;head>&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; />&lt;meta charset=&quot;utf-8&quot; />&lt;style type=&quot;text/css&quot;>&#xa;p, li { white-space: pre-wrap; }&#xa;hr { height: 1px; border-width: 0; }&#xa;li.unchecked::marker { content: &quot;\2610&quot;; }&#xa;li.checked::marker { content: &quot;\2612&quot;; }&#xa;&lt;/style>&lt;/head>&lt;body style=&quot; font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;&quot;>&#xa;&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;>&lt;span style=&quot; font-family:'Arial'; font-size:10pt; color:#000000;&quot;>output&lt;/span>&lt;/p>&lt;/body>&lt;/html>" orientation="0">
     <pos x="616" y="300"/>
    </Text>
    <Text html="&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;>&#xa;&lt;html>&lt;head>&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; />&lt;meta charset=&quot;utf-8&quot; />&lt;style type=&quot;text/css&quot;>&#xa;p, li { white-space: pre-wrap; }&#xa;hr { height: 1px; border-width: 0; }&#xa;li.unchecked::marker { content: &quot;\2610&quot;; }&#xa;li.checked::marker { content: &quot;\2612&quot;; }&#xa;&lt;/style>&lt;/head>&lt;body style=&quot; font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;&quot;>&#xa;&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;>&lt;span style=&quot; font-family:'Arial'; font-size:10pt; color:#000000;&quot;>input&lt;/span>&lt;/p>&lt;/body>&lt;/html>" orientation="0">
     <pos x="104" y="300"/>
    </Text>
    <Text html="&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;>&#xa;&lt;html>&lt;head>&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; />&lt;meta charset=&quot;utf-8&quot; />&lt;style type=&quot;text/css&quot;>&#xa;p, li { white-space: pre-wrap; }&#xa;hr { height: 1px; border-width: 0; }&#xa;li.unchecked::marker { content: &quot;\2610&quot;; }&#xa;li.checked::marker { content: &quot;\2612&quot;; }&#xa;&lt;/style>&lt;/head>&lt;body style=&quot; font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;&quot;>&#xa;&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;>&lt;span style=&quot; font-family:'Arial Black'; font-size:14pt; font-weight:696; color:#0055ff;&quot;>BOOSTER&lt;/span>&lt;/p>&lt;/body>&lt;/html>" orientation="0">
     <pos x="319" y="361"/>
    </Text>
    <Text html="&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;>&#xa;&lt;html>&lt;head>&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; />&lt;meta charset=&quot;utf-8&quot; />&lt;style type=&quot;text/css&quot;>&#xa;p, li { white-space: pre-wrap; }&#xa;hr { height: 1px; border-width: 0; }&#xa;li.unchecked::marker { content: &quot;\2610&quot;; }&#xa;li.checked::marker { content: &quot;\2612&quot;; }&#xa;&lt;/style>&lt;/head>&lt;body style=&quot; font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;&quot;>&#xa;&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;>&lt;span style=&quot; font-family:'MS Shell Dlg 2'; font-size:8pt; color:#000000;&quot;>Force_DeadZone&lt;/span>&lt;/p>&lt;/body>&lt;/html>" orientation="0">
     <pos x="169" y="177"/>
    </Text>
    <Text html="&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;>&#xa;&lt;html>&lt;head>&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; />&lt;meta charset=&quot;utf-8&quot; />&lt;style type=&quot;text/css&quot;>&#xa;p, li { white-space: pre-wrap; }&#xa;hr { height: 1px; border-width: 0; }&#xa;li.unchecked::marker { content: &quot;\2610&quot;; }&#xa;li.checked::marker { content: &quot;\2612&quot;; }&#xa;&lt;/style>&lt;/head>&lt;body style=&quot; font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;&quot;>&#xa;&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;>&lt;span style=&quot; font-family:'MS Shell Dlg 2'; font-size:8pt; color:#000000;&quot;>Force_Runout&lt;/span>&lt;/p>&lt;/body>&lt;/html>" orientation="0">
     <pos x="176" y="115"/>
    </Text>
    <Text html="&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;>&#xa;&lt;html>&lt;head>&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; />&lt;meta charset=&quot;utf-8&quot; />&lt;style type=&quot;text/css&quot;>&#xa;p, li { white-space: pre-wrap; }&#xa;hr { height: 1px; border-width: 0; }&#xa;li.unchecked::marker { content: &quot;\2610&quot;; }&#xa;li.checked::marker { content: &quot;\2612&quot;; }&#xa;&lt;/style>&lt;/head>&lt;body style=&quot; font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;&quot;>&#xa;&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;>&lt;span style=&quot; font-family:'MS Shell Dlg 2'; font-size:8pt; color:#000000;&quot;>Force_Ratio&lt;/span>&lt;/p>&lt;/body>&lt;/html>" orientation="0">
     <pos x="197" y="247"/>
    </Text>
   </Texts>
   <animationProperties loop="0" speed="1"/>
   <globalParams/>
  </Circuit>
 </Supercomponent>
</SUB>
